### ISSUE TITLE
Add vnd.api+json to the media types logged by PAYLOAD_TEXT Verbosity

### ISSUE THREAD

**Issue by NicolaIsotta** [eclipse-ee4j/jersey#3849]
It would be nice if the [vnd.api+json](http://www.iana.org/assignments/media-types/application/vnd.api%2Bjson) media type, used by the [JSON API](http://jsonapi.org/) standard, could be added to the media types logged by the LoggingFeature.Verbosity PAYLOAD_TEXT.

**Comment by arjvik** [comment]
I am working on a pull request for this right now. Note that `application/vnd.api+json` is not an official part of the JAX-RS API spec.
