### ISSUE TITLE
Grizzly does not process HTTP BODY with GET commands using jersey java? Is that the limitation for GET method?

### ISSUE THREAD

**Issue by addprs** [eclipse-ee4j/jersey#3865]

**Comment by psamsotha** [comment]
You can, but you just need to configure it with the method `setAllowPayloadForUndefinedHttpMethods()` of the server configuration.

If you are using the Jersey `GrizzlyHttpServerFactory`, then what you need to is pass a boolean parameter to the overload `createHttpServer()` that will cause the server not to automatically start. This way you can configure it before starting it.

```java
ResourceConfig rc = new ResourceConfig().packages("com.example");
HttpServer server =  GrizzlyHttpServerFactory.createHttpServer(URI.create(BASE_URI), rc, false);
server.getServerConfiguration().setAllowPayloadForUndefinedHttpMethods(true); 
server.start()
```

**Comment by addprs** [comment]
thank you got it.

**Comment by yfrolov** [comment]
> You can, but you just need to configure it with the method `setAllowPayloadForUndefinedHttpMethods()` of the server configuration.
> 
> If you are using the Jersey `GrizzlyHttpServerFactory`, then what you need to is pass a boolean parameter to the overload `createHttpServer()` that will cause the server not to automatically start. This way you can configure it before starting it.
> 
> ```java
> ResourceConfig rc = new ResourceConfig().packages("com.example");
> HttpServer server =  GrizzlyHttpServerFactory.createHttpServer(URI.create(BASE_URI), rc, false);
> server.getServerConfiguration().setAllowPayloadForUndefinedHttpMethods(true); 
> server.start()
> ```

What if I want to stick to JerseyTest? How to do it in this case?

**Comment by jansupol** [comment]
> What if I want to stick to JerseyTest? How to do it in this case?

You need to reimplement GrizzlyTestContainerFactory and configure `server`. See `JerseyTest(TestContainerFactory)` But you are going against the HTTP 1.1, maybe HTTP POST or PUT would suit you better?

**Comment by yfrolov** [comment]
> But you are going against the HTTP 1.1, maybe HTTP POST or PUT would suit you better?

Thanks for your advice @jansupol, I know that it's against the HTTP 1.1, but I just need to create tests for existing code.
