### ISSUE TITLE
Code Question: Multiple implementations of RuntimeDelegate?

### ISSUE THREAD

**Issue by mkarg** [eclipse-ee4j/jersey#3866]
JAX-RS API will load the very first RuntimeDelegate it finds on the classpath. Using `JAXRS_2_2` branch I noticed that (at least) two implementations are registered as such a service: A no-op one from core-common, and a fully-featured from server. I wonder how that shall work? In fact, RuntimeDelegate.getInstance() currently always returns to me the no-op one ffrom core-common, but never the fully-featured from server. If I (manually) remove the no-op's service declaration from META-INF, all works fine.

Can someone please tell me what my fault is? Or is this simply a bug?

**Comment by jansupol** [comment]
It is possible to use only jersey client, and not to have the server jars on classpath. Even then, the Runtime Delegate should be found. That's the one in the core. On the server, the fully featured Runtime Delegate should be used. 

In the upcoming change in JAXRS 2.2, the Jersey Runtime Delegate has been removed from JAX-RS RuntimeDelegate.  In Jersey 2.2 branch, core-common/src/main/resources/META-INF/services/javax.ws.rs.ext.RuntimeDelegate has been created, which seems to cause the issue you report.  This should be fixed. There is org.glassfish.jersey.server.internal.RuntimeDelegateImplTest that tests the correct RuntimeDelegate is loaded.

**Comment by mkarg** [comment]
@jansupol Actually I have no idea how to fix this (other than introducing a proxy implementation dynamically checking whether the full implementation is found on the classpath) as the server module has the core module as a dependency, so maven always will put the partial implementation *before* the full implementation.

**Comment by mkarg** [comment]
A possible solution could be a separation of the client JAR into two JARs: One for standalone Clients, one for server-side Clients. This should be straightforward.

**Comment by jansupol** [comment]
Sorry, what is the exact thing you want to get fixed? Is there anything broken? Is there any misbehavior caused by having two runtime delegates?

**Comment by mkarg** [comment]
From the back of my mind (the original bug report is from 2018) then the problem was (and possibly still is) that the RuntimeDelegate found by the Server is actually the *limited* RuntimeDelegate of the Client, if jersey-client JAR is in the classpath *before* jersey-server JAR. The workaround was (and possibly still is) to sort the classpath accordingly. Maybe Jersey team fixed that since 2018, then we can close this issue. Otherwise we need to find a solution (even if the solution would be to clearly document the behavior).

**Comment by jansupol** [comment]
In 2018, only Jersey 2.x existed. There, the `META-INF/services/javax.ws.rs.ext.RuntimeDelegate` is included just for the server module. Since the API uses the service lookup first, the common/client RuntimeDelegate could be found only as a result of a fallback method in the API when the server module was not on the classpath at all.

In Jersey 3, (where the fallback has been removed from the Jakarta REST API) the common `RuntimeDelegate` has the ability to redirect itself to the server `RuntimeDelegate` so it does not matter which RuntimeDelegate gets loaded first.

**Comment by mkarg** [comment]
So to keep things simple, we should ask people to go with Jersey 3, and close the issue as "will not fix" for users of Jersey 2?

**Comment by jansupol** [comment]
I agree to ask people to go with Jersey 3. However, I do not see anything that needs to be fixed in Jersey 2.

**Comment by mkarg** [comment]
Okay, so I am closing this issue now. Thank you for the clarification! :-)
