### ISSUE TITLE
Fine grained configuration of Jetty HttpClient in jersey-jetty-connector

### ISSUE THREAD

**Issue by cen1** [eclipse-ee4j/jersey#3873]
Jetty HttpClient exposes plenty of configuration options but (almost) none of these are configurable via `jersey-jetty-connector`. Specifically, I'd like to configure `requestBufferSize` to enable support for calling large URLs with the client.

Additionally, since API 2.5 `ClientConfig` now accepts `JettyConnectorProvider` instead of `JettyConnector` and I see no way to pass configuration to the `JettyConnector`.

Before:
```
 ClientConfig config = new ClientConfig();
 Connector connector = new JettyConnector(c); //you can pass some config here
 config.connector(connector);
 Client client = ClientBuilder.newClient(config);
```
API 2.5:
```
ClientConfig config = new ClientConfig();
config.connectorProvider(new JettyConnectorProvider()); //how to configure connector???
Client client = ClientBuilder.newClient(config);
```
Am I just missing something blatantly obvious here?

**Comment by cen1** [comment]
Proposed patch: https://github.com/cen1/jersey/commit/34f43ce252ee17891f1a7ec82992e2edc060490c

I finally figured out I can set these properties via `client.propery()`. Are the other ways?

**Comment by jansupol** [comment]
See [org.glassfish.jersey.jetty.connector.UnderlyingHttpClientAccessTest](https://github.com/eclipse-ee4j/jersey/blob/master/connectors/jetty-connector/src/test/java/org/glassfish/jersey/jetty/connector/UnderlyingHttpClientAccessTest.java) for a way to access Jetty `HttpClient`. Does it help?

**Comment by jansupol** [comment]
Hm...`HttpClient` has `stop()` and `start()` start that can workaround the issue....but I agree its not a nice solution

**Comment by zmanji** [comment]
I have run into a similar issue. I would like to configure the underlying Jetty client to use the [HttpClientTransportOverHTTP2](https://www.eclipse.org/jetty/documentation/9.3.x/http-client-transport.html#_http_2_transport) transport to support HTTP2. However the only way to set the transport is to pass in one via the constructor:
```
    public HttpClient(HttpClientTransport transport, SslContextFactory sslContextFactory)
    {
        this.transport = transport;
        this.sslContextFactory = sslContextFactory;
    }
```

Would it be possible to pass in an `HttpClient` instance into the `JettyConnectorProvider` constructor?

**Comment by cen1** [comment]
That would be the most powerful option and it's an easy fix. The queston is, do you still apply config that is currently in `JettyConnector` or do you consider the client to be good as is and just invoke `start()`?

**Comment by jansupol** [comment]
@zmanji We can create an enhancement allowing to pass the HttpClient/HttpClientTransport instance in using (`ClientConfig#register(new HttpClient(), HttpClient.class)`. Does it sound good?
@cen1 [Your code looks good](https://github.com/cen1/jersey/commit/34f43ce252ee17891f1a7ec82992e2edc060490c). If you want, you can create PR. Please do forget `commit -s` and have an eclipse account associated with git hub id.
Or you can just use the enhancement once it's in.

**Comment by cen1** [comment]
Since @zmanji idea is more general and allows full control over the client configuration I'll prepare a patch with his idea instead.

**Comment by zmanji** [comment]
@jansupol passing in an instance of the client via the `register` method sounds good to me.

**Comment by cen1** [comment]
`JettyConnectorProvider`can't be extended to accept an instance of HttpClient since `getConnector` returns a new instance (although.. why not just return the same instance every time?).

Extending the register method to accept HttClient is a bit beyond my knowledge since I am not familiar with jersey internals.

**Comment by jansupol** [comment]
@cen1 @zmanji Would #4089 help?

**Comment by cen1** [comment]
Patch looks promising. I'll give it a go in the next few days.

**Comment by cen1** [comment]
@jansupol thumbs up from me. Exactly what I needed.

**Comment by cen1** [comment]
This is merged so closing.
