### ISSUE TITLE
SSLConfigurator requires java.util.PropertyPermission for * with read and write

### ISSUE THREAD

**Issue by shaneargo** [eclipse-ee4j/jersey#3879]
Hi,

We are using Jersey Client in an environment which enforces certain Java Security Manager restrictions, which we have no control over, and we have noticed that SslConfigurator requires java.util.PropertyPermission for all properties with read and write.

This class doesn't appear to actually require writing any system properties or the ability to read most.

This is because, when constructing an SslConfigurator using system properties, every system property is loaded (using `PropertiesHelper.getSystemProperties()` which calls `System.getProperties()`), and then the individual properties are selected from the map:
https://github.com/eclipse-ee4j/jersey/blob/12a057315292a624ceb31b58bd04eec3cb19a819/core-common/src/main/java/org/glassfish/jersey/SslConfigurator.java#L310

If this refactored so that `PropertiesHelper.getSystemProperty()` (which calls `System.getProperty()`) instead, then we could grant read-only permissions to the specific system properties.

I'd be happy to do this refactor and send a pull request, I just wanted to run it by you before doing so.

Cheers,
Shane.

**Comment by jansupol** [comment]
Hi Shane,
This sounds reasonable. Please submit the PR.
Thanks,
Jan
