### ISSUE TITLE
Server responds 204 if a json resource method returns null

### ISSUE THREAD

**Issue by FuweiChin** [eclipse-ee4j/jersey#3881]
**Steps to Repreduce:**  
1. jersey dependencies:  
  ```
  org.glassfish.jersey.bundles:jersey-ri:2.27
  org.glassfish.jersey.media:jersey-media-json-jackson:2.27
  ```
2. resource method:  
  ```
  @GET
  @Path("{id}")
  @Produces(MediaType.APPLICATION_JSON)
  public GeoService getServiceById(@PathParam("id") int id) {
  	return geoServiceService.getServiceById(id);
  }
  ```
**Actual Result:**  
if the resource method returns null, then server will respond 204 (No content) with a empty body.

**Expected Result:**  
I'm not sure whether Jersey handles null directly or Jackson's MessageBodyWriter writes null value as empty, but I expect response body to be serialized JSON "null"(without quotes) if the resource method returns null.

**Comment by jansupol** [comment]
Do you have a user specific `MessageBodyWriter<GeoService>` that deals with `nulls`? You can also use Interceptor to set non-null entity

**Comment by FuweiChin** [comment]
I just created a custom `MessageBodyWriter<GeoService>` and a `WriterInterceptor`, guess how? neither of them handles null value (Jersey doesn't call them when the resource method returns null)  .

Maybe I need to change return type of the method to `javax.ws.rs.core.Response` as a workaround.

Thanks for your guidance.
