### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jersey#3909]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by jansupol** [comment]
The job should be created on the new jenkins, as described [here](https://github.com/eclipse-ee4j/jersey/wiki/CI-CD).

**Comment by senivam** [comment]
Jenkins Build CI/CD pipeline are ready to use at:

https://jenkins.eclipse.org/jersey/job/Jersey_master_build/ (build for master branch)
https://jenkins.eclipse.org/jersey/job/Jersey_EE4J_build/ (build for EE4J_8 branch)

Jobs are triggered per commit (push) to appropriate Jersey branch at GitHub

**Comment by m0mus** [comment]
Why it's reopened?
