### ISSUE TITLE
Release pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jersey#3910]
We need to create a release CI/CD pipeline for this project. 

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)

**Comment by jansupol** [comment]
[The link to CI/CD inormation](https://github.com/eclipse-ee4j/jersey/wiki/CI-CD)

**Comment by senivam** [comment]
Job is prepared at 

https://jenkins.eclipse.org/jersey/job/Jersey_release/

it is parametrized. 2 parameters are: 
- release_branch : branch on which release will be performed
- dry_run : whether the job shall really perform release or just test it but do not perform any real changes

default values are EE4J_8_Jenkins and true respectively. The next build shall be probably run using EE4J_8 branch.
