### ISSUE TITLE
@Provider Not effective

### ISSUE THREAD

**Issue by Jiwenzhen** [eclipse-ee4j/jersey#3960]
I want to use Fastjson to implement Json conversion.
this is my code.
`
@Provider
public class FastJsonBodyWriter implements MessageBodyWriter<Object> { 

    @Override
    @Produces(MediaType.APPLICATION_JSON)
    public boolean isWriteable(Class<?> type, 
                      Type genericType, 
                      Annotation[] annotations, MediaType mediaType) { 
        return type.isAnnotationPresent(FastJson.class); 
    }

    @Override
    public long getSize(Object t, Class<?> type, 
                      Type genericType, 
                      Annotation[] annotations, 
                      MediaType mediaType) { 
        return -1;
    }

    @Override
    public void writeTo(Object t, Class<?> type, 
                      Type genericType, 
                      Annotation[] annotations, 
                      MediaType mediaType,
                      MultivaluedMap<String, Object> httpHeaders, 
                      OutputStream entityStream) 
            throws IOException, WebApplicationException {
    	System.out.println("TestFastJsonWriter!!!!!!!");
        entityStream.write(JSONObject.toJSONString(t).getBytes()); 
    }
}
`
but it is no use.
I tried debug, but the breakpoint did not enter this method.

**Comment by senivam** [comment]
the provider itself looks fine, but how do you register it?

**Comment by Jiwenzhen** [comment]
How can I register it?I thought that this would be enough.

**Comment by senivam** [comment]
There are some examples here:

https://jersey.github.io/documentation/latest/deployment.html#environmenmt.appmodel

**Comment by jansupol** [comment]
I am closing this as this looks like an application bug. Feel free to reopen if the problem persists.
