### ISSUE TITLE
WebApplicationException thrown from ClientResponseFilter wrapped in ProcessingException

### ISSUE THREAD

**Issue by wakawaka54** [eclipse-ee4j/jersey#3975]
Current Behavior:

When throwing a WebApplicationException or a sub-class of WebApplicationException, the client runtime wraps the exception in a ProcessingException which makes catching for specific WebApplicationExceptions tidious in client code.

Expected Behavior:

When throwing a WebApplicationException or a sub-class of WebApplicationException, the client runtime should through the WebApplicationException rather than wrapping it in a ProcessingException.

AFAIK, the JAX-RS spec allows for ClientResponseFilter to throw WebApplicationExceptions for non-successful responses.

Sample **ClientResponseFilter**
```java
public class WebErrorFilter implements ClientResponseFilter {
    @Override
    public void filter(ClientRequestContext request, ClientResponseContext response) throws IOException {
        throw new WebApplicationException("A problem occurred");
    }
}
```

**Example Invocation**
```java
try {
     Response response = client.target("http://localhost:1234").request().get();
} catch ( WebApplicationException ex ) {
    // Expect this branch
} catch ( ProcessingException ex ) {
   // Actually goes through this branch with wrapped WebApplicationException
}
```

**Comment by jansupol** [comment]
This is by JAX-RS design. Client side is meant to throw javax.ws.rs.client.ResponseProcessingException rather then WebApplicationException. I believe this is a behaviour of any JAX-RS implementation.  You may start a discussion on JAX-RS issue tracker.
