### ISSUE TITLE
Release to OSSRH staging repository

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jersey#3980]
- [ ] Uptake new Eclipse versions of dependencies. Use [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) wiki to find components versions to use.

- [x] Release to OSSRH staging repository

- [x] Update [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) with released version number. 

[How to release first versions of EE4J components](https://wiki.eclipse.org/How_to_release_first_versions_of_EE4J_components)

**Comment by mkarg** [comment]
It is hard to track progress of this issue. It is open since a month and nobody outside Oracle knows why. I am sure there is a pretty good reason. So it would be cool if you could add just some finer granulated tasks list to this issue naming the hardest issues. So people know what you are currently struggling with and maybe can chime in to help. Just as an idea. :-)

**Comment by jansupol** [comment]
It's quite hard to have the Travis passing as the projects keep missing from OSSRH (a feature of the OSSRH that seems to drop artifacts after a period of time, so I assume JAX-RS would need to be re-staged again in 2-3 weeks, same version)

**Comment by chkal** [comment]
> I assume JAX-RS would need to be re-staged again in 2-3 weeks, same version

We already released JAX-RS 2.1.3 to Maven Central, so this won't be a problem.

**Comment by jansupol** [comment]
#4001

**Comment by senivam** [comment]
blocked by https://bugs.eclipse.org/bugs/show_bug.cgi?id=542441 (permanent timeout on release-job)

**Comment by senivam** [comment]
@arjantijms Jersey is bigger than OpenMQ, that may be the reason. I was trying about 2 days to stage it and upload never finished (always failed on connection timeout). So I've filed a bug to Eclipse just in case they know some trick for that.

**Comment by senivam** [comment]
Done:
https://oss.sonatype.org/content/groups/staging/org/glassfish/jersey
