### ISSUE TITLE
Did jersey-rx-client and jersey-rx-client-java8 get abandoned?

### ISSUE THREAD

**Issue by jawaff** [eclipse-ee4j/jersey#3989]
For Jersey version 2.25.1 there was a jersey-rx-client and jersey-rx-client-java8 extension that added reactive support for built-in Java features. I originally was under the impression that these were the main reactive client extensions, because they're built off of native Java features. However, it now seems like the jersey-rx-client-guava, jersey-rx-client-rxjava and jersey-rx-client-rxjava2 extensions are the only supported extensions now. 

It seems like the person who made this decision doesn't agree with the reactive features that native Java provides, but that's just silly. Jersey basically enforces Java-wide standards for web servers, so it should support at least the native Java features, right? Jersey-rx-client-rxjava in particular already has a replacement for it, so shouldn't that also be abandoned just like jersey-rx-client and jersey-rx-client-java8? If the goal is to abandon extensions that _shouldn't_ be used anymore, then I think jersey-rx-rxjava falls under that category. Otherwise, I see no reason that the mentioned reactive client extensions were abandoned.

Relevant Links:
https://bintray.com/bintray/jcenter/org.glassfish.jersey.ext.rx%3Ajersey-rx-client/2.25.1#files/org/glassfish/jersey/ext/rx/jersey-rx-client
https://bintray.com/bintray/jcenter/org.glassfish.jersey.ext.rx%3Ajersey-rx-client-java8

**Comment by jansupol** [comment]
Jersey 2.25 was JAX-RS 2.0 implementation. JAX-RS 2.1 comes with [reactive client](https://jax-rs.github.io/apidocs/2.1/javax/ws/rs/client/Invocation.Builder.html#rx--). Jersey 2.26+ is JAX-RS 2.1 implementation and [JAX-RS reactive client](https://jersey.github.io/documentation/latest/rx-client.html) is prefered over Jersey original rx client. Do you miss any functionality from the original rx implementation/extension ?

**Comment by jawaff** [comment]
I'm just transitioning to JAX-RS 2.1 from 2.0, so the problem was just that
I was looking in the wrong spot. You linked me to exactly what I was
looking for. I appreciate the help.
