### ISSUE TITLE
Release Jersey 2.29 including #3772 fix

### ISSUE THREAD

**Issue by vreuland** [eclipse-ee4j/jersey#4004]
Hello Jersey maintainers,

I saw in the list of your reported issues that a fix has been made for #3772 a bit more than one month ago. The fix is commited in master and targeted for the next 2.29. 

I tried it and it solves the issue I encounter when using the Spotify Docker Client library (that depends on Jersey, cf. https://github.com/spotify/docker-client/issues/727). 👍 

That is why I would like to ask: Is a release of 2.29 planned already?
If yes, when can it be expected?

Thanks in advance for your return.
Kind regards,
Vincent

**Comment by jansupol** [comment]
Unfortunately, not soon. Currently, we are finishing release 2.28.  Release 2.29 - I believe that can only happen after the legal matters get settled. As far as I know, the legal discussion is in progress. Personally, I'd love to see 2.29 during spring. We are maintaining a [roadmap](https://github.com/eclipse-ee4j/jersey/wiki/Road-Map) which you can watch.

**Comment by glade-at-gigwell** [comment]
Hi guys - wanted to see if there's any further clarity on when releases will start happening again? thanks!

**Comment by jansupol** [comment]
Yes, we are a bit of overdue. We planned to release 2.29 RC1 the last month and 2.29 FINAL this month. Hope we hit at least the second goal.

**Comment by glade-at-gigwell** [comment]
@jansupol Thanks for the update! Is there a place we can monitor or subscribe to know when this is close to release?   Is this issue sufficient? Cheers

**Comment by jansupol** [comment]
@glade-at-gigwell Jersey 2.29 is available in maven central :)

**Comment by larrywest** [comment]
That's great, thank you.

It would also be nice to see the 2.29 release notes on the [project home page](https://jersey.github.io), in addition to your [helpful blog page](http://blog.supol.cz/?p=144).

PS: IMHO every project should have at least links to their release notes in their [github releases page](https://github.com/eclipse-ee4j/jersey/releases). It's an obvious place for users to look.
