### ISSUE TITLE
@PositiveOrZero doesn't work on method parameters

### ISSUE THREAD

**Issue by Glutwolf** [eclipse-ee4j/jersey#4017]
Hey there, I just started working with Jersey 2.27.

When testing a GET-Request with Bean Validation, I noticed that the corresponding method parameters are not validated properly.

Since I have not tried all possibilities, i can only refer to this piece of code:
```java
   @GET
   @Produces(MediaType.APPLICATION_JSON)
   public Response getUser(@PositiveOrZero @PathParam("id") int id) {
        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
        Validator validator = factory.getValidator();
        Object o = validator.validate(id);
    }
```
The @PositiveOrZero annotation in this example is not being validated, while @Min(0) is.

**Comment by Glutwolf** [comment]
After some research, I discovered that jersey still only implements Bean Validation 1.1 (JSR 349) with Hibernate Validator 5.1.3 Final.

Table 2.2, “Bean Validation constraints” under the following link  shows purpose and supported data types of all constraints specified in the Bean Validation API:

https://docs.jboss.org/hibernate/validator/5.1/reference/en-US/html_single/#section-builtin-constraints

Hopefully I could help someone with that.

**Comment by mszabo-wikia** [comment]
@Glutwolf AFAIK the upcoming 2.28 release will implement BV 6.0 as per https://github.com/eclipse-ee4j/jersey/issues/3871
