### ISSUE TITLE
Question: the new version to be released(2.28) will resolve the problem about connection reuse?

### ISSUE THREAD

**Issue by Linary** [eclipse-ee4j/jersey#4024]
I saw some problems about connection reuse, like https://github.com/eclipse-ee4j/jersey/pull/3861,
and the version that has been released to the maven central repository seems to have this problem.
So, will the new version fix it?

**Comment by jansupol** [comment]
#3861 will be in 2.29. So, not in 2.28, sorry. We would like to have 2.29 released in Spring, or as soon as we get a notice from the Eclipse Foundation that all legal matters have been solved and the projects are free to create new releases.

**Comment by jansupol** [comment]
I am sorry, we do not have cycles to check older version for specific bugs. Please try and see
