### ISSUE TITLE
Github Repository Branches Cleanup

### ISSUE THREAD

**Issue by mkarg** [eclipse-ee4j/jersey#4038]
Currently there are lots of (presumably temporary) branches found in the Github repository. This is rather confusing. Also, the branch [JAXRS_2_2](https://github.com/eclipse-ee4j/jersey/tree/JAXRS_2_2) seems to be totally left behind the branch [master](https://github.com/eclipse-ee4j/jersey/tree/master), and it does not build anymore [since months](https://github.com/eclipse-ee4j/jersey/commit/10b22cbca153737d00c0b0e02f302712a00565cc). This makes further contributing to this branch impossible, which is bad, as JAX-RS 2.2 is planned to be release ASAP.

My question is what the plans of the project leads are to fix that. Do you have a time frame when this will be cleaned up (and by whom), or do you want contributors to provide PRs to fix (i. e. rollup with master) that?

**Comment by jansupol** [comment]
What do you mean the branch JAXRS_2_2 does not build? We plan to set up a Jenkins job to build it on Eclipse Jenkins. 
Regarding the JAXRS_2_2, we need to update master with EE4J_8 and then we can update the JAXRS_2_2. I am little worried that JAX-RS 2.2 ASAP release would be a couple of months, though.

**Comment by mkarg** [comment]
"JAXRS_2_2 does not build" means that the existing [Travis Job failed](https://travis-ci.org/eclipse-ee4j/jersey/builds/391810891?utm_source=github_status&utm_medium=notification) building this branch in June 2018 after a commit by Santiago and was not fixed since. It is unclear whether you want to wait for a third party contribution to fix that or whether Santiago is planning to fix it himself or whether you think it will build again once rebased ontop of `master` or something like that.

In fact I am also worried about the long time it will take until we officially MAY release JAX-RS 2.2, because technically we could within days. Too bad the EF and Oracle could not finally find an agreement after so long time. But to be honest, what worries me more is the fact that JAX-RS 2.2 *development* is stuck because of the failing JAXRS_2_2 banch in Travis, as I am using Travis to check feasibility of new features I'm working on for JAXRS_2_2. :-(

**Comment by jansupol** [comment]
We have consolidated the number of branches. There is a PR #4058 to update JAXRS_2_2 branch in Jersey. I used classes from your PR to have the branch built.

**Comment by mkarg** [comment]
Thanks a lot for that! :-)
