### ISSUE TITLE
@Path annotation for root path ("/") is broken in Jersey 2.28

### ISSUE THREAD

**Issue by pmwmedia** [eclipse-ee4j/jersey#4040]
I have just tried to update from Jersey 2.27 to 2.28, and noticed that `@Path("/")` doesn't work anymore. However, `@Path("/foo")` and `@Path("/foo/bar")` do still work. The same problem with `@Path("{any: .*}")`: It still catches `/foo` and `/foo/bar`, but doesn't catch `/` anymore.

**Comment by jansupol** [comment]
Interesting, there is a bunch of tests using `@Path("/")` in Jersey that are passing. Can you provide some details?

**Comment by pmwmedia** [comment]
In my real world project, I use `jersey-container-jetty-http`. This way I got also the new Jetty version when updating to Jersey 2.28. While creating a minimal example project, I found out that the cause is a change in Jetty's `ResourceService`. Therefor I'm closing this issue here.

**Comment by jansupol** [comment]
I am really glad the issue is not on our side. Regarding the connectors, we plan to make them more configurable in 2.29, if that helps.
