### ISSUE TITLE
PATCH 

### ISSUE THREAD

**Issue by AllanHoejgaardJensen** [eclipse-ee4j/jersey#4056]
# PATCH not supported

I had an example using the ReaderInterceptor and used the method work around in order to support PATCH. It seems like that form of support for PATCH is no longer working. 

I recently migrated an example project to Helidon MP and PATCH was not supported in the client. I made a very rudimentary ["hack"](https://github.com/AllanHoejgaardJensen/helidon-breakfastcode-2019/blob/master/src/main/java/org/glassfish/jersey/client/internal/HttpUrlConnector.java#L342) that gave support for PATCH that worked in the example.  

I am not sure whether this is the way you want to create that support. 

However if it is useful for anyone I could create a PR.

**Comment by jansupol** [comment]
The HTTP PATCH is not supported while using the default `HttpUrlConnectionProvider`. The workaround is to use reflection to modify fields of a JDK's `HttpUrlConnection`. Manipulating JDK classes in runtime by default is dodgy, that is why the property `SET_METHOD_WORKAROUND` usage is left on the end-user.

The HTTP PATCH is supported by other connectors, what you just need to do is to use them. Please see [ClientConfig#connectorProvider](https://jersey.github.io/apidocs/latest/jersey/org/glassfish/jersey/client/ClientConfig.html#connectorProvider-org.glassfish.jersey.client.spi.ConnectorProvider-) or for instance [netty example](https://github.com/eclipse-ee4j/jersey/blob/6f425d9cd75192c09dc7e0233d35938d561e15b0/examples/helloworld-netty/src/test/java/org/glassfish/jersey/examples/helloworld/netty/HelloWorldTest.java#L55)
