### ISSUE TITLE
EncodingFilter handles 'Accept-Encoding' header with empty String awkwardly

### ISSUE THREAD

**Issue by tkroehli** [eclipse-ee4j/jersey#4068]
The class _org.glassfish.jersey.server.filter.EncodingFillter_ only checks if the list of values for the 'Accept-Encoding' header is empty but not if a value in the list is empty. A reader is used in _ContentEncoding#fromString_ for this value and the method _hasNext_ is called, but its result is unused. This leads to a ParseException when _nextToken_ is called for an empty String. 
The exception does not lead to errors as it is caught, but still it can lead to lots of unnecessary exceptions and logging output.

**Comment by senivam** [comment]
fixed
