### ISSUE TITLE
Java.util.Date as queryParam is not working in Jersey 2.27 

### ISSUE THREAD

**Issue by PallaviNanjappa** [eclipse-ee4j/jersey#4070]
We have implemented  webservice using Jersey 2.22.1. There are endpoints in webservice which will take date as query and path params.
When we upgraded jersey from 2.22.1 to 2.27, we have noticed that the endpoints which took date as query param returns response as  “PathParam.QueryParamException 404 Not Found” even if the param value is non null. 
In the current code, we have registered custom DateParamProvider as ParamConverterProvider through Abstract binder and is not working in jersey 2.27(and in 2.28) while its working in 2.22.1.

The DateConverterProvider is implemented same as given in below issue.
https://github.com/jersey/jersey/issues/2825

Can someone suggest me to solve this issue?

**Comment by senivam** [comment]
in Jersey 2.22.x was used Binder directly from HK2 - *org.glassfish.hk2.utilities.binding.AbstractBinder* 

In Jersey 2.27 there is builtin Binder - *org.glassfish.jersey.internal.inject.AbstractBinder* 

and it is required to use that Binder in order to process Date QueryParam properly

**Comment by PallaviNanjappa** [comment]
Thank you for the quick response.

The problem is still same.

 I have done custom date param provider registration as below.

register(new org.glassfish.jersey.internal.inject.AbstractBinder() {

    @Override
    protected void configure() {
        bind(MyDateParamProvider.class).to(ParamConverterProvider.class).ranked(10);
    }
});

When I registered in standard way also didn't work.
register(MyDateParamProvider.class);

Please help me to identify the problem.

**Comment by senivam** [comment]
I've implemented a test for that case which demonstrates a possibility of implementation. Please take a look. (#4071)

If it does not help, please provide a reproducer of your specific case.

**Comment by eguller** [comment]
I have created another issue with reproducer project.
@senivam , @PallaviNanjappa can we continue discussion there ?
