### ISSUE TITLE
JerseyClientBuilder modifies Map content during provider registration

### ISSUE THREAD

**Issue by Verdent** [eclipse-ee4j/jersey#4082]
When you try to register new provider with Map of contracts, it will get modified when there is non supported provider class present in the map.

Example:
Map<Class<?>, Integer> contracts = new HashMap<>();
contract.put(ClientRequestFilter.class, 500);
contract.put(SomeCustomClass.class, 501);

contracts.size();// -> returns 2
jerseyClientBuilder.register(MyProvider.class, contracts);
contracts.size();// -> returns 1

**Comment by senivam** [comment]
That is documented behavior:

 /**
     * Create a contract provider for a given component class.
     *
     * @param componentClass  component class to create contract provider model for.
     * @param defaultPriority default component priority. If {@value ContractProvider#NO_PRIORITY},
     *                        the value from the component class {@link javax.annotation.Priority} annotation will be used
     *                        (if any).
     * @param contractMap     map of contracts and their binding priorities. If {@code null}, the contracts will
     *                        gathered by introspecting the component class. Content of the contract map
     *                        may be modified during the registration processing.
     * @param modelEnhancer   custom contract provider model enhancer.
     * @return contract provider model for the class.
     */
    private static ContractProvider modelFor(final Class<?> componentClass,
                                             final int defaultPriority,
                                             final Map<Class<?>, Integer> contractMap,
                                             final Inflector<ContractProvider.Builder, ContractProvider> modelEnhancer)

**Comment by senivam** [comment]
Even though the behavior is documented it does not seem to be correct. Thus fix for it is introduced.

**Comment by senivam** [comment]
merged, fixed
