### ISSUE TITLE
Returning empty rows or sometimes partial entries

### ISSUE THREAD

**Issue by dqlsll123** [eclipse-ee4j/jersey#4088]
The sql queries on DB return the correct data. But rest response is partial or empty. 

For table HR
Columns: id, name, location, birth.
We did a select name, location, birth from HR.
It returns
name location birth
Jack  CA          ****

But rest response would just return name: {name: Jack}

![image](https://user-images.githubusercontent.com/18634176/55052231-5e693800-5015-11e9-89d0-5a4c3e7ff599.png)

[dscs-8974.zip](https://github.com/eclipse-ee4j/jersey/files/3011620/dscs-8974.zip)

**Comment by jansupol** [comment]
[Duplicates Moxy](https://bugs.eclipse.org/bugs/show_bug.cgi?id=545822)

**Comment by jansupol** [comment]
Without a context, this makes no sense. Please add a reproducer.

**Comment by dqlsll123** [comment]
Thanks. Will close it now. Won't be able to provide more details without approve.
