### ISSUE TITLE
StringMessageProvider return character length rather than octet length

### ISSUE THREAD

**Issue by kingsfleet** [eclipse-ee4j/jersey#4093]
StringMessageProvider underestimates the length of the data because it uses the string character length rather than deriving it from a value that depends on the character set encoding.

    @Override
    public long getSize(String s, Class<?> type, Type genericType, Annotation[] annotations, MediaType mediaType) {
        return s.length();
    }

**Comment by senivam** [comment]
Actually this shall not be a subject for fixes. As per documentation this function is deprecated and it is recommended for implementations to return -1l.

   

> /**

     * Originally, the method has been called before {@code writeTo} to ascertain the length in bytes of
     * the serialized form of {@code t}. A non-negative return value has been used in a HTTP
     * {@code Content-Length} header.
     * <p>
     * As of JAX-RS 2.0, the method has been deprecated and the value returned by the method is ignored
     * by a JAX-RS runtime. All {@code MessageBodyWriter} implementations are advised to return {@code -1}
     * from the method. Responsibility to compute the actual {@code Content-Length} header value has been
     * delegated to JAX-RS runtime.
     * </p>
