### ISSUE TITLE
@Priority is not always picked up correctly for JAX-RS providers

### ISSUE THREAD

**Issue by chkal** [eclipse-ee4j/jersey#4099]
There are still some cases where ordering of JAX-RS providers via `@Priority` doesn't work correctly. In my case there are two `ExceptionMapper` instances for the same exception type but with different priorities. Jersey fails to pick up the `@Priority`, which results in a default priority of `Priorities.USER` for both mappers and therefore in random ordering at runtime.

IMO the problem actually occurs for all JAX-RS provider types. It occurs with Jersey 2.28. See the following analysis for details:

Custom providers are looked up in the `Providers` class like this:

https://github.com/eclipse-ee4j/jersey/blob/895c293e366afce166e508ae9db23f9e4b9b5f80/core-common/src/main/java/org/glassfish/jersey/internal/inject/Providers.java#L287-L290

The `getServiceHolders` method gets a `Comparator` which uses `Providers.getPriority()` to order the providers according to the `@Priority` annotation.

https://github.com/eclipse-ee4j/jersey/blob/895c293e366afce166e508ae9db23f9e4b9b5f80/core-common/src/main/java/org/glassfish/jersey/internal/inject/Providers.java#L363-L371

Everything is fine so far. 

The problem is that `Providers.getPriority()` isn't always called with the actual provider implementation class but sometimes gets an instance of `org.glassfish.jersey.inject.hk2.InstanceSupplierFactoryBridge`. This means that Jersey sometimes looks for the `@Priority` on the wrong class and is ignoring the `@Priority` on the actual implementation class.

![image](https://user-images.githubusercontent.com/159245/56075775-31b07100-5dc8-11e9-8f23-32560877e143.png)

The `Providers` class seems to use `ServiceHolder.getImplementationClass()` to get the type of the provider class, which doesn't work correctly in all cases.

https://github.com/eclipse-ee4j/jersey/blob/895c293e366afce166e508ae9db23f9e4b9b5f80/core-common/src/main/java/org/glassfish/jersey/internal/inject/Providers.java#L313-L315

<del>My current guess is that it should use `ServiceHolder.getImplementation**Type**()` instead. But I'll need to verify that. I'll try to create a failing integration tests for this issue.-</del>

**Comment by chkal** [comment]
Please see #4100 for a possible fix. Although I'm not completely sure if it is the best place for a fix.

**Comment by chkal** [comment]
I created #4101 which contains an integration test which reproduces this issue. I hope this helps.

**Comment by jansupol** [comment]
@chkal #4103 Should fix the issue.
