### ISSUE TITLE
Create META-INF/services for JAX-RS RuntimeDelegate and ClientBuilder

### ISSUE THREAD

**Issue by jansupol** [eclipse-ee4j/jersey#4108]
[JAX-RS is about to remove default names of services](https://github.com/eclipse-ee4j/jaxrs-api/pull/755), which would break Jersey. Jersey should add META-INF/services to point to services in Jersey. For RuntimeDelegate, this is already done in JAXRS_2_2 branch.

**Comment by cowwoc** [comment]
Version 3.0.0

When I attempt to use `UriBuilder` I get:

```
java.lang.RuntimeException: java.lang.ClassNotFoundException: Provider for jakarta.ws.rs.ext.RuntimeDelegate cannot be found
	at jakarta.ws.rs/jakarta.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:113)
	at jakarta.ws.rs/jakarta.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:84)
	at jakarta.ws.rs/jakarta.ws.rs.core.UriBuilder.newInstance(UriBuilder.java:69)
```

I attempted to add:

```
<dependency>
	<groupId>org.glassfish.jersey.core</groupId>
	<artifactId>jersey-common</artifactId>
        <version>3.0.0</version>
</dependency>
```

This issue is tagged with version 2.30 but it doesn't look like it was ever fixed in version 3.0.0 (which was just released last week). Also note that I am using Java Modules so that might further complicate the situation. How should I proceed?

**Comment by jansupol** [comment]
We never updated 2.x with this, but you can check 3.x jersey-common.jar; it contains META-INF/services/jakarta.ws.rs.ext.RuntimeDelegate. It contains a 0x0A at the end, though...

If that causes an issue, the workaround would be to add a dependency to core-server, which has the proper runtime delegate and does not have 0x0A at the end of the META-INF/services file.

**Comment by cowwoc** [comment]
@jansupol Thanks for the feedback.

As I mentioned above jersey-common 3.0.0 does not work so this needs to get fixed.
