### ISSUE TITLE
AnnotationAcceptingListener#AnnotatedClassVisitor : This feature requires ASM7

### ISSUE THREAD

**Issue by maxencelaurent** [eclipse-ee4j/jersey#4147]
When such an AnnotatedClassVisitor visits a class with nested elements, ASM7 throws `java.lang.UnsupportedOperationException: This feature requires ASM7.`

AnnotatedClassVisitor implements ASM API 5:
https://github.com/eclipse-ee4j/jersey/blob/44c05a5d32d84b3ee41f9015554eda92d2aa6e31/core-server/src/main/java/org/glassfish/jersey/server/internal/scanning/AnnotationAcceptingListener.java#L166-L168

But visiting module requires ASM 6:
https://github.com/eclipse-ee4j/jersey/blob/44c05a5d32d84b3ee41f9015554eda92d2aa6e31/core-server/src/main/java/jersey/repackaged/org/objectweb/asm/ClassVisitor.java#L128-L136

and nested members, ASM7
https://github.com/eclipse-ee4j/jersey/blob/44c05a5d32d84b3ee41f9015554eda92d2aa6e31/core-server/src/main/java/jersey/repackaged/org/objectweb/asm/ClassVisitor.java#L148-L155
https://github.com/eclipse-ee4j/jersey/blob/44c05a5d32d84b3ee41f9015554eda92d2aa6e31/core-server/src/main/java/jersey/repackaged/org/objectweb/asm/ClassVisitor.java#L234-L241

**Comment by jansupol** [comment]
Fixed by #4148
