### ISSUE TITLE
jersey-bean-validation 2.28 on google app engine

### ISSUE THREAD

**Issue by meilleureVie** [eclipse-ee4j/jersey#4154]
bean validation with api "jersey-bean-validation 2.28" fails on google app engine. It says something like : 
javax.validation.ValidationException: HV000183: Unable to initialize 'javax.el.ExpressionFactory'. Check that you have the EL dependencies on the classpath, or use ParameterMessageInterpolator instead at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.buildExpressionFactory(ResourceBundleMessageInterpolator.java: .....)

---------------------------------------------------
But when i use old api "jersey-bean-validation 2.27" it works.

**Comment by jansupol** [comment]
Since 2.28, jakarta packages are used, [jakarta.el ](https://mvnrepository.com/artifact/jakarta.el/jakarta.el-api) dependency is needed. Any chance you could add the new jakarta API and [impl](https://mvnrepository.com/artifact/org.glassfish/jakarta.el/3.0.2)dependencies?

**Comment by jansupol** [comment]
Basically, `javax.el` should be identical to `jakarta.el` jars, so it should not matter which jar is used, I only suspect the dependencies could be the cause.

**Comment by heatzync** [comment]
Thanks for your comment @jansupol. It helped me realise that there is an API and an Implementation and that I need both.

**Comment by jravi123** [comment]
I'm having the exact same issue and I tried putting the jakarta.el-api and jakarta.el dependencies in pom.xml and changed the org.glassfish.jersey version to all known values, 27, 28 - 34 but still I can;t seem to get rid of this exception - 

1. javax.validation.ValidationException: HV000183: Unable to initialize 'javax.el.ExpressionFactory'. Check that you have the EL dependencies on the classpath, or use ParameterMessageInterpolator instead
2. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of org.glassfish.jersey.server.validation.internal.ValidationBinder$ConfiguredValidatorProvider errors were found
3. java.lang.IllegalStateException: Unable to perform operation: resolve on org.glassfish.jersey.server.validation.internal.ValidationBinder$ConfiguredValidatorProvider


Any inputs will be appreciated!

**Comment by Li-GL** [comment]
> I'm having the exact same issue and I tried putting the jakarta.el-api and jakarta.el dependencies in pom.xml and changed the org.glassfish.jersey version to all known values, 27, 28 - 34 but still I can;t seem to get rid of this exception -
> 
> 1. javax.validation.ValidationException: HV000183: Unable to initialize 'javax.el.ExpressionFactory'. Check that you have the EL dependencies on the classpath, or use ParameterMessageInterpolator instead
> 2. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of org.glassfish.jersey.server.validation.internal.ValidationBinder$ConfiguredValidatorProvider errors were found
> 3. java.lang.IllegalStateException: Unable to perform operation: resolve on org.glassfish.jersey.server.validation.internal.ValidationBinder$ConfiguredValidatorProvider
> 
> Any inputs will be appreciated!

maybe you need to notice the class loading order, refer to https://stackoverflow.com/questions/5474765/order-of-loading-jar-files-from-lib-directory, in my case, I have to put the tomcat-embed-el-9.0.82.jar in front, e.g., `-classpath lib/tomcat-embed-el-9.0.82.jar:lib/*`

**Comment by jansupol** [comment]
It sounds like there is no EL impl on the classpath, just the API.
