### ISSUE TITLE
jersey-common doesn't specify javax.annotation version in manifest

### ISSUE THREAD

**Issue by cliffred** [eclipse-ee4j/jersey#4156]
Since version 2.28, jersey-common does not specify a version number in the Import-Package for javax.annotation in the manifest anymore. This leads to a problem in an OSGi environment (An Eclipse RCP application in my case); javax.annotation is resolved to the system bundle instead of jakarta.annotation-api leading to a java.lang.NoClassDefFoundError: javax/annotation/Priority at runtime. Manually editing the manifest by spicifying a version like `javax.annotation;version="[1.3,2)"` fixes the problem.

**Comment by jansupol** [comment]
The version was removed so that the JDK's annotation is used. Unfortunately, the Priority is not in the package. We should fix the version.

**Comment by jansupol** [comment]
`Priority` is since Common Annotations 1.2

**Comment by jansupol** [comment]
Fixed by #4164
