### ISSUE TITLE
Upgrade Hibernate Validator to 6.0.12.Final

### ISSUE THREAD

**Issue by ielatif** [eclipse-ee4j/jersey#4167]
Build fail localy because Hibernate Validator with Java 11 brings JavaFX on the classpath

> [ERROR] Failed to execute goal on project jersey-gf-ejb: Could not resolve dependencies for project org.glassfish.jersey.containers.glassfish:jersey-gf-ejb:jar:2.29SNAPSHOT: Failed to collect dependencies at org.glassfish.main.ejb:ejb-container:jar:5.1.0-RC2 -> org.glassfish.main.hk2:hk2-config:jar:5.1.0-RC2 -> org.hibernate.vlidator:hibernate-validator:jar:6.0.11.Final -> org.openjfx:javafx.base:jar:11.0.0-SNAPSHOT: Failed to read artifact descriptor for org.openjfx:javafx.base:jar:11.00-SNAPSHOT: Could not transfer artifact org.openjfx:javafx.base:pom:11.0.0-SNAPSHOT

see [Using Hibernate Validator with Java 11 brings JavaFX on the classpath](https://hibernate.atlassian.net/browse/HV-1644)

Upgrade Hibernate Validator to 6.0.12.Final fixes this issue.

**Comment by jansupol** [comment]
Applied for [CQ 20221](http://dev.eclipse.org/ipzilla/show_bug.cgi?id=20221) and [CQ 20222](http://dev.eclipse.org/ipzilla/show_bug.cgi?id=20222) for 6.0.17.Final

**Comment by ielatif** [comment]
@jansupol thanks for sharing the links, but unfortunately i can not access them. I am not able to access IPZILLA.

**Comment by jansupol** [comment]
@ielatif I will notify here when CQs get approved

**Comment by jansupol** [comment]
Fixed by #4172

**Comment by ielatif** [comment]
@jansupol thanks

**Comment by jansupol** [comment]
The CQs have been approved.
