### ISSUE TITLE
Missing class-level @Path results in no match

### ISSUE THREAD

**Issue by nkiesel** [eclipse-ee4j/jersey#4169]
Hi,

I have a very simple class with a single endpoint:
```java
public class Metrics {
    @GET
    @Path("/metrics")
    @Produces(MediaType.TEXT_PLAIN)
    public String getMetrics() {
        return "yeah";
    }
}
```
This will not be matched unless I add a `@Path("/)` to the class.  is that expected? I read the spec to say that either class or method (or both) should be sufficient.

Also, what do I have to do for Jersey to tell me that it did not find a match? I have all logging and tracing enabled but this seems to silently fail.  is there a way to ask Jersey for all the available templates?

**Comment by jansupol** [comment]
Hi,
Section 1.5 of the Spec says:

> Root resource class A resource class annotated with `@Path`. Root resource classes provide the roots of the resource class tree and provide access to sub-resources

If no `@Path` is on the resource, then it is supposed to be a subresource, accessible via subresource locators.

You can get a list of endpoints from a [wadl](https://jersey.github.io/documentation/latest/wadl.html)
