### ISSUE TITLE
ServerRuntime.mapException() throws NullPointerException for NotFoundException default constructor

### ISSUE THREAD

**Issue by geoffreyharding** [eclipse-ee4j/jersey#4171]
There is a missing check for null in org.glassfish.jersey.server.ServerRuntime.java in mapException():

```
    waeResponse = webApplicationException.getResponse();
    if (waeResponse.hasEntity()) {
```

Corresponds to line 514 in version 2.28

A NullPointerException can be thrown here for any WebApplicationExceptions with a null response.  The easiest repro is to throw a NotFoundException using the default constructor.
Example:
```
	@GET
	@Path("/test")
	public void testGet()
	{
		throw new javax.ws.rs.NotFoundException();
	}
```

**Comment by jansupol** [comment]
How did you manage not to have a Response?
```
        NotFoundException exception = new NotFoundException();
        Assert.assertNotNull(exception.getResponse());
```

**Comment by okarpukhin** [comment]
I've faced the same issue in one of my tests using mockito (v5.8.0):
```
        when(mockFooService.barMethod()).thenThrow(NotFoundException.class);
```
`Mockito` somehow creates an instance of `NotFoundException` without a `Response`.

If I pass an instance of `NotFoundException` (instead of class), the test works as expected:
```
        when(mockFooService.barMethod()).thenThrow(new NotFoundException());
```

**Comment by jansupol** [comment]
A user-defined subclass of `WebApplicationException` might return null, correct.
