### ISSUE TITLE
Inconsistent behavior when it comes to parsing values

### ISSUE THREAD

**Issue by maald** [eclipse-ee4j/jersey#4192]
When it comes to parsing string values to objects,  there is inconsistent behavior for different data types. 

With most data types (Integer/Double/Float/Character/Byte), you get:

-  an error on startup if the decalred default value, provided as a string, cannot be parsed (e.g., `( @QueryParam("n") @DefaultValue("foo") Integer n)`).  

- 404 error code if the dynamic value is invalid/parsing fails (e.g., `path?q=foo` for `(@QueryParam("n") Integer n)` ). 

- `null` value if the request url doesn't include the declared query parameter or it's included without a **value** (e.g., `path?` and `path?q=` for `(@QueryParam("n") Integer n)` ). String query parameters are an exception; for String data type, `null` value is provided only if the query parameter is not present; if the query parameter (the **name**) is included without a **value** ( `path?q=` ) then it's treated as an empty string by the runtime.

On the other hand, Boolean data type seems to be handled differently / have inconsistent behavior with what I described above; startup error and runtime 404 error code will never occur even if the string values are not boolean compatible. `null` value is provided only if the query is not included in the request url (Boolean and String fall back to some default value when the query parameter value is not included / unlike other data types which return `null`). If a default `true` value is misspelled, then it will just be parsed to `false` value without warnings!

```java

@GET
@Path("{var}")
public String booleans(
           @PathParam("var") Boolean ppValue,                                                                            
           @QueryParam("query") Boolean qpValue,                             
           @QueryParam("default") @DefaultValue("invalid") Boolean dqpValue
){
        StringBuilder sb = new StringBuilder("-- boolean values -- \n");

        sb.append("var       = ").append(Objects.toString(ppValue)).append("\n");
        sb.append("query   = ").append(Objects.toString(qpValue)).append("\n");
        sb.append("default = ").append(Objects.toString(dqpValue)).append("\n");

        return sb.toString();
}
```

```
curl 'http://.../not-boolean'     // @PathParam
```

> -- boolean values --
var       = false            (`false` instead of 404 at runtime)
query   = null             (ok)
default = false            (`false` instead of startup error)

```
curl 'http://.../not-boolean?query='      // query without a value
```

> -- boolean values --
..
query    = false            (`false` instead of null) 
..

```
curl 'http://.../not-boolean?query=foo&default=bar'   // all invalid
```

> -- boolean values --
(no startup or runtime errors for all)
var       = false  
query   = false
default = false

JAX-RS defines what data type you can use with resource method parameters and resource fields / properties:

> - Be a primitive type 
> - Have a constructor that accepts a single String argument
> - Have a static method named valueOf or fromString that accepts a single String argument (see, for example, Integer.valueOf(String))
> - Have a registered implementation of ParamConverterProvider JAX-RS extension SPI that returns a ParamConverter instance capable of a "from string" conversion for the type.
> - Be List<T>, Set<T> or SortedSet<T>, where T satisfies 2, 3 or 4 above.

I think Jersey is mostly following that rules by using `Boolean.valueOf(string)` API to parse the string values. The API states that any value, including `null`, is parsed to `false` unless the string value is `"true"` (case insensitive). On the other hand, `path?q=` is parsed into an empty string value _even though_ `new String(stringVarWithNullValue)` throws NPE and `String.valueOf(stringVarWithNullValue)` returns `null`. 

Given that String values are handled in a different manner, I think it's reasonable to expect that string values for Boolean type should get validated first before parsing so it's consistent will almost all other data types. Otherwise, even API clients now have adopt Java Boolean API behavior (i.e., their testing code will just have to assume that any string value other than "true" will become "false" instead of 4XX error code).

**Comment by maald** [comment]
@mkarg any thought on this? any feedback is appreciated.

**Comment by mkarg** [comment]
What exactly is your question? Whether this is a bug? Whether this is a violation of spec?

**Comment by maald** [comment]
I think the spec distinguishes between primitive and Object data types (primitive wrappers and user defined). It doesn't have a special case for parsing strings into Boolean type. 


I believe Jersey follows the spec by calling Boolean.valueOf(str). Unfortunately, Boolean.valueOf API behavior is tricky/designed for convenience. The expectation is that the API caller knows about the API contract. However, many JAX-RS developers and all API clients don't typically know about this implementation detail (how a string is parsed into Boolean) whenever they use boolean values. Because of the current behavior, even API clients will need to be aware of this implementation detail.


Here is an example of bugs waiting to happen:

API:
```
method(
      @QueryParam("q1") String s,
      @QueryParam("q2") Boolean b
) 
```

By mistake, the client makes a request with:
```
...?q1=true&
    q2=string
```
or with
```
...?q1=string&
    q2=
```
Because of the current behavior, the client can't easily detect this mistake (i.e., get an error message stating that `q2` must be a valid boolean string). It will silently convert `q2` to `q2=false` in both cases and continue without any warning. As a result, the client will need to know that the backend uses JAX-RS runtime which uses Boolean.valueOf(str) API in order to understand why boolean query parameters never return an error regardless of query values. It gets worst if the developer or client misspelled `true` for a default value or the API call.


The current behavior is like working with "truthy and falsey" semantic.


I doubt this's the desired or intended behavior by the spec. Just wanted to hear your thoughts on this. maybe the spec can suggest that implementations should be strict about parsing string values to Boolean data type (null of empty strings, error for values other than "true"/"false"). After all, if developer or a client passes a boolean string then it's more likely than not they want/expect the runtime to warning them if that string value is not "true"/"false" so it can be fixed right away.

**Comment by mkarg** [comment]
Have you read the spec?

**Comment by maald** [comment]
I'm new to JAX-RS but I have read some of spec document for 2.1 (namely chapter 3 where resources are discussed). I also browsed the JavaDoc for QueryParam and DefaultValue [here](https://jax-rs.github.io/apidocs/2.1) and I'm using Jersey to test the behavior. Not sure if I'm missing something or my previous comments are false.

**Comment by mkarg** [comment]
Chapter 3 clearly explains how data types are to be converted. From that list (1 through 4) it becomes obvious that String, Integer and Boolean definitively will behave differently, as there is no String-to-String conversion at all (hence _all_ Strings are valid, even _empty_ ones), and String-to-Integer works definitively differently than String-to-Boolean (e. g. the JRE _does not even specificy_ the outcome of `valueOf()` with an empty String value, so it _could_ be anything like `TRUE`, `FALSE`, `null` or `throw RuntimeException`) thanks to the source code of the JRE which you can easily inspect. It even would be valid that different JREs behave differently here. The JAX-RS specification will not mandate the JRE's job, it will just build *ontop* of that. If you want a safety check to guarantee uniform error essages, you need to use either Bean Validation or write your own Container Request Filter. That's clearly the application vendor's job, not the JAX-RS vendor's or the JRE's vendor's.

If you think _Jersey is not compliant to the spec_, please *briefly* set up a test case proofing which rule of the spec is not followed.

If you think the _spec is not clear enough_, please *briefly* propose a wording in the JAX-RS issue tracker (not the Jersey issue tracker).

If you want something different than that, please tell me *briefly* _what_.

**Comment by spericas** [comment]
@maald You may want to check `ParamConverter` and `ParamConverterProvider` if the standard behavior isn't ideal for your use case.

**Comment by maald** [comment]
@mkarg I appreciate the feedback a lot. I definitely wasn't aware that different JRE have different behavior for parsing empty string using `Boolean.valueOf(string)` API.

Given your feedback, I wouldn't call it a Jersey or spec issue. If Jersey were to change this behavior/"fix it" by being strict about the String-to-Boolean conversion then it would not be compliant with the spec. So I properly just close this ticket.

@spericas , that was my initial thought too. I was digging into Jersey source code and came across that.



Just some personal views:
I don't see mandating that implementations be strict about String-to-Boolean conversion as fixing the JRE problem. After all frameworks sit in a middle layer between the application and the environment in which they run. A framework often tries to smooth out the different behavior originating from the layer beneath it so that applications built on top of it can get a consistent behavior instead of having to dig into the minor technical details of each environment and code around it. 

A basic application that runs just fine on one JRE but throws a runtime exception in another is definitely a terrible thing to have to deal with. To put it another way, when asked "what's the expected behavior if the DefaultValue or request contains invalid boolean string?", a developer will have to say "out of the box, it depends on the JRE running the app. you may get 4xx error code or the string will be converted to false". 

JAX-RS is definitely extensible and I love that. I just think having to repeat yourself by writing/copy-pasting the same code for every JAX-RS App you build just to get a predictable and safe String-to-Boolean conversion behavior is unproductive at best. It's nice when frameworks try to reduce the need to repeat yourself in every app and do extra work (opt-in) just to get a consistent behavior. I really doubt that anyone would be unhappy if String-to-Boolean conversion in the spec was strict and the expected behavior is consistent regardless of the JRE environment. Just imagine how many bugs & "it worked on this machine but not that" will be eliminated with a simple "it must be either "true" or "false" string value" rule. 

Again that's just my own personal view which some might disagree with. 


thanks all for the input.
