### ISSUE TITLE
JacksonFeature ExceptionMappers leaks implementation details

### ISSUE THREAD

**Issue by feinstein** [eclipse-ee4j/jersey#4200]
The `JacksonFeature` `ExceptionMapper<JsonParseException>` and `ExceptionMapper<JsonMappingException>` Exception Mappers return the full error message as the Response body and there's no way to catch it and remove it.

I have an `AutoValue` class that Jackson tries to convert from JSON, if there's an error in the conversion (my `AutoValue` class doesn't accepts empty strings for its `name` field), I get a 400 Response with the text:

>Cannot construct instance of \`com.example.vo.AutoValue_User$Builder\`, problem: Last name is null or empty.
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 14, column: 1]

I tried to use an `ExceptionMapper<Throwable>` to catch all exceptions, log them, and return an empty Response, but it didn't work. I also tried to make my own version of the  `ExceptionMapper<JsonParseException>` and `ExceptionMapper<JsonMappingException>` as it was suggested to me, but this didn't work either (worked on Tomcat, but not on other servlet containers).

Is it there a way to remove this body message? 
Could you guys remove this or make it a separate module so only those interested would include it, and the rest of us could just catch those exceptions in our own Exception Mappers?

**Comment by jansupol** [comment]
Fixed by #4225
