### ISSUE TITLE
Link to user guide from Github

### ISSUE THREAD

**Issue by cowwoc** [eclipse-ee4j/jersey#4207]
I couldn't find any links to the user manual, from Github or from the Eclipse project page.

Please link to https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/user-guide.html from the main Github landing page. This will help users get started with this project.

**Comment by jansupol** [comment]
On the [WIKI](https://github.com/eclipse-ee4j/jersey/wiki), we have a link to our [documentation](https://jersey.github.io/). As noted, it is in the process to be migrated to the page you [pointed out]( https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/user-guide.html). Currently, the original [documentation ](https://jersey.github.io/documentation/latest/index.html) is the primary source. Unfortunately, it does not contain the correct 2.29 version of the documentation, yet. We are working on it.

**Comment by jansupol** [comment]
You have a good point to have a link to the documentation more visible from the main GitHub page, though.

**Comment by jansupol** [comment]
I have added a link to the wiki to the top of the GitHub project. There is a link to the documentation.
