### ISSUE TITLE
Integration with CDI (Weld) causes warnings

### ISSUE THREAD

**Issue by tomas-langer** [eclipse-ee4j/jersey#4216]
When running Jersey on top of Weld, I get the following error messages:
```
2019.08.06 11:42:31 INFO org.jboss.weld.Event Thread[main,5,main]: WELD-000411: Observer method [BackedAnnotatedMethod] private org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider.processAnnotatedType(@Observes ProcessAnnotatedType) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
2019.08.06 11:42:31 WARN org.jboss.weld.Bootstrap Thread[main,5,main]: WELD-000146: BeforeBeanDiscovery.addAnnotatedType(AnnotatedType<?>) used for class org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider$JaxRsParamProducer is deprecated from CDI 1.1!
```

Weld: 3.1.1
Jersey: 2.29

How to reproduce:
 - follow a quickstart guide for Helidon MP, version 1.2 or newer:
https://helidon.io/docs/latest/#/guides/03_quickstart-mp

Start the application - observe the standard output

**Comment by tomas-langer** [comment]
Problem defined by the info message has quite a big impact on startup of Helidon applications.

**Comment by jansupol** [comment]
This looks like Jersey 2.26. Are you sure it's 2.29?

**Comment by jansupol** [comment]
The INFO message does not seem possible to fix by `@WithAnnotations`, as noted in [CdiComponentProvider](https://github.com/eclipse-ee4j/jersey/blob/66f5cfa1804e4e29dac456744d41bc7e8b66ad57/ext/cdi/jersey-cdi1x/src/main/java/org/glassfish/jersey/ext/cdi1x/internal/CdiComponentProvider.java#L528). Weld does not provide a way to [turn the info off](https://issues.jboss.org/browse/WELD-2130).

The WARNING should be [fixed](https://github.com/eclipse-ee4j/jersey/commit/5319e7975ad83e22abc6021a6dcb99e524888dd5#diff-467ecf5a2c720057361484958eea31fa) in 2.29.

**Comment by ljnelson** [comment]
(Lurking, but the line in `CdiComponentProvider` you reference is not a lifecycle observer method.  `@Observes` is commented out.)

**Comment by jansupol** [comment]
@ljnelson Originally, when the comment was put to Jersey, `ProcessAllAnnotatedTypes` did not yet exist. When it was created, the `@Observes` was moved there, but the comment remained in the `CdiComponentProvider`. Of course, `@WithAnnotations` would be needed to be put to `ProcessAllAnnotatedTypes`, but the comment is still valid for the new class.
