### ISSUE TITLE
WriterInterceptor called AFTER ContainerResponseFilter

### ISSUE THREAD

**Issue by mkarg** [eclipse-ee4j/jersey#4223]
According to JAX-RS 2.1 Specification PDF Figure C.2: *JAX-RS Client Processing Pipeline* (page 82) `WriterInterceptor` has to be invoked *before* `ContainerResponseFilter`.

In fact, Jersey 2.29 (I tried it directly on Java SE 8) actually invokes the interceptor *after* the filter.

Proof:
```java
public class Proof implements WriterInterceptor, ContainerResponseFilter {

    @Override
    public void aroundWriteTo(WriterInterceptorContext context) throws IOException, WebApplicationException {
        System.out.println("aroundWriteTo " + System.nanoTime());
        context.proceed();
    }

    @Override
    public void filter(ContainerRequestContext requestContext, ContainerResponseContext responseContext) throws IOException {
        System.out.println("filter " + System.nanoTime());
    }

}
```
prints:
```bash
filter 107293929846300
aroundWriteTo 107293932276200
```
(compare the print sequence and the printed nanotime)

*I noticed this when I tried to pass a property from the interceptor to the filter: The property is **missing** in the filter's request context!*

This is a *critical* problem in several cases:
* When the interceptor replaces the entity.
* When the interceptor has to pass properties to the filter.

**Comment by jansupol** [comment]
I must be missing something. `ContainerResponseFilter` is a server-side only class. I.E. Figure C.2: JAX-RS Client Processing Pipeline does not apply to it. Rather, Figure C.1: JAX-RS Server Processing Pipeline applies to order of executions of `ContainerResponseFilter` and `WriterInterceptor`. But from Fig.1, _Container response chain_, I'd understand the `ContainerResponseFilter` is executed first and the `WriterInterceptor` afterward.

**Comment by mkarg** [comment]
@jansupol Damned, you're right. I actually missed the word "Client" client! Silly me!
