### ISSUE TITLE
Java 11 profiles are adding extra dependencies

### ISSUE THREAD

**Issue by srdo** [eclipse-ee4j/jersey#4229]
Hi,

As part of Java 11 compatibility, several Jersey modules have Java 11 profiles that add extra dependencies to the dependency tree, e.g. this one https://github.com/eclipse-ee4j/jersey/blob/d3b2d63f9e04769b84f7992e3857218d90a9d8a0/core-common/pom.xml#L297

We are using Jersey in an application (Apache Storm) we distribute binaries for. This binary distribution comes bundled with the application's dependencies, including Jersey and its transitive dependencies.

Since the extra Java 11 dependencies are only present when building Storm with Java 11, I am concerned that a binary distribution built with Java 8 won't necessarily work when run on Java 11, as it will be missing the extra jars. 

The jars I'm seeing added in Java 11 are:
* com.sun.activation:jakarta.activation:1.2.1
* jakarta.activation:jakarta.activation-api:1.2.1
* jakarta.xml.bind:jakarta.xml.bind-api:2.3.2

Would it be possible for Jersey to add the extra Java 11 jars to Jersey's regular dependency set, so they are present in both Java 8 and 11 builds, or will having these jars present for Java 8 cause issues?

**Comment by jansupol** [comment]
JAX-B and Activation are part of JDK 8, so there is no additional dependency needed for JDK 8. Since these dependencies are no longer part of JDK11, it is necessary to add them there.

**Comment by srdo** [comment]
@jansupol Thanks, but that wasn't really what I meant.

I'm asking if these dependencies can be added to the JDK 8 build as well (assuming this doesn't cause issues on Java 8), so the dependency tree doesn't change depending on whether I'm building with JDK 8 or 11.

**Comment by jansupol** [comment]
I do not think we should demand those dependencies for JDK8. But it should be easy for a consumer of Jersey to demand the dependencies in their app. Just add them in maven pom when declaring dependencies.

**Comment by srdo** [comment]
Ok, thanks. We'll add the extra dependencies to our POM. The reason I thought it made sense to add them to JDK 8 Jersey is so other projects that distribute binaries or fat jars built on Java 8 aren't surprised by this.
