### ISSUE TITLE
Java 11 java.desktop module dependency

### ISSUE THREAD

**Issue by dconnelly** [eclipse-ee4j/jersey#4245]
Not sure why Jersey should have any dependency on AWT classes, but I am seeing this warning when running a Dropwizard/Jersey app under Java 11:
```
WARNING: HK2 service reification failed for [org.glassfish.jersey.message.internal.RenderedImageProvider] with an exception:
MultiException stack 1 of 2
java.lang.NoClassDefFoundError: java/awt/image/RenderedImage
```
We probably should move this provider to a separate maven module, and document that for Java 11+ the 'java.desktop' module would be required for usage.

**Comment by arjantijms** [comment]
Maybe it's because of a property converter being used somewhere (this is often used for low level conversions, see e.g. https://arjan-tijms.omnifaces.org/2014/08/high-time-to-standardize-java-ee.html)

That one has an awkward historical dependency on AWT indeed. Many server apps use this one.

**Comment by jansupol** [comment]
relates to #4293
