### ISSUE TITLE
How to implement cron with jersey ?

### ISSUE THREAD

**Issue by meilleureVie** [eclipse-ee4j/jersey#4259]
How to implement cron with jersey ?

**Comment by jansupol** [comment]
Not sure what you ask for. There is an [EJB functionality](https://docs.oracle.com/javaee/6/tutorial/doc/bnboy.html) which you can use in the resource class.

Or maybe you ask for an asynchronous response to be sent after a time out. 

In general, I do not feel the issue tracker is a place for these types of questions. You may try SO.

**Comment by meilleureVie** [comment]
i want to create a task which will be run every day a 24h:00. How make it
with jersey

**Comment by senivam** [comment]
Jersey is JAX-RS implementation. It is not designed to schedule tasks. 

How to schedule tasks is described for example here: https://stackoverflow.com/questions/22163662/how-to-create-a-java-cron-job
