### ISSUE TITLE
@Context injection not working in ContainerRequestFilter instanciate from dynamicFetaure

### ISSUE THREAD

**Issue by meilleureVie** [eclipse-ee4j/jersey#4261]
I need to register a custom intance of requestFilter from dynamic feature and want to get all injected objects with @context or @Inject injected.
In my case, I need a custom instance of requestFilter because i override RolesAllowedDynamicFeature to support i18n response output. despite the fact to instanciate your RolesAllowedRequestFilter within AuthorizationDynamicFeature i need also to inject a messageInterpolator that i have created and binded. 
Sorry for my bad english

**Comment by jansupol** [comment]
`@Context`/`@Inject` is used only when instantiated by Jersey during a request. Do you register an instance or a class?

**Comment by meilleureVie** [comment]
Instance

**Comment by jansupol** [comment]
Right, with instance, the injection will never work. Try registering a class.

**Comment by meilleureVie** [comment]
Register class is not a good choice for me. I need to register an instance
because l need to instanciate my filter with custom parameter

**Comment by jansupol** [comment]
You would need to register a class. Passing the custom paramater would need to be done some other way. Either register a binder where you would bind the custom class with custom parameters and inject this custom class as well. Or you can create two filters one as a class and one as an instance. The instance would have the custom properties and it will set them to the context#setproperty. You would need to set priority for the instance fiter to be executed first.

**Comment by jansupol** [comment]
Or you can set the property in the `ResourceConfig`. There are multiple options.

**Comment by meilleureVie** [comment]
Ok thanks
