### ISSUE TITLE
ContextResolvers registered as lambdas are not be invoked

### ISSUE THREAD

**Issue by thoraage** [eclipse-ee4j/jersey#4278]
On jersey-server version 2.29.1 or earlier (2.26 at least) the code below will depend on whether the context resolver is implemented as a sub class or as a lambda. If you're using the lambda version it will never be invoked.

```
final ObjectMapper objectMapper = ...;
final ContextResolver<ObjectMapper> contextResolver2 = type -> objectMapper;
final ContextResolver<ObjectMapper> contextResolver1 = new ContextResolver<ObjectMapper>() {
    @Override
    public ObjectMapper getContext(Class<?> type) {
        return objectMapper;
    }
 };
return new ResourceConfig(MyResource.class)
    .register(contextResolverx);
```

**Comment by jansupol** [comment]
When you create lambda, the lambda class is not an instance of `ParametrizedType`, i.e. there is no known parametrized type argument. In other words, in runtime, the `<ObjectMapper>` is not obtained from the class created by the lamdba definition.

So it is actually registered, but as `ContextResolver<Object>`.
