### ISSUE TITLE
Observable/Single and Flux/Mono support

### ISSUE THREAD

**Issue by politrons** [eclipse-ee4j/jersey#4289]
I´m getting crazy trying to test my Jesey service using JerseyTest to make my endpoints return a Mono, Flux, Single or Observable, but I was not able so far.

Any documentation that I can follow to see how to confgure my service to provide this feature.

For the resource config I'm trying

  ```
  ResourceConfig rc = new ResourceConfig();
            rc.register(SpringLifecycleListener.class);
            rc.register(RequestContextFilter.class);
            rc.register(new JacksonFeature());
            rc.register(new ObjectMapperContextResolver());
            rc.register(new JacksonJsonProvider());
            rc.register(new ReactorInvokerProvider());


        @GET
        @Path("jax-rs-flux")
        @Produces(MediaType.APPLICATION_JSON)
        public Mono<String> getJsonImplicitListStreamingAsync2() {
            return Mono.just("Hello world flux");
        }
```

And in the client

   ```
     List<String> collector = new ArrayList<>();
        Client client = ClientBuilder.newClient();
        WebTarget target = target().path("reactive/jax-rs-flux");
        client.target(target.getUri())
                .register(new JacksonJsonProvider())
                .register(new ReactorInvokerProvider())
                .request(MediaType.APPLICATION_JSON)
                .rx(ReactorInvoker.class)
                .get(String.class)
                .doOnNext(rr -> {
                    collector.add(rr);
                })
                .subscribe();

```

So far I only manage to receive in onNext callback `{"scanAvailable":true}`

Regards

**Comment by jansupol** [comment]
Not sure what your problem is. But I assume, you do not see error logs. You can make them available in JerseyTest as follows:
```
    @Override
    protected Application configure() {
        set(TestProperties.RECORD_LOG_LEVEL, Level.FINEST.intValue());
        return new ResourceConfig()....;
    }

@Test
public void test() {
   ....
        List<?> logRecords = getLoggedRecords();
        for (final LogRecord logRecord : getLoggedRecords()) {
                System.out.println(logRecord.getMessage());
            }
        }
}

```

**Comment by jansupol** [comment]
Maybe if you have issues on the server side with sending Mono, add an ExceptionMapper<Exception> and print the exception message.

**Comment by politrons** [comment]
Hi,  thanks for answer.

No error in logs, I just receive in onNext function

`{"scanAvailable":true}`

Do you know what that json means?. Maybe the MediaType is incorrect?.

I was following the JaxRS 2.1 documentation

https://cwiki.apache.org/confluence/display/CXF20DOC/JAX-RS+RxJava

Do you know a documentation or example of Jersey server implementing this solution to follow?

Regards

**Comment by jansupol** [comment]
> No idea what means :(

That means it is a client side class. It does have no meaning on a server, as it (I assume) implements the `RxInvoker` class.

**Comment by politrons** [comment]
Any suggestion how to implement the client properly?

**Comment by jansupol** [comment]
I just found [this](https://stackoverflow.com/questions/53822069/reactor-rest-mono-returns-scanavailable-true), might relate.

**Comment by politrons** [comment]
I saw that stackoverflow post before, and is not related. I will continue searching for a working example

**Comment by jansupol** [comment]
There is a `RxInvoker<Observable>` implementation in [rx-client-rxjava module](https://github.com/eclipse-ee4j/jersey/blob/master/ext/rx/rx-client-rxjava/src/main/java/org/glassfish/jersey/client/rx/rxjava/RxObservableInvoker.java) if that helps.

**Comment by jansupol** [comment]
Closing as this seems to be resolved

**Comment by 4501** [comment]
Hi @Politron ,I am also facing similar issue.Could you please help me?

**Comment by 4501** [comment]
Hi @Politron ,I am also facing similar issue.Could you please help me?

**Comment by 4501** [comment]
Hi @Politron ,I am also facing similar issue.Could you please help me?

**Comment by 4501** [comment]
Hi @Politron ,I am also facing similar issue.Could you please help me?

**Comment by 4501** [comment]
Hi @Politron ,I am also facing similar issue.Could you please help me?

**Comment by 4501** [comment]
Hi @Politron ,I am also facing similar issue.Could you please help me?
