### ISSUE TITLE
Jersey 2.29 : duplicated bean validation api library

### ISSUE THREAD

**Issue by ghusta** [eclipse-ee4j/jersey#4295]
When importing Bean Validation for Jersey with `org.glassfish.jersey.ext:jersey-bean-validation` (as of 2.29), it seems that there are duplicated libraries : 

* `javax.validation:validation-api`
* `jakarta.validation:jakarta.validation-api`

IMO the first one should be excluded.

As an example, look at how _Spring Boot 2.2_ managed this problem in `spring-boot-starter-validation`  : 
[Source pom.xml](https://github.com/spring-projects/spring-boot/blob/v2.2.0.RELEASE/spring-boot-project/spring-boot-starters/spring-boot-starter-validation/pom.xml)

**Comment by jansupol** [comment]
Agree, the javax comes from org.hibernate.validator:hibernate-validator:jar:6.0.17.Final and should be excluded in POM.
