### ISSUE TITLE
Jersey 2.28 + Bean Validation 2.0 + JDK 11 won't build

### ISSUE THREAD

**Issue by ghusta** [eclipse-ee4j/jersey#4299]
Because of an issue in Hibernate Validator 6.0.11, it can't compile with JDK 11, 
when using `org.glassfish.jersey.ext:jersey-bean-validation` (v2.28).

See [HV-1644](https://hibernate.atlassian.net/browse/HV-1644)

The log at compile time :

    [WARNING] The POM for org.openjfx:javafx.base:jar:11.0.0-SNAPSHOT is missing, no dependency information available
    The POM for org.openjfx:javafx.base:jar:11.0.0-SNAPSHOT is missing, no dependency information available

It can be fixed by upgrading Hibernate Validator to 6.0.12. 

Related to PR #3908

**Comment by jansupol** [comment]
Latest Jersey uses Validator 6.0.17.Final

**Comment by ghusta** [comment]
Yes, upgrading to Jersey 2.29.1 may be a solution too
