### ISSUE TITLE
Add @PropertiesClass annonatated classes to config properties

### ISSUE THREAD

**Issue by jansupol** [eclipse-ee4j/jersey#4323]

**Comment by jansupol** [comment]
Currently, only ClientProperties, ServerProperties, and CommonProperties properties are used for properties defined by system properties grabbed when SecurityManager is on.
It would make sense to try other @PropertiesClass annotated property classes.

**Comment by jbescos** [comment]
If I understand it correctly:
The current class SystemPropertiesConfiguration.getExpectedSystemProperties() is only loading the fields from CommonProperties, CommonProperties and ClientProperties.

And we want to add any existing or future class having the annotation @PropertiesClass or 
@Property

I will develop it in this way:
Adding a new method in ReflectionHelper: List<Class<?>> findClassesInPackageWhere(Package root, Predicate<Class<?>> ... predicates)

So it will return the classes under a package given the predicates (having the annotation @PropertiesClass or @Property)
