### ISSUE TITLE
Jersey 2.29 AbstractBinder.configure() called twice

### ISSUE THREAD

**Issue by mr-aixigo** [eclipse-ee4j/jersey#4344]
After upgrading von 2.28 to 2.29 I noticed that the `configure()` methods of all binders are called twice. This happens with `org.glassfish.hk2.utilities.binding.AbstractBinder` and can be solved by switching to `org.glassfish.jersey.internal.inject.AbstractBinder`.

Since this occured only in 2.29 I would like to know:
* Is this a bug which will be fixed?
* Should `org.glassfish.hk2.utilities.binding.AbstractBinder` be considered as deprecated? I could not find anything in the documentation that suggests I should stop using this class.

```
import org.glassfish.hk2.utilities.binding.AbstractBinder;       // bad
//import org.glassfish.jersey.internal.inject.AbstractBinder;    // good
import org.glassfish.jersey.server.ResourceConfig;

public class DemoConfig extends ResourceConfig
{
   public DemoConfig()
   {
      registerInstances( new DemoBinder() );
   }

   static class DemoBinder extends AbstractBinder
   {
      @Override
      protected void configure()
      {
         System.out.println( "configure()" );
      }
   }
}
```

**Comment by jansupol** [comment]
Thanks, this will be fixed.
Duplicates #4256

**Comment by jansupol** [comment]
As a workaround, you can use:
```
   public DemoConfig()
   {
      register(DemoBinder.class);
   }
```
