### ISSUE TITLE
Bump Jetty version to 9.4.24.v20191120

### ISSUE THREAD

**Issue by nddipiazza** [eclipse-ee4j/jersey#4354]
We need to bump Jetty version to 9.4.24.v20191120 because a back-breaking change was introduced. 

See https://github.com/eclipse-ee4j/jersey/issues/4302

Once we bump the version, we need to change:

https://github.com/nddipiazza/jersey/blob/12a057315292a624ceb31b58bd04eec3cb19a819/containers/jetty-http/src/main/java/org/glassfish/jersey/jetty/JettyHttpContainerFactory.java#L296

from `protected` to `public`

**Comment by nddipiazza** [comment]
I just noticed this appears already fixed on master. please cut a new version. 2.29.2 with this fix.

**Comment by jansupol** [comment]
Jersey 2.30.1 contains this change. It is already out. For the next version, we upgraded to Jetty 9.4.27.v20200227 (#4425)
