### ISSUE TITLE
Please update roadmap :-)

### ISSUE THREAD

**Issue by mkarg** [eclipse-ee4j/jersey#4384]
I kindly like to ask for an update of the roadmap in the wiki. It still says 2.30 is next, but actually it is already released. Also it would be nice to find approximate deadlines for the next releases. Thanks. :-)

**Comment by jansupol** [comment]
Jersey is going through Release Review this week so we will see after that.
The first is going to be 2.30.1, though, ASAP

**Comment by jansupol** [comment]
Although this seems to be more a permanent bug, I think we may close this. I have updated the road map, and this is fixed - until the next release

**Comment by mkarg** [comment]
Thank you, Jan! :-)
