### ISSUE TITLE
Release notes for 2.30.1 are not published (link yields 404)

### ISSUE THREAD

**Issue by larrywest** [eclipse-ee4j/jersey#4401]
At https://eclipse-ee4j.github.io/jersey.github.io/, the bottom of the text under "About" says:

> The latest stable release of Jersey is [2.30.1](https://eclipse-ee4j.github.io/jersey.github.io/download.html).

That link is to a download page, "https://eclipse-ee4j.github.io/jersey.github.io/download.html".

At that page, the top section, "JAX-RS 2.1 / Jersey 2.26+", begins with this paragraph:

> Jersey 2.30.1, that implements [JAX-RS 2.1 API](https://jcp.org/en/jsr/detail?id=370) API _(sic)_ is the most recent release of Jersey. To see the details about all changes, bug fixed and updates, please check the [Jersey 2.30.1 Release Notes](https://jersey.github.io/release-notes/2.30.1.html).

**That final link is the one that doesn't exist** (redirects somewhere with no release notes):
* "https://jersey.github.io/release-notes/2.30.1.html"

The previous release notes are here:
* "https://eclipse-ee4j.github.io/jersey.github.io/release-notes/2.30.html"
but the 2.30.1 release notes are not here, either:
* "https://eclipse-ee4j.github.io/jersey.github.io/release-notes/2.30.1.html"

**Comment by senivam** [comment]
Fixed
