### ISSUE TITLE
Wildcard @Produces is preferred over exact @Produces with lower qs

### ISSUE THREAD

**Issue by sumitjainn** [eclipse-ee4j/jersey#4433]
Wildcard @Produces with higher qs is preferred over exact match @Produces with lower qs

```@Path(value = "resource")
public class Resource {
	@GET
        @Produces(value = "*/*; qs=0.9")
	public Response getPlain() {
		return Response.ok("text/plain")
				.header("HEAD", "text-plain").build();
	}

	@GET
	@Produces(value = "text/html; qs=0.5")
	public Response getHtml() {
		return Response.ok("<html></html>).header("HEAD", "text-html")
				.build();
	}
}`

Request: Accept: text/html

Response: Content-Type: text/plain

**Comment by jansupol** [comment]
For an HTTP request with the `Accept:text/*` header, the Spec Section 3.7.2, paragraph 3.b (right before paragraph c) says:
> Let A be the request accept header set of client media types and PM a resource method’s
`@Produces set of server media types`, we use the media type `max>={S(a, p) | (a,p) ϵ A x Pm}`.

So `max` for `getPlain` will be `text/*`, for `getHtml` will be `text/html`, and `getHtml` wins as `text/html` >= `text/*`. (By the ordering i. paragraph 3.b, page 23)

However, for an HTTP request with the `Accept:text/html`, the `max` for `getPlain` will be `text/html` and `getHtml` will be `text/html`. So `getPlain` wins over `getHtml` as qs=0.9>qs=0.5.

This seems to work as designed.
