### ISSUE TITLE
Maven metadata doesn't contain all versions of jersey

### ISSUE THREAD

**Issue by volyx** [eclipse-ee4j/jersey#4445]
I'm getting this error when I'm building my jersey application.

```
 Could not resolve dependencies for project companyjaxrs2retrofit:jar:1.0-SNAPSHOT: Failed to collect dependencies at org.glassfish.jersey.media:jersey-media-multipart:jar:[2.25.1,2.25.1]: No versions available for org.glassfish.jersey.media:jersey-media-multipart:jar:[2.25.1,2.25.1] within specified range 
```
There are no versions in https://repo1.maven.org/maven2/org/glassfish/jersey/media/jersey-media-multipart/maven-metadata.xml

<img width="483" alt="image" src="https://user-images.githubusercontent.com/3828802/79851153-99cb6700-83cd-11ea-9c01-94b1b05f4286.png">

For example Guava has all old versions in their metadata https://repo.maven.apache.org/maven2/com/google/guava/guava/maven-metadata.xml 

<img width="429" alt="image" src="https://user-images.githubusercontent.com/3828802/79851186-a3ed6580-83cd-11ea-9f74-d1a8057c964d.png">

This error occurred after 3.0.0-M1 release

**Comment by balta3** [comment]
perhaps the same problem as #4035

**Comment by volyx** [comment]
Fixed. But how to prevent this in future? https://repo1.maven.org/maven2/org/glassfish/jersey/media/jersey-media-multipart/maven-metadata.xml

<img width="644" alt="image" src="https://user-images.githubusercontent.com/3828802/79981698-cc4c9100-84ad-11ea-80fb-c57d9d500470.png">

**Comment by jansupol** [comment]
Interesting. Issue #4035 occurred when the projects had too much power to purge older versions from the nexus repository. Jersey 3.0.0-M1 has been a very first release of Jersey to the new jakarta.oss.sonatype.org repository and we experienced some oddities regarding credentials with the first release that could have caused this. Hopefully, it will not repeat. We try to monitor this during the next release.
