### ISSUE TITLE
ApacheConnector force the useSystemProperties flag to false

### ISSUE THREAD

**Issue by lounagen** [eclipse-ee4j/jersey#4458]
ApacheConnector force the useSystemProperties flag to false: https://github.com/eclipse-ee4j/jersey/blob/f9a8431854f87fa652576a4cc32ad7e26c145afe/connectors/apache-connector/src/main/java/org/glassfish/jersey/apache/connector/ApacheConnector.java#L365

All the code is already done, but the switch to activate it is missing.

The related PR to add such a config field to activate the existing feature: #4459

**Comment by senivam** [comment]
fixed by #4459
