### ISSUE TITLE
3.0.0-M2 release isn't available through maven repo

### ISSUE THREAD

**Issue by rubensayshi** [eclipse-ee4j/jersey#4470]
I was really looking forward to a published version with jetty bumped since some anoying bug (which was fixed a while ago in jetty) has been haunting us for weeks.

So I was super happy to see `3.0.0-M2` tagging last week, but it seems it didn't make it to the maven repo yet, not sure who / what publishes the releases but it would be very much appreciated if it would be published <3

**Comment by arjantijms** [comment]
M2 has been staged here:

https://jakarta.oss.sonatype.org/content/repositories/staging/org/glassfish/jersey/jersey-bom/3.0.0-M2

> not sure who / what publishes the releases

Maxim Nesen I think.

**Comment by senivam** [comment]
For now it is not possible to push 3.0.0-M2 version to central because it has some dependencies which are only in staging, so it will not work without that dependencies centralized as well.

**Comment by senivam** [comment]
@arjantijms do you know anything about plans of releasing HK2 M1 to central? Actually this is the only dependency which prevents Jersey M2 from being published to central.

**Comment by arjantijms** [comment]
Nope, no plans at the moment. I think the idea was to keep the implementations as much as possible in staging, since everything is still so volatile and changing all the time.

**Comment by rubensayshi** [comment]
would it be possible to bump jetty to a newer version and do 2.x release with that bump? the current version of jetty being used is almost a year old ...

**Comment by senivam** [comment]
Actual jetty version which is going to be released within the 2.31 version is 9.4.27.v20200227 which was released 28. Feb 2020. 

Version 2.31 is going to be released in the nearest future.

**Comment by jansupol** [comment]
@rubensayshi 3.0.0-Mx is a progress of the effort to adopt new APIs in `jakarta` package (transitioned from `javax` package). The milestone releases are highly experimental and certainly not production-ready. We would recommend continuing using 2.x branch at least until 3.0.0-RCx, unless you specifically want to test the new API. When 3.0.0. Final release is out, we still continue our work on 2.x branch in parallel with 3.x branch for a reasonable period to keep the `javax` based api support.

**Comment by senivam** [comment]
@rubensayshi Jersey of the version 2.31 is released. It contains dependency for jetty  version is 9.4.27.v20200227. Closing.

**Comment by rubensayshi** [comment]
awesome! <3
