### ISSUE TITLE
MessageBodyWriter not found for media type=application/xml in 3.0.0-M1

### ISSUE THREAD

**Issue by irq20xdfr** [eclipse-ee4j/jersey#4478]
Hi, i am using this dependency in maven

```
            <dependency>
                <groupId>org.glassfish.jersey</groupId>
                <artifactId>jersey-bom</artifactId>
                <version>${jersey.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

`	@GET
	@Path("/comidas")
	@Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
	public Comida listaComidas() {
		List<Comida> comidas = comidaService.getComidas();
		return comidas.get(0);
	}
`
it works well in 2.30, but in 3.0.0-M1 sends this

MessageBodyWriter not found for media type=application/xml

in both cases i see in my maven libreries
jersey-media-jaxb-3.0.0-M1.jar

and

jersey-media-jaxb-2.30.jar

But it only produces the XML when i use the 2.30 version? any suggestion that i might being missing?

Thanks

**Comment by jansupol** [comment]
Jakarta REST 3.0.0-M1 is already using the new [JAX-B API](https://github.com/eclipse-ee4j/jaxrs-api/blob/6dcc742d18d873d890a60ec38e8acd0ac70f4dfd/jaxrs-api/pom.xml#L628), and 3.0.0-M1 is using the new [JAX-B impl](https://github.com/eclipse-ee4j/jersey/blob/d00c463120fc01152d034ab0222808428e5cd4ce/pom.xml#L2117). Could it relate?

**Comment by irq20xdfr** [comment]
Thanks for your answer.

So, should i change something in my pom.xml or add another configuration to the web.xml file?

Because in version 2.30 the JAXB MessageBodyWriter is automatically discovered when i annotate my POJO with @XmlRootElement and add @Produces(MediaType.APPLICATION_XML) to the Jersey handler: @Path("/mypath")

I can even add a custom MessageBodyWriter in my project with 3.0.0-M1 and it works well

I used this code:

`@Produces("application/xml")
public class MyBeanMessageBodyWriter implements MessageBodyWriter<MyBean> {
 
    @Override
    public boolean isWriteable(Class<?> type, Type genericType,
                               Annotation[] annotations, MediaType mediaType) {
        return type == MyBean.class;
    }
 
    @Override
    public long getSize(MyBean myBean, Class<?> type, Type genericType,
                        Annotation[] annotations, MediaType mediaType) {
        // deprecated by JAX-RS 2.0 and ignored by Jersey runtime
        return -1;
    }
 
    @Override
    public void writeTo(MyBean myBean,
                        Class<?> type,
                        Type genericType,
                        Annotation[] annotations,
                        MediaType mediaType,
                        MultivaluedMap<String, Object> httpHeaders,
                        OutputStream entityStream)
                        throws IOException, WebApplicationException {
 
        try {
            JAXBContext jaxbContext = JAXBContext.newInstance(MyBean.class);
 
            // serialize the entity myBean to the entity output stream
            jaxbContext.createMarshaller().marshal(myBean, entityStream);
        } catch (JAXBException jaxbException) {
            throw new ProcessingException(
                "Error serializing a MyBean to the output stream", jaxbException);
        }
    }
}`

The problem is that in 3.0.0-M1  it seems like the JAXB-3.0.0-M1 MessageBodyWriter is not detected.

Any ideas?

Thank you so much.

**Comment by senivam** [comment]
this happends due to an error in JAXB-3.0.0-M1 which is fixed in JAXB-3.0.0-M2(3), but jakartified jersey whith those bumped dependencies is not published yet, so for now I'm not sure you can do anything about that.

**Comment by irq20xdfr** [comment]
Thanks @senivam 

I hope this helps other people with the same problem.

I'll keep using 2.30 for now.

Regards,

**Comment by jansupol** [comment]
Jersey 3.0.0-M6 is out, and should be working fine regarding this issue. As always, milestone releases are in general considered not production-ready.

Jersey 2.x will continue to be developed, maintained, and improved along with 3.x. Unless you plan to use new features the new Jakarta EE brings, you are safe with 2.x for the time being.
