### ISSUE TITLE
Preventing nulls when serializing a JSON response

### ISSUE THREAD

**Issue by shaggyfrog** [eclipse-ee4j/jersey#4479]
Given a request handler annotated with `@Produces(MediaType.APPLICATION_JSON)`, a JSON response can be easily created by something like `return Response.status(200).entity(data).build();`

However, if data contains null values, those are being serialized by default.

How can I prevent the null values from being serialized in the JSON response?

Using embedded Jersey 2.30.

**Comment by jansupol** [comment]
It depends on what is used for serializing the JSON. In 2.30 you can use Moxy, Jackson, Yasson, Jettison,...

**Comment by shaggyfrog** [comment]
By default, what is Jersey configured to use for JSON serialization? Because that would be the serializer I'm using, I guess.

I was hoping to be pointed to a working example of where the default serializer is configured.

**Comment by jansupol** [comment]
The "default" depends on what dependencies you have in your project. Given you seem to have only jersey-media-json-jackson, you need to configure Jackson, you can check [Jersey documentation](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/media.html#json.jackson) about how to configure Jackson's `ObjectMapper`.

**Comment by shaggyfrog** [comment]
Over the last decade there are a number of answers describing various ways to do this, with varying degrees of quality, for various versions of Jersey.

Just in case anyone searches for this in the future, the way I solved it was to create a new class, e.g.:

```java
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;

import javax.ws.rs.ext.ContextResolver;
import javax.ws.rs.ext.Provider;

@Provider
public class ObjectMapperResolver implements ContextResolver<ObjectMapper> {
    private final ObjectMapper mapper;

    public ObjectMapperResolver() {
        mapper = new ObjectMapper();
        // mapper.enable(SerializationFeature.INDENT_OUTPUT); // not strictly required
        mapper.setSerializationInclusion(Include.NON_NULL);
    }

    @Override
    public ObjectMapper getContext(Class<?> type) {
        return mapper;
    }
}
```

My embedded-Jersey-app didn't already have a `ResourceConfig` class (which is Jersey's subclass of `javax.ws.rs.core.Application` -- and not a great name IMO), so I created one:

```java
import org.glassfish.jersey.server.ResourceConfig;

public class MyResourceConfig extends ResourceConfig {
    public MyResourceConfig() {
        //... perhaps a call to packages("...") also goes here...
        register(ObjectMapperResolver.class);
    }
}
```

Then the `main` method in the top-level `App` class that embeds Jersey might look like:

```java
...
public class App {
  ...
  public static void main(String... args) throws Exception {
    ...
    ServletContextHandler applicationContext = new ServletContextHandler(ServletContextHandler.SESSIONS);
    applicationContext.setContextPath("/");
    applicationContext.setSessionHandler(new SessionHandler());

    // API/REST (Jersey)
    ServletHolder jerseyServletHolder = applicationContext.addServlet(ServletContainer.class, "*");
    jerseyServletHolder.setInitParameter(
        "javax.ws.rs.Application",
        "com.example.MyResourceConfig"
    );
    ...
```
