### ISSUE TITLE
E-mail address specified in readme automatically rejects all e-mails

### ISSUE THREAD

**Issue by shaggyfrog** [eclipse-ee4j/jersey#4480]
"If you run into any issues or have questions, ask at jersey-dev@eclipse.org"

When sending an e-mail to that address, it gets an immediate rejection response, with no explanation of how to resolve.

If the address is for a mailing list, then instructions for joining the mailing list should replace the suggestion to use the e-mail address directly.

**Comment by jansupol** [comment]
Yes, you need to be [subscribed ](https://accounts.eclipse.org/mailing-list/jersey-dev) to the mailing list.

**Comment by edbratt** [comment]
Abstractly, this isn't all that different from the fact one needs to have a GitHub account to file issues here. Were it not for rampant SPAM, these restrictions could be lessened. Regretfully (and having had my inbox bombarded in this way) I don't think we can consider relaxing this. Do you feel this requires further action, or may we close this issue?

**Comment by shaggyfrog** [comment]
I outlined the problem (as I see it) in the original message, but the two responses so far don't seem to acknowledge the problem description, or my proposed change.

I didn't say anything about lessening restrictions.

**Comment by jansupol** [comment]
I have updated the README (#4485)
