### ISSUE TITLE
Consuming JSON list of strings sent via POST

### ISSUE THREAD

**Issue by shaggyfrog** [eclipse-ee4j/jersey#4486]
Given a function that processes a request, annotated like the following

```java
@Path("/something")
@POST
@Consumes(MediaType.APPLICATION_JSON)
public Response SomeFunction(@Context HttpServletRequest request) {
```

And assuming that a valid request with `Content-type: application/json` is received by Jersey, with the body something like `["a", "b"]` -- in other words, a JSON list of strings -- what is the easiest way to have Jersey automagically parse the body into a parameter for the function?

I tried adding `List<String> foos` as a parameter, i.e.:

```java
public Response SomeFunction(List<String> foos, @Context HttpServletRequest request) {
```

But this fails with the message:
> Cannot deserialize instance of `java.util.ArrayList` out of VALUE_STRING token
> at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 1]

**Comment by shaggyfrog** [comment]
I grabbed a copy of the entire repository and then started modifying the json-jackson example (https://github.com/jersey/jersey/tree/master/examples/json-jackson) to try and figure out what is wrong with my embedded Jersey app.

I added a new test resource that looks something like this:

    @Path("myTest")
    public class MyTestResource {
    
        @Path("first")
        @POST
        @Consumes(MediaType.APPLICATION_JSON)
        public Response getFirst(List<String> strings) {
            String s;
            if ((strings != null) && (strings.size() > 0)) {
                s = strings.get(0);
            } else {
                s = "";
            }
            return Response.status(200).entity(s).build();
        }
    }

And then I added `MyTestResource.class` to the super call to `ResourceConfig` in the default constructor for `MyApplication`. Then I added a test:

    @Test
    public void testMine() {
        enable(TestProperties.LOG_TRAFFIC);

        String responseMsg = target().path("myTest/first").request(MediaType.APPLICATION_JSON)
                .post(Entity.entity("[]", MediaType.valueOf("application/json")), String.class);
        assertEquals("", responseMsg);

        responseMsg = target().path("myTest/first").request(MediaType.APPLICATION_JSON)
                .post(Entity.entity("[\"a\"]", MediaType.valueOf("application/json")), String.class);
        assertTrue(responseMsg.contains("a"));

        Response response = target().path("myTest/first").request(MediaType.APPLICATION_JSON)
                .post(Entity.entity("asdf", MediaType.valueOf("application/json")));
        assertEquals(Response.Status.BAD_REQUEST.getStatusCode(), response.getStatus());
    }

**And that all worked fine**; the test passed. So I can't reproduce easily.

That has me thinking that perhaps my app is not properly configured to use Jackson.

I am calling `register(JacksonFeature.class);` in my app, but it seems like having that call there or not doesn't matter. (Sidenote: that is also true for the json-jackson example; perhaps this step is no longer necessary, but is still included in the examples and documentation?)

I set a breakpoint in `JacksonAutoDiscoverable` and I can see it getting hit the first time my endpoint is getting called.

My pom has dependencies on the following jersey (2.30) artifacts:

      org.glassfish.jersey.containers
          jersey-container-servlet-core
      org.glassfish.jersey.core
          jersey-client
          jersey-server
      org.glassfish.jersey.inject
          jersey-hk2
      org.glassfish.jersey.media
          jersey-media-json-jackson
          jersey-media-multipart

I have alphabetized them here, but would dependency order in the pom matter? Am I missing one?

The error message "Cannot deserialize instance of `java.util.ArrayList` out of VALUE_STRING token" makes me think that the Jackson/Jersey is not being used to process the parameter to the method (is this called the Provider?) and is being processed with vanilla Jersey, which can't do the JSON deserialization by itself

**Comment by jansupol** [comment]
So you are using Jackson and a bit of googling tells me "Cannot deserialize instance of java.util.ArrayList out of VALUE_STRING token" is a Jackson's message "com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of VALUE_STRING token", which tells me you possibly doing something wrong with Jackson. The Exception seems to say the content JSON is a String, but you want to have an array of strings. Could that be your case?

**Comment by shaggyfrog** [comment]
Hi @jansupol, as you see from the test case I wrote above, I'm passing a valid JSON list to the endpoint, and it's correctly parsing that POSTed data, and returning back the correct response.

However, basically the exact same code that works inside the `json-jackson` example is not working inside my app, and I'm trying to figure out why.

**Comment by shaggyfrog** [comment]
I went back to the drawing board and realized that the error message was trying to tell me that the JSON body had leading quotation marks `"`, which I didn't grok, because I thought it was just part of how the LoggingFeature was logging body data.

This happened because my client is Python and I was calling `json_data = json.dumps(foos)` and then calling `request()` with `json=json_data` instead of `json=foos` directly (and skipping any use of `dumps()`. Stupid mistake!

Thanks for your help @jansupol
