### ISSUE TITLE
"Download" button on project home page leads to 404

### ISSUE THREAD

**Issue by shaggyfrog** [eclipse-ee4j/jersey#4487]
The "Download" button in the upper-right corner of the home page at https://eclipse-ee4j.github.io/jersey/ leads to a 404 on GitHub Pages.

**Comment by senivam** [comment]
the issue is related to the main template, there is a PR which shall fix that: 

https://github.com/EclipseFdn/jekyll-theme-eclipsefdn/pull/2

**Comment by jansupol** [comment]
The PR is merged, but the Download button still is not working. Interestingly, https://eclipse-ee4j.github.io/yasson works

**Comment by senivam** [comment]
fixed
