### ISSUE TITLE
Using SNI with HttpUrlConnector

### ISSUE THREAD

**Issue by thomasmey** [eclipse-ee4j/jersey#4515]
Hi,

I followed below linked documenation to add SNI parameter to HttpsUrlConnection.

It basically does:
1.) create an SSLSocketFactoryWrapper which adds SNI parameter to all newly created TLS sockets
2.) sets Java's HttpsUrlConnection.setDefaultSSLSocketFactory to above wrapper.

see also original blog post:
http://javabreaks.blogspot.com/2015/12/java-ssl-handshake-with-server-name.html

The problem is:
Jersey's HttpUrlConnector never uses the HttpsUrlConnection's defaultSSLSocketFactory, instead the secureConnection method always falls back to SSLContext's SSLSocketFactory:

https://github.com/eclipse-ee4j/jersey/blob/da3473b03c64ef745b3e0083bd5e31c54a35198d/core-client/src/main/java/org/glassfish/jersey/client/internal/HttpUrlConnector.java#L302

I would like to know your opinion on adding SNI support or enable SNI support in Jersey.

The explicit SNI support is helpful in an localhost setup but still make TLS happy by providing an explicit serverName, e.g.: Tomcat running on localhost 8080 and 8443, but certificate on 8443 is issued by companies PKI with another hostname.

So either fix/enhance HttpUrlConnector in secureConnection method, or even make SNI support explicit in Client API.

**Comment by tvallin** [comment]
Hi,

Please have a look at this test : https://github.com/eclipse-ee4j/jersey/blob/03d8a7216a5e9f4452158fd018c37a518b6eef35/tests/e2e-client/src/test/java/org/glassfish/jersey/tests/e2e/client/connector/ssl/SslHttpUrlConnectorTest.java#L55

I think if you use SSLSocketFactoryWrapper in this way, it might achieves what you are trying to do. 

Let me know if it helps.

**Comment by tvallin** [comment]
Hello @thomasmey,

Have you tried to create a custom SSLSocketFactory shown in my last comment ?

Please provide me your feedback.

Thanks

**Comment by thomasmey** [comment]
Hi,
Sorry not yet. And currently on vacation. Will try it next week on work.

**Comment by tvallin** [comment]
Hi @thomasmey ,

Are you still facing SNI issue with the solution provided earlier ?

**Comment by jansupol** [comment]
The SNI is supported by the HttpUrlConnector in a recent Jersey. The SNI currently is set based on the HOST HTTP header. (See the [doc](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/client.html#d0e5657)). The HttpUrlConnector has the HOST header restricted, though. `sun.net.http.allowRestrictedHeaders` property needs to be set to `true` to allow the HOST HTTP header.
