### ISSUE TITLE
org.glassfish.hk2:hk2-locator:jar:3.0.0-M2 not found in Maven Central

### ISSUE THREAD

**Issue by mkarg** [eclipse-ee4j/jersey#4521]
When converting a Hello World application from Jersey 3.0.0-M1 to 3.0.0-M6 then Maven fails due to a missing dependency.

It seems Jersey 3.0.0-M6 depends on hk2-locator 3.0.0-M2, but that version is actually not contained in Maven Central!

Please either publish it, or reduce the dependency to an earlier version.

```
[ERROR] Failed to execute goal on project helloworld: Could not resolve dependencies for project eu.headcrashing.jaxrsdoneright:helloworld:jar:Jakarta-EE-9-M1: Failure to find org.glassfish.hk2:hk2-locator:jar:3.0.0-M2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

**Comment by arjantijms** [comment]
The dependency is in staging, and can be found here: https://jakarta.oss.sonatype.org/content/repositories/staging/org/glassfish/hk2/hk2-locator/3.0.0-M2/

You can compile with `-Pstaging` or alternatively add the staging repos to a global settings.xml:

```xml
           <repositories>
                <repository>
                    <id>sonatype-nexus-staging</id>
                    <name>Sonatype Nexus Staging</name>
                    <url>https://jakarta.oss.sonatype.org/content/repositories/staging/ </url>
                    <releases>
                        <enabled>true</enabled>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                </repository>
            </repositories>
            <pluginRepositories>
                <pluginRepository>
                    <id>sonatype-nexus-staging</id>
                    <name>Sonatype Nexus Staging</name>
                    <url>https://jakarta.oss.sonatype.org/content/repositories/staging/ </url>
                    <releases>
                        <enabled>true</enabled>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                </pluginRepository>
            </pluginRepositories>
```

**Comment by jansupol** [comment]
Unfortunately, HK2 is not in central. Feel free to file a bug on HK2 for them to move it from staging to central.

**Comment by mkarg** [comment]
It is a bad idea to publish things into Central which depend on things not found in Central. :-(

Actually there already is an issue at HK2 for that (https://github.com/eclipse-ee4j/glassfish-hk2/issues/513).

**Comment by arjantijms** [comment]
Note that in 513, Steve says "GlassFish needs a M2 release in staging". It's not about publishing to central. As a rule of thumb milestone releases of the implementation components have mostly been published to staging only.

**Comment by mkarg** [comment]
If we want people to play with M1 (and I assume this is why we did the video show yesterday) we should allow them to pull *all* needed parts from Central. Nobody has any benefit from a Jersey in Central that in turn demands parts taken from other repos -- in that case, one could simply pull Jersey from staging itself.

**Comment by jansupol** [comment]
I agree, we did not want to release M6 to central until HK2 is there, but we must show progress towards Jakarta EE 9, as we reach the deadline for it, and Steve promised me to put HK2 M2 to central. So here we are. 
Similarly, GF 6 M1 contains Jersey M4, which is not in central, since it depends on HK2 M1.

**Comment by jansupol** [comment]
Closing as HK2 M2 is in the maven central.

**Comment by mkarg** [comment]
Steve pushed HK2 to Maven Central, so Jersey 3.0.0-M6 works like a charm now (at least the modules I actively tested today).

Thanks a lot to all of you! :-)

**Comment by jansupol** [comment]
@mkarg Thanks Markus, good pushing on this.
