### ISSUE TITLE
“NoSuchMethodErrors” due to multiple versions of org.apache.maven:maven-artifact:jar

### ISSUE THREAD

**Issue by Bing-ok** [eclipse-ee4j/jersey#4533]
## Issue description
Hi, there are multiple versions of **_org.apache.maven:maven-artifact_** in **_jersey-2.31\tools\jersey-doc-modulelist-maven-plugin_**. As shown in the following dependency tree, according to Maven's “nearest wins” strategy, only **_org.apache.maven:maven-artifact:3.1.1_** can be loaded, **_org.apache.maven:maven-artifact:2.2.0_** will be shadowed.

However, one method defined in shadowed version **_org.apache.maven:maven-artifact:2.2.0_** is referenced by client project via **_org.apache.maven.shared:maven-dependency-tree:2.0_**, but missing in the actually loaded version **_org.apache.maven:maven-artifact:3.1.1_**.

For instance, the following missing method(defined in **_org.apache.maven:maven-artifact:2.2.0_**) is actually referenced by **_jersey-2.31\tools\jersey-doc-modulelist-maven-plugin_**, which will introduce a runtime error(i.e., "NoSuchMethodErrors") into **_jersey-2.31\tools\jersey-doc-modulelist-maven-plugin_**.

**_Missing method: org.apache.maven.artifact.versioning.ManagedVersionMap: void init (java.util.Map)_** is invoked by **_jersey-2.31\tools\jersey-doc-modulelist-maven-plugin_** via the following path:
<pre><code>
paths------
&lt;org.glassfish.jersey.tools.plugins.PredefinedCategories: org.glassfish.jersey.tools.plugins.PredefinedCategories[] values()&gt; jersey-2.31\tools\jersey-doc-modulelist-maven-plugin\target\classes
&lt;org.apache.maven.project.MavenProject: java.lang.Object clone()&gt; Repositories\org\apache\maven\maven-project\2.2.0\maven-project-2.2.0.jar
&lt;org.apache.maven.project.MavenProject: void deepCopy(org.apache.maven.project.MavenProject)&gt; Repositories\org\apache\maven\maven-project\2.2.0\maven-project-2.2.0.jar
&lt;org.apache.maven.artifact.versioning.ManagedVersionMap: void <init>(java.util.Map)&gt;
</code></pre>

## Suggested fixing solutions
1. Upgrade dependency **_org.apache.maven.shared:maven-dependency-tree_** from **_2.0_** to **_2.2_**. Because the newer version **_org.apache.maven.shared:maven-dependency-tree:2.2_** does not invoke the above missing method, such upgrading can solve the problem.
2. Change dependency **_org.apache.maven:maven-artifact_** from **_3.1.1_** to **_2.2.0_**, so that the missing methods will be loaded.

Thank you very much for your attention.
Best regards,

## Dependency tree----
<pre><code>
[INFO] org.glassfish.jersey.tools.plugins:jersey-doc-modulelist-maven-plugin:maven-plugin:1.0.1
[INFO] +- org.apache.maven:maven-plugin-api:jar:3.1.1:compile
[INFO] |  +- org.apache.maven:maven-model:jar:3.1.1:compile
[INFO] |  |  \- (org.codehaus.plexus:plexus-utils:jar:3.0.15:compile - omitted for duplicate)
[INFO] |  +- <b>(org.apache.maven:maven-artifact:jar:3.1.1:compile - omitted for duplicate)</b>
[INFO] |  \- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.0.0.M5:compile
[INFO] |     +- javax.enterprise:cdi-api:jar:1.0:compile
[INFO] |     |  +- javax.annotation:jsr250-api:jar:1.0:compile
[INFO] |     |  \- javax.inject:javax.inject:jar:1:compile
[INFO] |     +- com.google.guava:guava:jar:10.0.1:compile
[INFO] |     |  \- com.google.code.findbugs:jsr305:jar:1.3.9:compile
[INFO] |     +- org.sonatype.sisu:sisu-guice:jar:no_aop:3.1.0:compile
[INFO] |     |  +- (javax.inject:javax.inject:jar:1:compile - omitted for duplicate)
[INFO] |     |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |     +- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.0.0.M5:compile
[INFO] |     +- (org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile - omitted for duplicate)
[INFO] |     +- (org.codehaus.plexus:plexus-classworlds:jar:2.4:compile - omitted for conflict with 2.5.1)
[INFO] |     \- (org.codehaus.plexus:plexus-utils:jar:2.1:compile - omitted for conflict with 3.0.15)
[INFO] +- org.apache.maven:maven-core:jar:3.1.1:compile
[INFO] |  +- (org.apache.maven:maven-model:jar:3.1.1:compile - omitted for duplicate)
[INFO] |  +- org.apache.maven:maven-settings:jar:3.1.1:compile
[INFO] |  |  \- (org.codehaus.plexus:plexus-utils:jar:3.0.15:compile - omitted for duplicate)
[INFO] |  +- org.apache.maven:maven-settings-builder:jar:3.1.1:compile
[INFO] |  |  +- (org.codehaus.plexus:plexus-utils:jar:3.0.15:compile - omitted for duplicate)
[INFO] |  |  +- (org.codehaus.plexus:plexus-interpolation:jar:1.19:compile - omitted for duplicate)
[INFO] |  |  +- (org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile - omitted for duplicate)
[INFO] |  |  +- (org.apache.maven:maven-settings:jar:3.1.1:compile - omitted for duplicate)
[INFO] |  |  \- (org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile - omitted for duplicate)
[INFO] |  +- org.apache.maven:maven-repository-metadata:jar:3.1.1:compile
[INFO] |  |  \- (org.codehaus.plexus:plexus-utils:jar:3.0.15:compile - omitted for duplicate)
[INFO] |  +- <b>(org.apache.maven:maven-artifact:jar:3.1.1:compile - omitted for duplicate)</b>
[INFO] |  +- (org.apache.maven:maven-plugin-api:jar:3.1.1:compile - omitted for duplicate)
[INFO] |  +- org.apache.maven:maven-model-builder:jar:3.1.1:compile
[INFO] |  |  +- (org.codehaus.plexus:plexus-utils:jar:3.0.15:compile - omitted for duplicate)
[INFO] |  |  +- (org.codehaus.plexus:plexus-interpolation:jar:1.19:compile - omitted for duplicate)
[INFO] |  |  +- (org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile - omitted for duplicate)
[INFO] |  |  \- (org.apache.maven:maven-model:jar:3.1.1:compile - omitted for duplicate)
[INFO] |  +- org.apache.maven:maven-aether-provider:jar:3.1.1:compile
[INFO] |  |  +- (org.apache.maven:maven-model:jar:3.1.1:compile - omitted for duplicate)
[INFO] |  |  +- (org.apache.maven:maven-model-builder:jar:3.1.1:compile - omitted for duplicate)
[INFO] |  |  +- (org.apache.maven:maven-repository-metadata:jar:3.1.1:compile - omitted for duplicate)
[INFO] |  |  +- (org.eclipse.aether:aether-api:jar:0.9.0.M2:compile - omitted for duplicate)
[INFO] |  |  +- org.eclipse.aether:aether-spi:jar:0.9.0.M2:compile
[INFO] |  |  |  \- (org.eclipse.aether:aether-api:jar:0.9.0.M2:compile - omitted for duplicate)
[INFO] |  |  +- (org.eclipse.aether:aether-util:jar:0.9.0.M2:compile - omitted for duplicate)
[INFO] |  |  +- (org.eclipse.aether:aether-impl:jar:0.9.0.M2:compile - omitted for duplicate)
[INFO] |  |  +- (org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile - omitted for duplicate)
[INFO] |  |  \- (org.codehaus.plexus:plexus-utils:jar:3.0.15:compile - omitted for duplicate)
[INFO] |  +- org.eclipse.aether:aether-impl:jar:0.9.0.M2:compile
[INFO] |  |  +- (org.eclipse.aether:aether-api:jar:0.9.0.M2:compile - omitted for duplicate)
[INFO] |  |  +- (org.eclipse.aether:aether-spi:jar:0.9.0.M2:compile - omitted for duplicate)
[INFO] |  |  \- (org.eclipse.aether:aether-util:jar:0.9.0.M2:compile - omitted for duplicate)
[INFO] |  +- org.eclipse.aether:aether-api:jar:0.9.0.M2:compile
[INFO] |  +- org.eclipse.aether:aether-util:jar:0.9.0.M2:compile
[INFO] |  |  \- (org.eclipse.aether:aether-api:jar:0.9.0.M2:compile - omitted for duplicate)
[INFO] |  +- (org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.0.0.M5:compile - omitted for duplicate)
[INFO] |  +- org.codehaus.plexus:plexus-interpolation:jar:1.19:compile
[INFO] |  +- org.codehaus.plexus:plexus-utils:jar:3.0.15:compile
[INFO] |  +- org.codehaus.plexus:plexus-classworlds:jar:2.5.1:compile
[INFO] |  +- org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile
[INFO] |  \- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
[INFO] |     +- (org.codehaus.plexus:plexus-utils:jar:1.5.5:compile - omitted for conflict with 3.0.15)
[INFO] |     \- org.sonatype.plexus:plexus-cipher:jar:1.4:compile
[INFO] +- <b>org.apache.maven:maven-artifact:jar:3.1.1:compile</b>
[INFO] |  \- (org.codehaus.plexus:plexus-utils:jar:3.0.15:compile - omitted for duplicate)
[INFO] \- org.apache.maven.shared:maven-dependency-tree:jar:2.0:compile
[INFO]    +- org.apache.maven:maven-project:jar:2.2.0:compile
[INFO]    |  +- (org.apache.maven:maven-settings:jar:2.2.0:compile - omitted for conflict with 3.1.1)
[INFO]    |  +- org.apache.maven:maven-profile:jar:2.2.0:compile
[INFO]    |  |  +- (org.apache.maven:maven-model:jar:2.2.0:compile - omitted for conflict with 3.1.1)
[INFO]    |  |  +- (org.codehaus.plexus:plexus-utils:jar:1.5.15:compile - omitted for conflict with 3.0.15)
[INFO]    |  |  +- (org.codehaus.plexus:plexus-interpolation:jar:1.11:compile - omitted for conflict with 1.19)
[INFO]    |  |  \- (org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile - omitted for duplicate)
[INFO]    |  +- (org.apache.maven:maven-model:jar:2.2.0:compile - omitted for conflict with 3.1.1)
[INFO]    |  +- org.apache.maven:maven-artifact-manager:jar:2.2.0:compile
[INFO]    |  |  +- (org.apache.maven:maven-repository-metadata:jar:2.2.0:compile - omitted for conflict with 3.1.1)
[INFO]    |  |  +- (org.codehaus.plexus:plexus-utils:jar:1.5.15:compile - omitted for conflict with 3.0.15)
[INFO]    |  |  +- <b>(org.apache.maven:maven-artifact:jar:2.2.0:compile - omitted for conflict with 3.1.1)</b>
[INFO]    |  |  +- (org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile - omitted for duplicate)
[INFO]    |  |  +- org.apache.maven.wagon:wagon-provider-api:jar:1.0-beta-6:compile
[INFO]    |  |  |  \- (org.codehaus.plexus:plexus-utils:jar:1.4.2:compile - omitted for conflict with 3.0.15)
[INFO]    |  |  \- backport-util-concurrent:backport-util-concurrent:jar:3.1:compile
[INFO]    |  +- org.apache.maven:maven-plugin-registry:jar:2.2.0:compile
[INFO]    |  |  +- (org.codehaus.plexus:plexus-utils:jar:1.5.15:compile - omitted for conflict with 3.0.15)
[INFO]    |  |  \- (org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile - omitted for duplicate)
[INFO]    |  +- (org.codehaus.plexus:plexus-interpolation:jar:1.11:compile - omitted for conflict with 1.19)
[INFO]    |  +- (org.codehaus.plexus:plexus-utils:jar:1.5.15:compile - omitted for conflict with 3.0.15)
[INFO]    |  +- <b>(org.apache.maven:maven-artifact:jar:2.2.0:compile - omitted for conflict with 3.1.1)</b>
[INFO]    |  \- org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile
[INFO]    |     +- junit:junit:jar:3.8.1:compile
[INFO]    |     +- (org.codehaus.plexus:plexus-utils:jar:1.0.4:compile - omitted for conflict with 3.0.15)
[INFO]    |     \- classworlds:classworlds:jar:1.1-alpha-2:compile
[INFO]    \- (org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile - omitted for duplicate)
</code></pre>

**Comment by Bing-ok** [comment]
Could you help me review this issue? 👍 Thanks! @senivam

**Comment by Bing-ok** [comment]
Could you help me review this issue? 👍 Thanks! @jansupol

**Comment by Bing-ok** [comment]
@senivam Could you please help me review this issue? Thank you very much.

**Comment by senivam** [comment]
Hi @Bing-ok, preferred solution is to upgrade dependency version. 

However it's possible to upgrade just to the newest versions of all dependencies - 3.6.3 and 3.0.2 respectively. The  jersey-doc-modulelist-maven-plugin will work as expected and it's version will be 1.0.2. 

However I'm not sure how do you use it, be case at least my experiments with dependencies and mvn dependency:tree show somehow different output and plugin works in any version without described error.

**Comment by Bing-ok** [comment]
You can use command <code>mvn dependency:tree -Dverbose</code> to print the full dependency tree as shown above.

**Comment by senivam** [comment]
yeah, but the main point was that I can not reproduce described error. 

and if you do not have objections against raising versions to the latest (not just to 2.2 of the maven-dependency-tree)

**Comment by senivam** [comment]
PR #4567 was merged, so issue can be closed as fixed.
