### ISSUE TITLE
Missing Expect header and 100-continue handling in Jersey Client

### ISSUE THREAD

**Issue by skunjuma** [eclipse-ee4j/jersey#4536]
We use Jersey client in our SDK for a object storage service. Our clients upload large content through PUT calls. Recently we are experiencing problems with too many concurrent uploads overwhelming our load balancers and web servers. We have traffic throttling and request control features at the server side. But clients can still overload our systems by continuously retrying requests. This is in part due to missing handling for expect header and 100-continue responses by the Jersey client used in JAX-RS client framework. Please add support for handling expect header and 100-continue responses.

**Comment by senivam** [comment]
starting by requesting corresponding header support from JAX-RS API (see [issue 900](https://github.com/eclipse-ee4j/jaxrs-api/issues/900))
