### ISSUE TITLE
[Documentation] - Every links to the API docs broken

### ISSUE THREAD

**Issue by dadon-david** [eclipse-ee4j/jersey#4560]
Hello,

Every links to the API docs in the documentation are broken.

Example: 

[In this part of the documentation](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/jaxrs-resources.html#highlighter_835541:~:text=The%20%40PathParam%20and%20the%20other%20parameter%2Dbased%20annotations) there a link to the API docs of `@PathParam` and the link is broken:

The link is https://jax-rs.github.io/apidocs/2.1.6//PathParam.html
And I think it should be https://jax-rs.github.io/apidocs/2.1/javax/ws/rs/PathParam.html

You can see many of these links here:
- https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/jaxrs-resources.html
- https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/deployment.html

Would it be possible to fix this? 

Thank you very much!

**Comment by senivam** [comment]
HTML (page) is already fixed, PR is submitted to prevent wrong links generation in future.

**Comment by dadon-david** [comment]
Thanks a lot!

**Comment by senivam** [comment]
merged, can be closed as fixed
