### ISSUE TITLE
how to suppress "GET method should not consume any entity"

### ISSUE THREAD

**Issue by jacalata** [eclipse-ee4j/jersey#4563]
I have inherited a program, and I need to make the logs quieter so I can actually read them. They are absolutely filled with this message: "     WARNING: A HTTP GET method, public com.google.protobuf.Message com.tableau.gateway.rest.resources.DynamicJerseyResource.execute(com.google.protobuf.Message,javax.ws.rs.container.ContainerRequestContext), should not consume any entity."

I've figured out that comes from this line of jersey:
https://github.com/eclipse-ee4j/jersey/blob/eafb9bdcb82dfa3fd76dd957d307b99d4a22c87f/core-server/src/main/java/org/glassfish/jersey/server/model/ResourceMethodValidator.java#L102

I've added this line to my log4j config:
        <Logger name="org.glassfish.jersey" level="TRACE" />
but this message is still showing up. 
How do I actually hide it? (Ideally with a smaller stick, but anything that works will be useful)

**Comment by jacalata** [comment]
ugh line was stripped
name="org.glassfish.jersey.server.model" level="TRACE"

**Comment by tvallin** [comment]
Hi,

The logger name which is printing this warning is "org.glassfish.jersey.internal.Errors". I set its Level to SEVERE and it hides the warning.

**Comment by jansupol** [comment]
Note that the warning informs about a conflict with HTTP 1.1 RFC [2616](https://tools.ietf.org/html/rfc2616), that does not support HTTP GET with an entity.

**Comment by jansupol** [comment]
Closing this. If you feel you want to continue the discussion, feel free to reopen.
