### ISSUE TITLE
JerseyClient builder does not support full range of configuration

### ISSUE THREAD

**Issue by jcalcote** [eclipse-ee4j/jersey#4568]
I left a comment in the jersey-dev email list a few days ago but never heard back so I'm going to assume no one has a problem with my suggestion that we fix the client builder. 

The problem is that in some methods the builder cancels out the attributes set by other methods of the builder. For instance, you cannot setup a custom trust store in your own SSLContext and also use the internal SslConfigurator to set a key store. Using the internal SSLConfigurator and a custom SSLContext are exclusive. There's no reason for this except that it was simpler to manage it that way.

**Comment by jansupol** [comment]
Unfortunately, neither the jersey-dev email nor this issue description contains an example idea of how you would think it would be good to combine the SslConfigurator and SSLContext. SslConfigurator is basically an SSLContext builder, both classes contain the information about key store and trust store, as you said. How would JerseyClient decide which trust store and which key store it would use?

**Comment by jansupol** [comment]
Also, the ClientBuilder#sslContext says:

**Comment by jcalcote** [comment]
Hi Jan. You are correct - your hands are tied by the API definition, which I didn't notice. After looking at the documentation and carefully examining the implementation again, I realized the issue only affects the builder keystore and truststore methods. Custom key and trust managers can both be set on a custom SSLContext, and that context then set on the client builder, so my issue just evaporated. :) Please close this issue. Sorry for the bother.
