### ISSUE TITLE
Jesery client sends a request twice when using Expect header and server returns with non-100 response

### ISSUE THREAD

**Issue by skunjuma** [eclipse-ee4j/jersey#4587]
I was trying to use the Expect header while uploading data. I noticed that Jersey client sends the same request twice when server returns back with a non-100 response. Debugging further into this revealed that HTTPURLConnection throws ProtocolException with "Server rejected operation" message and does not read the full response body or store the headers. HttpUrlConnector._apply method tries to set the headers to ClientResponse using HTTPURLConnection.getHeaderFields. getHeaderFields method first tries to getInputStream which in turn call getOutputStream. This results in sending the request again since both streams are null due the the ProtocolException.

I have a PR: https://github.com/eclipse-ee4j/jersey/pull/4588 which will solve this issue.

**Comment by senivam** [comment]
the issue shall be fixed by #4613 and is already available in the 2.33 version of Jersey. Please consider update to the version 2.33.
