### ISSUE TITLE
Registered binders not iterated in registration order

### ISSUE THREAD

**Issue by eocantu** [eclipse-ee4j/jersey#4638]
In our migration from jersey `2.25.1` to `2.32` we have noticed that the way in which registered binders are iterated is no longer deterministic. This is particularly problematic when different configuration order could lead to the wrong thing getting injected.

A similar issue was raised in #4538 but it doesn't seem like the fix addresses the issue for binders.

It seems to me the problem lies in the following code:
https://github.com/eclipse-ee4j/jersey/blob/aebe70dd367fca8d51b8a837d53879e5290d4be1/core-common/src/main/java/org/glassfish/jersey/model/internal/ComponentBag.java#L603-L611

`instances` was originally created as a `LinkedHashSet` which is an ordered set, but the method above uses `Collectors.toSet()` which doesn't preserve order.

**Comment by jansupol** [comment]
Fixed by https://github.com/eclipse-ee4j/jersey/pull/4648
