### ISSUE TITLE
SseEventSource cannot see the JAXRS_DEFAULT_SSE_BUILDER in OSGI

### ISSUE THREAD

**Issue by maho7791** [eclipse-ee4j/jersey#4649]
Because the package org.glassfish.jersey.media.sse.internal is not exported in the jersey-media-sse bundle,e.g. the JaxRs client is not able to load the default SSE builder.

This is a constellation that will never work.
A possible solution could be to introduce a factory in the SSE that can be instanciated reflectivley and then create the builder instance in the javax.ws.rs.ext.sse.FactoryFinder#find call

There is an initial issues at the JaxRs-api repository that is related to this, because I believe SSE and API are involved in that problem: 
https://github.com/eclipse-ee4j/jaxrs-api/issues/925

**Comment by jansupol** [comment]
Basically, we have two possible options:
