### ISSUE TITLE
Subclass of ResourceConfig is not loaded after migrating Jersey v2.32 to v3.0.0

### ISSUE THREAD

**Issue by innocentliny** [eclipse-ee4j/jersey#4652]
Hi, please read below details, thank you.

- Environment
  - jdk1.8.0_261
  - tomcat v8.5.59 and v8.5.60
  - Jersey v2.32 and v3.0.0
- What I did to migrate to Jersey v3.0.0
  - [gradle] change Jersey v2.32 to v3.0.0
  - replace ```javax.ws.rs``` package to ```jakarta.ws.rs``` package
  - replace ```javax.inject``` package to ```jakarta.inject``` package
- Problem description
  My web application is working well with Jersey v2.32. After changed to Jersey v3.0.0, same URLs return ```HTTP 404 Not Found```.
  I noticed that my subclass of ResourceConfig was not loaded.
- Reproduce problem
  The [jersey-2-test.zip](https://github.com/eclipse-ee4j/jersey/files/5657294/jersey-2-test.zip) is the working demo with Jersey v2.32. Go to http://localhost:8080/test will return "ok" response.
  The [jersey-3-test.zip](https://github.com/eclipse-ee4j/jersey/files/5657293/jersey-3-test.zip) is the problem demo with Jersey v3.0.0. Go to http://localhost:8080/test will get HTTP 404 response.

I don't know why my subclass of ResourceConfig is not loaded.
I also read [migration guide](https://eclipse-ee4j.github.io/jersey.github.io/documentation/3.0.0/user-guide.html#mig-2.26), but nothing I can do.
Please let me know if I missed someting or any suggections.

Thank you very much.

**Comment by jansupol** [comment]
Sorry, you cannot use Tomcat 8.x for Jersey 3.x. Jersey 3.x needs Tomcat 10.

**Comment by innocentliny** [comment]
> 
> 
> Sorry, you cannot use Tomcat 8.x for Jersey 3.x. Jersey 3.x needs Tomcat 10.

YES! You are right!
Thank you very much.
