### ISSUE TITLE
Please open a security advisory

### ISSUE THREAD

**Issue by JLLeitschuh** [eclipse-ee4j/jersey#4706]
Hello,

I'm an independent security researcher performing security research under the [GitHub Security Lab Bug Bounty Program](https://securitylab.github.com/). I believe I may have found a security vulnerability in this project.

Please open a security advisory against this repository so we can privately discuss the details. This advisory can be opened by a user with admin permissions on this repository.

https://github.com/eclipse-ee4j/jersey/security/advisories

**Comment by jansupol** [comment]
The Eclipse Foundation is the holder of the admin privileges, now. I will try to ask them.

**Comment by JLLeitschuh** [comment]
I see the advisory is now open! Thank you! 😄
