### ISSUE TITLE
Jackson module auto-discovery sets Jaxb Annotation Introspector as primary

### ISSUE THREAD

**Issue by kincajou** [eclipse-ee4j/jersey#4723]
Hello.

Initially, when creating Jackson' ObjectMapper for Jersey needs, annotation introspectors order is defined - Jackson annotations first, JAXB annotations second (org.glassfish.jersey.jackson.internal.jackson.jaxrs.json.JacksonJaxbJsonProvider#DEFAULT_ANNOTATIONS).

https://github.com/eclipse-ee4j/jersey/commit/31bd8727e7f9c922f4c4f19c6a77b7c168aa9673 introduced module auto-discovery. If we have JAXB module in class path, when it is discovered and registered, it pushes JAXB annotation introspector back to primary (that's the default behavior of the module), thus breaking intended logic. 

It looks like a bug, but maybe I'm missing something? Some configuration options?

**Comment by dzharikhin** [comment]
It really hurts in DTOs with mixed annotations.
ex.
```java
public class Dto {
  @XmlElement(name = "jaxb")
  @JsonProperty("jackson")
  public String field;
```
response for Dto("abc") is `{"jackson": "abc"}` for v. 2.30.1, but for v. 2.32 it's `{"jaxb": "abc"}`
