### ISSUE TITLE
Can't register a subpath in jersey application

### ISSUE THREAD

**Issue by raul1991** [eclipse-ee4j/jersey#4727]
I already have a servlet endpoint registered in karaf/osgi and it appear in the `http:list` command.

```
ID  | Servlet                | Servlet-Name             | State       | Alias               | Url
----+------------------------+--------------------------+-------------+---------------------+------------------------
**140 | ServletContainerBridge | ServletModel-16          | Deployed    | /foo               | [/foo/*]**
```

The code for the above registration is written as an osgi bundle deployed in the karaf which registers the above endpoint.

```
    componentConfiguration = getServiceConfiguration(JAXRS_CONNECTOR_PID);
    componentConfiguration.getBundleLocation();
    Dictionary<String, Object> properties = componentConfiguration.getProperties();
    if (properties == null)
    {
        properties = new Hashtable<String, Object>();
    }

    properties.put("root", "/foo");
    componentConfiguration.update(properties);
```

Now I have developed another rest api but that does not seem to be registering but when
**I hot deploy into osgi after karaf and all bundles are up, the subpath gets registered**

Jersey versions in karaf
```
336 | Active  |  80 | 2.31.0             | jersey-container-servlet-core
337 | Active  |  80 | 2.31.0             | jersey-core-client
338 | Active  |  80 | 2.31.0             | jersey-core-server
339 | Active  |  80 | 2.31.0             | jersey-ext-entity-filtering
340 | Active  |  80 | 2.31.0             | jersey-media-json-jackson
341 | Active  |  80 | 2.31.0             | jersey-media-multipart
```

Karaf version : 4.2.7
java: 11

Please suggest how can I get this subpath registered

**Comment by jansupol** [comment]
I do not understand your app and "hot deploy", but I assume you need to make sure `ServletContainer#reload` is called.
To do so, you can implement `ContainerLifecycleListener`, make sure you keep it at hand, you will get the `Container` registered with `ContainerLifecycleListener#onStartup`, and after the "hot deploy" you'll take the listener's `Container` and you should be able to call `Container#reload`.

**Comment by jansupol** [comment]
Hm...the second readings sounds like you have the subpath working only after the "hot deploy" and you do not need the `Container#reload` then. So you say you have just one Resource method working until you "hot deploy"?

**Comment by raul1991** [comment]
**_Some clarifications_**

By hot deploy, I mean when I copy the jars in the running karaf container's deploy folder.


Also I have two resources

One that looks like

/foo/entity/v1/

and the other one

/foo/appconfigs


I have 2 java  classes in two different bundles which have @Path annotation in them. I believe that is how jersey is trying to register them ?

I tried implementing the BundlerActivator to understand if the second bundle is getting activated or not. It does but still endpoint never appears and I keep getting 404 from jetty.

**Comment by raul1991** [comment]
@jansupol Also, in production hot deploying won't ever be an option so can't go that road.

**Comment by raul1991** [comment]
@jansupol  it turns out that the root context is being registered from the first bundle at start level 80 and the second rest endpoint also has the same start level. So karaf will try to bring them both up in parallel which causes a race condition.

So I changed the start level to 90 so the second endpoint comes later than the root context bundle and it registers perfectly.

**Comment by jansupol** [comment]
I'm glad you have figured that out. Hence closing now.
