### ISSUE TITLE
Print request/response logs in a single line

### ISSUE THREAD

**Issue by sarun85** [eclipse-ee4j/jersey#4734]
As the LoggingFeature is splitting the request data into several lines, it is difficult to filter the logs based on the thread id. Is it possible to provide an option in the LoggingFeature to pass in a delimiter as an optional parameter that will replace the line terminator "\n". This will help our project to filter the logs of a particular request from the log file using a script.

Thanks.

**Comment by senivam** [comment]
Hi @sarun85, for now line separator is hard-codded into LoggingInterceptor, but I think it won't be a big trouble to make i parametrized in future releases.
