### ISSUE TITLE
running jersey-common in java 11 runtime

### ISSUE THREAD

**Issue by vassik** [eclipse-ee4j/jersey#4755]
Hi,

We are using jersey-common in some of our projects and want to switch to java 11.

I see that jar files which you distribute are compiled with java 8. The binaries which can download from https://mvnrepository.com/ are also compiled with java 8.

I am wondering what are the possible consequences of running this code in java 11 environment? I have noticed that **sun.misc.Contended** is not longe present in java 11 runtime. I guess it is not going to fail with NoClassFoundException at runtime since it is an annotation, but are we going possibly to experience _false sharing_ as it is described here https://www.baeldung.com/java-false-sharing-contended?

I have also noticed that you have java11 folder in you code base where you have fixed this issue, but i guess it requires to be compiled by java 11. Do you distribute binaries compiled by jdk 11? Where can i find them? Are there any plans to abandon java 8? What is a timeline here?

**Comment by jansupol** [comment]
Jersey works fine on JDK 8, 11, 12, 13, 14, and 15.

Jersey is compiled with JDK 8, but some jars (such as Jersey common) is a multirelease jars that contain JDK 11+ equivalents for classes that used to be in JDK 8. The JDK 11 classes are in META-INF/versions in the multirelease jars and JDK 11+ classloader perfectly understands the structure and loads the proper classes.

**Comment by vassik** [comment]
correct, I have just checked that, should have noticed that...Thank you for your promp reply.
