### ISSUE TITLE
Please update asm repackaged to support java 16/17 🙏

### ISSUE THREAD

**Issue by eivinhb** [eclipse-ee4j/jersey#4756]
Ref.: https://gitlab.ow2.org/asm/asm/-/commit/7f24d5bc035ea9ed5cfa0e18a1f899109825ca40

We want to follow the release-track of java and we are now blocked by the asm repackaged in jersey 2.32.

**Comment by senivam** [comment]
will this help: #4754 ?

**Comment by eivinhb** [comment]
I guess it does! Looking forward to this to be released.

**Comment by jansupol** [comment]
For the time being, Jersey 2.33 contains repackaged ASM 9.0. ASM 9.0 should support JDK 16. While it does not support all the JDK 17 features, we overcame the ASM byte code check not to fail with JDK 17, it only prints a warning, if that helps. We try to add ASM 9.1 to 2.34, should the CQ be approved.

**Comment by eivinhb** [comment]
Yes, I realised that there was a 2.33 after I posted the above question and that 2.33 supported 16.
