### ISSUE TITLE
SSLContext gets initialized too early

### ISSUE THREAD

**Issue by bomgar** [eclipse-ee4j/jersey#4757]
Hi,

I have an application that modifies the java Security stack during runtime. This includes the SSL setup. Before this happens I use Jersey to make some http (not https) calls. This causes the SSLContext to initialize

The issue is the static final field here: `org.glassfish.jersey.client.internal.HttpUrlConnector`
```java
    private static final SSLSocketFactory DEFAULT_SSL_SOCKET_FACTORY = HttpsURLConnection.getDefaultSSLSocketFactory();

```

This initializes the SSLContext even if the client is only used for http. 

So this is called:
```java
    public static synchronized SSLContext getDefault()
            throws NoSuchAlgorithmException {
        if (defaultContext == null) {
            defaultContext = SSLContext.getInstance("Default");
        }
        return defaultContext;
    }

```
The default context does not get created again after that even if i modify the Security settings. 

This should only happen when SSL is actually used for the first time.

**Comment by jansupol** [comment]
This seems to go right against #4566.

**Comment by jansupol** [comment]
We may use `LazyValue` that uses the double-checked-locking. The LazyValue ought to be better for the native image, too.
