### ISSUE TITLE
Availability of  3.0.2 on Maven central

### ISSUE THREAD

**Issue by nhenneaux** [eclipse-ee4j/jersey#4786]
I'm looking to update Jersey for security issue https://github.com/eclipse-ee4j/jersey/security/advisories/GHSA-c43q-5hpj-4crv but cannot find an artifact on Maven.

**Comment by jansupol** [comment]
Yes, we will promote Jersey 3.0.2 to Maven Central shortly.

**Comment by jansupol** [comment]
It is in maven central now.
