### ISSUE TITLE
why jersey-helidon-connector:3.x is not avaliable on mvnrepository.com?

### ISSUE THREAD

**Issue by copbint** [eclipse-ee4j/jersey#4805]
please look at:  
<https://mvnrepository.com/artifact/org.glassfish.jersey.connectors/jersey-helidon-connector>

**Comment by jansupol** [comment]
Unfortunately, there is no Helidon that works with `jakarta.ws.rs-api`, yet. Helidon connector provider has the main method `public Connector getConnector(Client client, Configuration runtimeConfig)` and Helidon would not understand the arguments, at the moment. The Helidon 4 would use jakarta API and the Helidon connector would be in maven central again, then.

**Comment by copbint** [comment]
Thanks for your reply!  
well, while it is definitited in the bom:  
<https://github.com/eclipse-ee4j/jersey/blob/master/bom/pom.xml#L68>  
this actuall make me fell some confuse...
it would be nice to keep bom sync with real released jars ^_^

**Comment by jansupol** [comment]
You are right, thanks for pointing it out. We shall remove it from the bom pom.
