### ISSUE TITLE
Sun Jersey Dual License is not clearly mentioned in https://javaee.github.io/glassfish/LICENSE

### ISSUE THREAD

**Issue by akscis** [eclipse-ee4j/jersey#4807]
The dual license for Jersey is not clearly indicated on the respective license page for the repository. Before the actual license text begins, we should mention that the license is a dual license and GPLv2 license is applicable with a classpath exception. 

https://javaee.github.io/glassfish/LICENSE

The license pages have moved for the older version making it difficult to track the appropriate license URL to include in a product using Jersey.

**Comment by jansupol** [comment]
First, https://javaee.github.io/glassfish/LICENSE is a page for old Java EE Projects. The license of Jersey in Java EE was CDDL + GPLwCPE (up to Jersey 2.27). As noted in the LICENSE webpage, the information is archived, i.e. read-only.

After transitioning to the Eclipse Foundation, which the current repository is a part of it, the license changed. The current license (Jersey 2.28+) is here: https://github.com/eclipse-ee4j/jersey/blob/master/LICENSE.md. We use EPL 2.0 + GPLv2wCPE, as well as other Eclipse EE4J projects.

**Comment by jansupol** [comment]
The link https://javaee.github.io/glassfish/LICENSE reflects the license for Glassfish 4.x and 5.0. It does not relate to Jakarta Jersey, hence closing. Feel free to open a new bug if you feel the licensing is still not handled properly.
