### ISSUE TITLE
Problem with high level of concurrency

### ISSUE THREAD

**Issue by dsvensson** [eclipse-ee4j/jersey#4842]
Running a test suite on a 32 core machine results in random failures, as if Jersey hasn't started properly when the test methods start.

One example is that I randomly get the following reply when using the target() to call a resource:
```
<html><head><title>Grizzly 2.4.4</title><style>...
```

I've specified the following props in gradle:
```
systemProperty("jersey.config.test.container.port", "0")
systemProperty("junit.jupiter.execution.parallel.enabled", "true")
systemProperty("junit.jupiter.execution.parallel.mode.default", "same_thread")
systemProperty("junit.jupiter.execution.parallel.mode.classes.default", "concurrent")
```

I have on abstract base class that inherits JerseyTest, which then 

Is there anything else I need to configure for this to work? 

I have this problem with both 2.30 and 2.34.

**Comment by jansupol** [comment]
> <html><head><title>Grizzly 2.4.4</title><style>... 

is basically a generic error response from grizzly client, saying that there was something wrong (usually on the server side), perhaps wrong path or some other 4xx http error. Easiest way to check is to observe [ServerRuntime.Responder#process](https://github.com/eclipse-ee4j/jersey/blob/bb78d64bfb4c2dd9b514e3c3d0f4db89c8bb2bb8/core-server/src/main/java/org/glassfish/jersey/server/ServerRuntime.java#L399). Are you sure you have the app setup correctly? The actual Throwable could be more descriptive.

**Comment by dsvensson** [comment]
Yep, 404. I interpret that as accessing the resource and the expected resource is not available at the path the client requested. I worry that this is due to either accessing the wrong server in a concurrent environment, or some other racy reason. The tests work flawlessly without concurrency. I'll have a look at the `process` method you suggested, and failing to do so I'll try to come up with a test case that reproduces the issue.

**Comment by dsvensson** [comment]
Finally found a pattern in what seemed to be random failures, and they were all in one way or another in a similar category of tests. Turned out to be an test specific AtomicReference that needed to be a ThreadLocal when going parallel.
