### ISSUE TITLE
maven3.8.2 build instructions for Jersey 3.0.1

### ISSUE THREAD

**Issue by pkcs11newbie** [eclipse-ee4j/jersey#4844]
Hello

I'm looking for instructions to build jersey source code using maven. 

So far,
1) Installed and setup maven (3.8.2)
2) Downloaded jersey source code from https://github.com/eclipse-ee4j/jersey/tree/3.0.1 and Unzipped it ( ex: D:\workdir\XXX\jersey3.0.1\jersey-3.0.1)
3) D:\workdir\XXX\jersey3.0.1\jersey-3.0.1>mvn package -Dmaven.test.skip=true -PcheckstyleSkip

I ran into issue in regards to directory-maven-plugin:0.3.1:highest-basedir (directories), which after a lot of googling, came across stackoverflow user who suggested to use directory-of goal. 
Attaching modified pom.xml for reference.
[pom.txt](https://github.com/eclipse-ee4j/jersey/files/7049738/pom.txt)

My expectation was to download jersey source code and built it using maven and generate the jersey jars that we need in our application. I wasn't expecting to make any changes to  pom.xml, but then again I haven't much experience with maven.  So, any help will be greatly appreciated.

Thanks..

**Comment by jansupol** [comment]
I have tested it with maven 3.8.2 and it worked for me, but we have a report that the `directory-maven-plugin` works well only with maven 3.6.x. Can you test it?

**Comment by jansupol** [comment]
It really looks like on some OS, `directory-maven-plugin` did not work with maven 3.8.2. Fortunately, there is recently version 1.0 of `directory-maven-plugin` released, which seem to working fine.
