### ISSUE TITLE
Release Jakarta version corresponding to 2.35

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jersey#4862]
A while ago Jersey 2.35 was released, but it looks like there was no corresponding Jakarta.* release this time around.

Should/can this be released still?

**Comment by senivam** [comment]
Hi Arjan, now we are releasing the 3.0.3 version which corresponds to 2.35. It shall be publicly available till the end of the week.

**Comment by arjantijms** [comment]
@senivam Thanks! :)

**Comment by senivam** [comment]
@arjantijms - Hi Arjan, just letting you know that 3.0.3 is in central. Thus the issue is resolved.

**Comment by arjantijms** [comment]
@senivam great! I'll do a PR to add this release to GF :)
