### ISSUE TITLE
Jersey Accept header validation

### ISSUE THREAD

**Issue by danielpenchev98** [eclipse-ee4j/jersey#4869]
Hi, I was just wondering if there is a way to prevent the validation of headers like Accept/Content-Type. The expected values in those headers might contain symbols like "=" (in the content type like JSON, XML, not the additional params after `;`) which apparently aren't allowed by Jersey. Normally if it didn't contain these chars, I would just declare a custom type either in the web.xml or in the servlet class as annotation, but that's not the case. I've also tried to alter the header value via Filters, but unfortunately, the request doesn't get to the filter. Is there a way somehow to tell Jersey to stop this request preprocess? (Modifying the clients of the servlet isn't an option, because of a back-compatibility requirement).
I'm using the jersey maven dependency v2.29.
Thanks in advance,
Daniel

**Comment by jansupol** [comment]
Can you please write few lines of code that show what you mean?
The following example seems to be working fine:
```
WebTarget target = ...
try (Response r = target.request().header(
                HttpHeaders.ACCEPT, "text/html, application/xhtml+xml, application/xml;q=0.9, */*;q=0.8").get()) {
            ....
}
```

**Comment by danielpenchev98** [comment]
@jansupol When i execute the request via `curl -v -H ‘accept: version=1.0’ -H ‘Content-Type: application/json’  $URL`,  the server, which uses jersey for its servlets, immediately returns 400, because of the Accept header value. The problem doesn't seem to be in the logic, I've written, for handling the request, because the request doesn't even reach my logic. My question is if there is a hidden functionality, which comes from `Jersey` itself, for validating the values of such headers and how can I disable this functionality only for this header type.

**Comment by jansupol** [comment]
HTTP Accept header is defined by [RFC 2616](https://datatracker.ietf.org/doc/html/rfc2616#page-100). `accept: version=1.0` header has invalid syntax per the RFC and it cannot be parsed by Jersey. Because of this, returns 400. Note that Jersey requires the Accept header on the server side, since it sets the media type header for the response accordingly.

If you really want to handle these invalid Http headers, you can do so in the `PreMathching` filters, for instance:
```
    @PreMatching
    protected static class HeaderFilter implements ContainerRequestFilter {
        @Override
        public void filter(ContainerRequestContext requestContext) throws IOException {
            requestContext.getHeaders().remove(HttpHeaders.ACCEPT);
        }
    }
```

**Comment by jansupol** [comment]
If you have more questions, feel free to reopen or create a new issue.
