### ISSUE TITLE
Vulnerable package in jersey-bean-validation 2.35

### ISSUE THREAD

**Issue by helinlee2010** [eclipse-ee4j/jersey#4907]
Hello,

The package used in `jersey-bean-validation 2.35` called: jakarta.el (version: 3.0.3) was reported to be vulnerable. 
Is it possible to get `jakarta.el` upgraded to 3.0.4 or newer for the **next 2.x** release?
![image](https://user-images.githubusercontent.com/57208483/138528426-911ca3e8-183e-4a91-a37e-3f14f4351721.png)

Thanks

**Comment by jansupol** [comment]
Jakarta EL 3.0.3 API is the newest javax EL API.
Jersey 2.35 already upgraded impl to [3.0.4](https://github.com/eclipse-ee4j/jersey/blob/e682eb98080f9672b071127feb838fa55477ea96/pom.xml#L2170)
