### ISSUE TITLE
CompletionCallback called early?

### ISSUE THREAD

**Issue by marcel-rothe** [eclipse-ee4j/jersey#4909]
Hello,

we have an application that relies on the timing of request completion. We use AsyncResponse with a CompeltionCallback that sends a websocket message as soon as it gets called similar to this example:
```
  @GET
  @Path("/test")
  public void test(@Suspended AsyncResponse ar)
  {
    ar.register((CompletionCallback) throwable -> {
      try
      {
        sessionHandler.getAllClientSessions().forEach(
            c -> {
              logger.info("Sending websocket message ... ");
              try
              {
                if (c.getSession() != null)
                  c.getSession().getBasicRemote().sendText("test " + new Date());
              } 
              catch (IOException e)
              {
                e.printStackTrace();
              }
              logger.info("After sending websocket message ... ");
            }
        );
      } catch (Exception e)
      {
        e.printStackTrace();
      }
    });
    ar.resume(Response.ok().build());
  }
```
However, it seems the CompletionCallback is called while the response is still being written. In a test the websocket message arrives before the REST response? Is this intended behavior or am I missing something?

```
...
test Wed Oct 27 11:59:50 CEST 2021
InboundJaxrsResponse{context=ClientResponse{method=GET, uri=http://localhost:8090/api/planning/test, status=200, reason=OK}}
...
```
My expectation would be that the response is fully written to the client before the callback executes. That is also how I read the javadoc.

Thanks.

**Comment by jansupol** [comment]
Yes, technically you are right, Jersey calls the callback and returns the response afterward. I assume this is to require just a single thread.

But the client should not rely on the order; even if the response is sent first, it can be received after the WebSocket response anyway. Each response (WebSocket, JAX-RS) is processed by a different Server thread and the order is not guaranteed. Also, the network connection can affect the order.

**Comment by marcel-rothe** [comment]
Thanks for your answer. So is there maybe any other way to find out, when a response was fully written to the client? I also tried request lifecylce events, but it did not work either.

**Comment by jansupol** [comment]
You already have the WebSocket Session, so can the WebSocket client notify when the response is received by the JAX-RS client?
That seems the cleanest way to know the _client_ already received the response message.

**Comment by marcel-rothe** [comment]
Ok, that's what we were thinking, too. Thanks for your help.
