### ISSUE TITLE
Support for Spring Framework 6

### ISSUE THREAD

**Issue by wilkinsona** [eclipse-ee4j/jersey#4915]
Do you have any plans to introduce a `jersey-spring6` module in Jersey 3.x? It's a little too early to do anything right now as development work on Spring Framework 6 has only just begun. Snapshots are available from https://repo.spring.io/snaphot and the first milestone is scheduled for 15 December. One of the major changes in Framework 6 is the upgrade to Jakarta EE 9. Hopefully this hopefully aligns quite nicely with Jersey 3.x. If there's anything that we (the Spring team) can do to help with Spring Framework 6 support in Jersey 3.x, please let me know.

**Comment by jansupol** [comment]
@wilkinsona Yes, we would like to support Spring 6. With Spring 5 we had some issues supporting spring with just using annotated beans without the xmls. Help from the Spring team would be appreciated. 

I do not think it is an issue to support milestone versions of Spring 6, as long as they are in the maven central. Glad to hear Spring will support jakarta.inject.

**Comment by wilkinsona** [comment]
Unfortunately, milestones are not published to Maven Central. They will be published to https://repo.spring.io/milestone.

**Comment by jansupol** [comment]
We may add the repo to the spring module. As long as the source code is available there for the legal to verify the licensing, Jersey should be good.

**Comment by wilkinsona** [comment]
Great. Yes, the source will be there. It’s all Apache v2 licensed as before.

**Comment by jansupol** [comment]
M2 is out there

**Comment by jansupol** [comment]
@wilkinsona Feel free to review #5023.
