### ISSUE TITLE
jersey ClientConfig throws NPE's in ApacheConnector if connect/read timeouts are set with long values instead of int

### ISSUE THREAD

**Issue by jcalcote** [eclipse-ee4j/jersey#4930]
Using Jersey 2.35 with apache connector provider. If you set ClientProperties.CONNECT/READ_TIMEOUT values using long values rather than int values, the configuration is created successfully, but as soon as the connector attempts to use the values, it can't parse or properly cast the longs  to integers.

**Comment by jansupol** [comment]
Yes, this is correct. Jersey tries to convert the object to a value type, but `Long` cannot be cast to `int` nor `Integer`.
