### ISSUE TITLE
Release 3.1.0-M2

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jersey#4941]
Hi,

The current release of 3.1,  M1, unfortunately doesn't work for GlassFish 7 and/or CDI 4 environments at all. It's only a few commits that are missing, but they are absolutely critical.

Shall we stage an M2?

I can do this myself.

**Comment by senivam** [comment]
Hi Arjan, 

we will release the M2 shortly. There is a separate job for the 3.1.x releases.

**Comment by arjantijms** [comment]
Thanks @senivam 

Btw, this job can probably be updated to JDK 17 now: 
https://ci.eclipse.org/jersey/job/continuous-integration/job/3.1/

**Comment by senivam** [comment]
regarding build update to JDK 17 there is an issue related to maven 3.8.3, nexus-staging-maven-plugin which requires as workaround setting of ``JDK_JAVA_OPTIONS`` or ``MAVEN_OPTS`` to `--add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.desktop/java.awt.font=ALL-UNNAMED`

so as soon as we still have everything targeted to JDK 11 and for now release perfectly works on JDK 11.0.2 I would keep that configuration until some fixes are released for indicated maven/nexus-staging-maven-plugin combination.

**Comment by arjantijms** [comment]
@senivam I see, though Jenkins I think I still running Maven 3.6.0 or so. At least for GlassFish we're able to build with JDK 17. See https://ci.eclipse.org/glassfish/view/GlassFish/job/glassfish_build-and-test_jdk17/

The importance to test/build on JDK 17 as well, is that Jakarta EE 10 promises (more or less) compatibility with JDK 17.

**Comment by senivam** [comment]
Sorry Arjan, I've got it wrong :) I thought we are talking about the release but for sure CI/CD build job shall be upgraded to perform builds on JDK17. Please take a look to the linked PR. Thanks :)

**Comment by jansupol** [comment]
The main JDK version for Jakarta EE 10 is JDK 11. We should be certain that Jersey works well on JDK 17, but the main testing should be on JDK 11.

**Comment by arjantijms** [comment]
@jansupol indeed, agreed!

**Comment by jansupol** [comment]
@arjantijms Jersey 3.1.0-M2 is in staging.

**Comment by arjantijms** [comment]
@jansupol Thanks! I'll update the GF PR to it ;)
