### ISSUE TITLE
Is there a way to get the URI-Template in a ClientRequestFilter?

### ISSUE THREAD

**Issue by wengertj** [eclipse-ee4j/jersey#4959]
Hi everyone 😃 

In the [micrometer slack](https://micrometer-metrics.slack.com/archives/C662HUJC9/p1640856353279000) there's a question/discussion going on about providing metrics for JAX-RS/Jersey clients.

Jon Schneider pointed out that there currently does not seem to be a way to get the URI-template that was used to issue a request by micrometer (or any metrics-api for that matter) in `jersey-client`. I'm not aware of an api for that either. 

Consider this simple client filter:

```java
public class MetricsFilter implements ClientRequestFilter {
    @Override
    public void filter( ClientRequestContext request ) throws IOException {
          // ... no way to access the URI-template within the filter?
   }
}
```

A workaround for this might be to actually let the user pass the URI-template via a property and then query the property in the filter.

`jersery-server` does provide such an api via `org.glassfish.jersey.server.monitoring.RequestEvent#getUriInfo`. 

So i guess I have two questions:
* Did I miss something or is there actually no api for that yet?
* Is this a feature you'd think is worth implementing in `jersey-client` (or maybe even as part of the JAX-RS spec)?

Thanks for your help!

**Comment by jansupol** [comment]
The `UriInfo` class is not implemented on the client-side, since it contains methods that are not known to the client, such as `[getPathParameters](https://docs.oracle.com/javaee/7/api/javax/ws/rs/core/UriInfo.html#getPathParameters-boolean-)`. 
We had a discussion about the possibility to provide `UriInfo` on the client-side, but it was not clear what the correct implementation should look like. We are open to suggestions, though.

**Comment by wengertj** [comment]
Thanks for your quick response, that clarifies my question 👍 

Implementing the entire `UriInfo` interface on the client-side does look challenging, I can see that.

I don't have any valuable suggestions. Maybe only that - at least for monitoring purposes - not the entire information provided by `UriInfo` would be necessary. But I can see that it might not be desirable to implement something "half-baked" on the client-side.
