### ISSUE TITLE
ApacheConnectorProvider should be abstract?

### ISSUE THREAD

**Issue by fahmydiab** [eclipse-ee4j/jersey#4961]
I got this error while trying to use OCI put Object :
Class 'ApacheConnectorProvider' must either be declared abstract or implement abstract method 'getConnector(Client, Configuration)' in 'ConnectorProvider'

**Comment by jansupol** [comment]
Or, do you use the same version of the `jersey-apache-connector` and `jersey-client` jar. Mixing version 2 and version 3 won't work,

**Comment by fahmydiab** [comment]
I think it was mixed versions, thanks
