### ISSUE TITLE
Error execute in weblogic 12.2.1.4 (cast WlsUrlConnectionProvider)

### ISSUE THREAD

**Issue by raszagar** [eclipse-ee4j/jersey#5002]
Hi, 
When excecute jersey project client in weblogic 12.2.1.4 get this error:
Cannot cast weblogic.jaxrs.client.internal.WlsUrlConnectionProvider to org.glassfish.jersey.client.spi.ConnectorProvider.

pom.xml:
```
  	<properties>
  	  	<spring.version>5.3.16</spring.version>
	  	<slf4j.version>1.7.25</slf4j.version>
	  	<jersey.version>2.35</jersey.version>
	</properties>
	...
	<dependency>
	    <groupId>org.glassfish.jersey.core</groupId>
	    <artifactId>jersey-client</artifactId>
	    <version>${jersey.version}</version>
	</dependency>
	<dependency>
	    <groupId>org.glassfish.jersey.media</groupId>
	    <artifactId>jersey-media-json-jackson</artifactId>
	    <version>${jersey.version}</version>
	</dependency>
```
weblogic.xml:
```
	<wls:container-descriptor>
 		<wls:prefer-web-inf-classes>true</wls:prefer-web-inf-classes>
	</wls:container-descriptor>
```
web.xml:
```
        <!-- This turn off the default jersey servlet for deploy with libraries from project -->
	<servlet>
		<servlet-name>TurnOffJerseyServlet</servlet-name>
		<servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class>
		<init-param>
			<param-name>jersey.config.server.provider.packages</param-name>
			<param-value>org.none</param-value>
		</init-param>
		<init-param>
			<param-name>jersey.config.disableAutoDiscovery</param-name>
			<param-value>true</param-value>
		</init-param>
	</servlet>
	<servlet-mapping>
		<servlet-name>TurnOffJerseyServlet</servlet-name>
		<url-pattern>/TurnOffJerseyServlet*</url-pattern>
	</servlet-mapping>
```
Java client:
```
	public ObjetoVO test() throws Exception {
		Client client = ClientBuilder.newClient(getConfig());
		WebTarget target = client.target("http://localhost:7001/iwmobilews/ws");
		return target.path("/api/test").request(MediaType.APPLICATION_JSON).get(ObjetoVO.class);
	}
	public ClientConfig getConfig() {
		ClientConfig config = new ClientConfig();
		config.register(getJsonProvider());
		return config;
	}
	public JacksonJaxbJsonProvider getJsonProvider() {
		JacksonJaxbJsonProvider provider = new JacksonJaxbJsonProvider();
		provider.setMapper(objectMapperClient());
		return provider;
	}
	public ObjectMapper objectMapperClient() {
		ObjectMapper mapper = new ObjectMapper();
		mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
		return mapper;
	}
```

Error: Cannot cast weblogic.jaxrs.client.internal.WlsUrlConnectionProvider to org.glassfish.jersey.client.spi.ConnectorProvider
java.lang.ClassCastException: Cannot cast weblogic.jaxrs.client.internal.WlsUrlConnectionProvider to org.glassfish.jersey.client.spi.ConnectorProvider
        at java.lang.Class.cast(Class.java:3369)
        at org.glassfish.jersey.internal.ServiceFinder$LazyObjectIterator.hasNext(ServiceFinder.java:690)
        at org.glassfish.jersey.client.ClientConfig$State.<init>(ClientConfig.java:144)
        at org.glassfish.jersey.client.ClientConfig.<init>(ClientConfig.java:509)
        at es.prueba.proyecto.ws.client.JerseyClientConfig.getConfig(JerseyClientConfig.java:23)
        at es.prueba.proyecto.ws.client.JerseyClient.test(JerseyClient.java:25)
        at es.prueba.proyecto.services.ProyectoService.test1(ProyectoService.java:48)
        at es.prueba.proyecto.Proyecto.test1(Proyecto.java:39)
        at jsp_servlet.__index._jspService(__index.java:124)

Can help me, please? 
Thanks.

**Comment by jbescos** [comment]
From the error I would say that WlsUrlConnectionProvider is not implementing/extending org.glassfish.jersey.client.spi.ConnectorProvider. Possibly because of a Jersey version missmatching.

Try to change the maven dependencies to scope provided. Then, the Jersey libraries of Weblogic will be loaded, and hopefully that fixes your issue.
```
	<dependency>
	    <groupId>org.glassfish.jersey.core</groupId>
	    <artifactId>jersey-client</artifactId>
	    <version>${jersey.version}</version>
            <scope>provided</scope>
	</dependency>
	<dependency>
	    <groupId>org.glassfish.jersey.media</groupId>
	    <artifactId>jersey-media-json-jackson</artifactId>
	    <version>${jersey.version}</version>
            <scope>provided</scope>
	</dependency>
```

**Comment by jansupol** [comment]
`WlsUrlConnectionProvider` is from 12.2.1.4, i.e. it extends Jersey 2.22.4 `ConnectorProvider`, whereas your client is using Jersey 2.35 `ConnectorProvider`.

It looks like `getConfig()` registers `WlsUrlConnectionProvider` (`ClientConfig.connectorProvider(WlsUrlConnectionProvider))`

**Comment by jansupol** [comment]
The `ConnectorProvider` has not changed between the versions, I assume there would be a classloading issue, where the 2.22.4 `ConnectorProvider` is loaded by a different classloader than 2.35 `ConnectorProvider` classloader. You can compare `WlsUrlConnectionProvider.class.getClassLoader()` with for instance `ConnectorProvider.class.getClassLoader()`.

**Comment by raszagar** [comment]
Hi,
When downgrade jersey version to 2.22.4 not work (same error).
Whit @jbescos solution work, with jersey from weblogic, thanks!
