### ISSUE TITLE
Jersey license clarification

### ISSUE THREAD

**Issue by ppatierno** [eclipse-ee4j/jersey#5004]
Hello everyone,
by reading the [LICENSE.md](https://github.com/eclipse-ee4j/jersey/blob/master/LICENSE.md) file, it seems to be clear that Jersey has a double license: EPL 2.0 and GPL 2.
Taking a look at the main [pom.xml](https://github.com/eclipse-ee4j/jersey/blob/master/pom.xml#L147) I noticed more than that and other licenses, including the W3C one which sounds to be not really "open source" in terms of redistribution.
It mentions that it's used in core-server but then the corresponding [pom.xml](https://github.com/eclipse-ee4j/jersey/blob/master/core-server/pom.xml#L36) doesn't mention that license.
Is that possible to have a clarification about it, what's the reason for W3C mentioned there? Is that really the case or we can just assume Jersey is double licensed as EPL 2.0 and GPL 2.
Thanks!

**Comment by jansupol** [comment]
The complete licensing information is in the [NOTICE](https://github.com/eclipse-ee4j/jersey/blob/master/NOTICE.md) files (there are more of them, the modules with the 3rd party code contain their own NOTICE.markdown files). 

In short, Jersey is dual-licensed under (EPL 2.0 and GPL 2+CPE) license, which is mandated by the Eclipse Jakarta project. Some classes (repackaged) contain additional licenses compatible with the Eclipse Foundation Jakarta rules.
The [mentioned W3C](https://github.com/eclipse-ee4j/jersey/blob/master/pom.xml#L212) license is used in some XML/XSD/DTD files under core-server/etc used in the compile time. These files are not distributed in the binary Jersey jar files.

**Comment by ppatierno** [comment]
@jansupol thank you very much for the answer. It makes more sense to me now!
