### ISSUE TITLE
Java 17 support for wadl-doclet 2.30+/3.x 

### ISSUE THREAD

**Issue by johnmarquez12** [eclipse-ee4j/jersey#5015]
I have a project transitioning from Java 11 to Java 17 depending on the wadl-doclet library, but having issues with `DocProcessor` class as it uses the deprecated sun.javadoc libs. From what I can see here: https://github.com/eclipse-ee4j/jersey/tree/master/ext/wadl-doclet/src/main/java12/org/glassfish/jersey/wadl/doclet, it was updated to support Java 13, and these changes should make it compatible with Java 17 but pulling in the library (3.0.4) gives me the older Java 8/11 version of the class. My gradle dependency is just defined as: 

```
implementation group: 'org.glassfish.jersey.ext', name: 'jersey-wadl-doclet', version: '3.0.4'
```

Is there anything I could be missing?

**Comment by jansupol** [comment]
>  gives me the older Java 8/11 version of the class

What do you mean by? The `jersey-wadl-doclet.jar` contains both versions.

**Comment by johnmarquez12** [comment]
> > gives me the older Java 8/11 version of the class
> 
> What do you mean? The `jersey-wadl-doclet.jar` contains both versions.

This is what I'm getting:
<img width="611" alt="image" src="https://user-images.githubusercontent.com/42983443/160682610-de27d191-c9c0-43fb-8d0c-91e3477273e5.png">

<img width="711" alt="image" src="https://user-images.githubusercontent.com/42983443/160683118-c8854c70-75a2-4019-8e28-c3869b579b46.png">

**Comment by jansupol** [comment]
I see. This is a multirelease jar. You see a default location for classes. The JDK 12+ classes are in the META-INF/versions/12 folder to be understood by the JDK classloader.
