### ISSUE TITLE
Netty Connector doesn't support Followredirects.

### ISSUE THREAD

**Issue by sumitaneja** [eclipse-ee4j/jersey#5045]
Follow redirect(jersey.config.client.followRedirects)  is true but netty connector still doesn't follow redirect and provides 307 to client.

**Comment by jbescos** [comment]
Hi @sumitaneja I have created an [issue](https://github.com/netty/netty/issues/12332) in Netty to support follow redirects.

We will see whether they can implement this, or we have to implement it in Jersey.

**Comment by jansupol** [comment]
hm... I think Netty supports follow-redirect, at least HelidonConnector based on Netty already implements follow-redirect.

**Comment by jansupol** [comment]
it might be possible that Helidon WebClient supports follow-redirect on its own, without Netty, though...

**Comment by jbescos** [comment]
> it might be possible that Helidon WebClient supports follow-redirect on its own, without Netty, though...

I think Helidon manages that in io.helidon.webclient.RedirectInterceptor

**Comment by jansupol** [comment]
Closed by #5048
