### ISSUE TITLE
Jersey BodyPartEntity issue

### ISSUE THREAD

**Issue by Nazaresh** [eclipse-ee4j/jersey#5054]
glassfish/jersey/media/multipart/internal/MultiPartResource.java

`BodyPartEntity bpe = (BodyPartEntity) multiPart.getBodyParts().get(0).getEntity(); `
"java.lang.String cannot be cast to org.glassfish.jersey.media.multipart.BodyPartEntity"

I missed something?

Jersey 3.0.4
Java 1.8

```
FormDataMultiPart multiPart = new FormDataMultiPart()
.bodyPart(new FormDataBodyPart("meta", "{\"idDocType\":\"PASSPORT\",\"country\":\"ALB\"}", MediaType.APPLICATION_JSON_TYPE))
.bodyPart(new FormDataBodyPart("cont", doc, new MediaType("image", MediaType.MEDIA_TYPE_WILDCARD)));
```

![image](https://user-images.githubusercontent.com/81460039/165769919-f8c64529-18eb-4f3c-8998-d03751f25062.png)

**Comment by jansupol** [comment]
Can you provide a full example?

**Comment by Nazaresh** [comment]
```
import com.fasterxml.jackson.databind.ObjectMapper;

import jakarta.ws.rs.client.Client;
import jakarta.ws.rs.client.ClientBuilder;
import jakarta.ws.rs.client.Entity;
import jakarta.ws.rs.client.WebTarget;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;

import org.glassfish.jersey.media.multipart.BodyPartEntity;
import org.glassfish.jersey.media.multipart.FormDataBodyPart;
import org.glassfish.jersey.media.multipart.FormDataMultiPart;
import org.glassfish.jersey.media.multipart.MultiPartFeature;

import java.io.File;
import java.time.Instant;

public class DocumentAdding
{
    public static String addDocument() throws Exception
    {
        String doc = "/images/logo.jpg"
        String number= "6259f18e1e38e90001bc8e0d"
        ObjectMapper objectMapper = new ObjectMapper() ;

        FormDataMultiPart multiPart = new FormDataMultiPart();
        multiPart.bodyPart(new FormDataBodyPart("meta", "{\"first\":\"firstLine\",\"second\":\"secodLine\"}", MediaType.APPLICATION_JSON_TYPE));
        multiPart.bodyPart(new FormDataBodyPart("cont", doc, new MediaType("image", MediaType.MEDIA_TYPE_WILDCARD)));
        
        BodyPartEntity ent = (BodyPartEntity) multiPart.getBodyParts().get(0).getEntity();  // ClassCastException: java.lang.String cannot be cast to org.glassfish.jersey.media.multipart.BodyPartEntity

        BodyPartEntity ent = multiPart.getBodyParts().get(0).getEntityAs(BodyPartEntity.class);  // IllegalStateException: Entity instance does not contain the unconverted content.

        Client client = ClientBuilder.newClient().register(MultiPartFeature.class);
        WebTarget target = client.target(URL).path("/resources/").path(number).path("/info");

        Response response = target.request()
        .header("Authorization", "Bearer " + "token")
        .header("X-Impersonate", "myName")
        .post(Entity.entity(multiPart, MediaType.MULTIPART_FORM_DATA));

        return String.valueOf(response);
    }
}
```

multipart - work are good with bearer but i need bytes of multipart.

**Comment by jansupol** [comment]
I see. `BodyPartEntity` is in the `BodyPart` after the entity is sent over the wire. When you create your `FormDataMultiPart`, you have the entity which you set there, i.e. `"{\"first\":\"firstLine\",\"second\":\"secodLine\"}"`, which is String.

**Comment by jansupol** [comment]
I assume you do not mean [String#getBytes()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#getBytes()). Why do you need the bytes?

**Comment by Nazaresh** [comment]
yes its something like `String#getBytes()` in my case - requestBody==multipart. i need correctly signature (without bearer) with hmacSHA256. 
```
import org.apache.commons.codec.binary.Hex;

 createSignature(long ts, HttpMethod httpMethod, String path, byte[] body)

Mac hmacSha256 = Mac.getInstance("HmacSHA256");
        hmacSha256.init(new SecretKeySpec(SECRET_KEY.getBytes(StandardCharsets.UTF_8), "HmacSHA256"));
        hmacSha256.update((ts + httpMethod.name() + path).getBytes(StandardCharsets.UTF_8));
        byte[] bytes = body == null ? hmacSha256.doFinal() : hmacSha256.doFinal(body);
        return Hex.encodeHexString(bytes);
```
and if ill try to use not bytes
```
Mac hmacSha256 = Mac.getInstance("HmacSHA256");
byte[] bytes = hmacSha256.doFinal(multiPart); // error: incompatible types: org.glassfish.jersey.media.multipart.FormDataMultiPart cannot be converted to byte[]
        byte[] bytes = hmacSha256.doFinal(multiPart);
```

**Comment by jansupol** [comment]
But it is YOUR entities that you put into the `FormDataMultiPart`. So you likely know the content and you can convert it to bytes.

**Comment by jansupol** [comment]
It depends...you may utilize `MultiPartWriter` and serialize the MultiPart to your outputStream. Ideally, you can provide your own `MessageBodyWriter<MultiPart>` that inherits from the `MultiPartWriter`, set a proper priority so that your's would be used, then you'll call `super.writeTo` ...

But depending on what you need the `Mac` for, it may be too late for you already.

**Comment by Nazaresh** [comment]
sorry for the long answer.
yeah its help me send `application/json` part but it doest work for my `image/*` part.

i seting  type for it - `new MediaType("image", MediaType.MEDIA_TYPE_WILDCARD)`
i think it doesnt work because in MultiPart entity looks like (screen 1) - **M:\JavaJunior\JavaJunior\src\main\resources\images\MyPicture.jpg**
but if i'll try to use it (path) like HTTP message (screen 2) its doesnt work - not **autorized 401**.
and if ill try to set bytes for entity - i had **bad request 400**

cant understand how to did it similar
server accepting - `image/*`

![image](https://user-images.githubusercontent.com/81460039/171001230-8b234f30-2e26-4a3b-92b0-2497dd6cf735.png)

![image](https://user-images.githubusercontent.com/81460039/171001032-ec4ec0ba-1d1a-4359-8597-13d135cc6dcd.png)

**Comment by Nazaresh** [comment]
also doesnt work if I using `new FileDataBodyPart("content", new File(doc));`
![image](https://user-images.githubusercontent.com/81460039/171197381-2f1dbb4c-8c2e-4316-bbf4-c50267b7c35a.png)

**Comment by Nazaresh** [comment]
im find difference
when i use `MultiPartWriter` i have this:
![image](https://user-images.githubusercontent.com/81460039/171798046-1a75275a-5278-450c-a954-6a7df3e33632.png)
and i check `MultiPart` request here - https://requestcatcher.com/
![image](https://user-images.githubusercontent.com/81460039/171798272-5c60b450-8f99-4913-b0b4-f8846d397a43.png)
but if i send this message like a `String` after `MultiPartWriter` i have this 
![image](https://user-images.githubusercontent.com/81460039/171798218-fa0606e8-55ba-408f-ab63-a5afb76fa302.png)
