### ISSUE TITLE
@Path("{x: .*}") does not match for URL-encoded paths segments, while @Encoded @Path("{x: .*}") does

### ISSUE THREAD

**Issue by mkarg** [eclipse-ee4j/jersey#5057]
Just noticed that the following does not match for URL encoded paths: `@Path("{x: .*}")`. The result is 404 always. If I add `@Encoded` it matches pretty well. This is weird. Did I miss something in the JAX-RS spec, or is that a bug in Jersey?

**Comment by jansupol** [comment]
I could not reproduce. 
```
    @Path("res")
    public static class ResourceThree {
        @GET
        @Path("{x: .*}")
        public String getThree() {
            return GET_VALUE;
        }
    }
```
and a request
```
        String entity = target("res").path("hello%20world%21").request().get(String.class);
        assertThat(entity, is(GET_VALUE));
```
Just works fine. Can you provide your code?

**Comment by mkarg** [comment]
Well, the application is thousands of classes... so which piece of the code do you need? The reproducer is mostly just as yours, but can you try with the following instead (yes, no typo: we want to have `x` to be a `URI` with the content `https://www.demo.com:8080/foo/bar`)?
```
curl https://localhost:8080/myapp/res/https://www.demo.com:8080/foo/bar
```
with code changed to:
```java
public String getThree(@PathParam("x") URI uri)
```

**Comment by jansupol** [comment]
No still could not reproduce
```
    @Path("three")
    public static class ResourceThree {
        @GET
        @Path("{x: .*}")
        public String getThree(@PathParam("x") URI uri) {
            return GET_VALUE;
        }
    }
```
```
    @Test
    public void testGetThree() {
        String entity = target("three").path("https://www.demo.com:8080/foo/bar").request().get(String.class);
        assertThat(entity, is(GET_VALUE));
    }
```

> so which piece of the code do you need?

The reproducer.

**Comment by mkarg** [comment]
I assume that `.path("...")` actually encodes the colons and dashes, which certainly would solve the problem. Will strip down my actual app to the bare minimum to see if it still happens. Will take some time. Stay tuned.

**Comment by mkarg** [comment]
This is pretty strange. I could reproduce all through the past weeks (worked with `@Encoded`, returned `404` without), and now that I want to strip it down to a reproducer, it just works perfectly fine in *all* cases. Anyways, as it does work, it cannot be a bug in Jersey. Sorry for the confusion, and a big thank you for picking up this issue. You always are a great help!

**Comment by mkarg** [comment]
To whom it may concern: The bug can only be reproduced when (a) using Payara 5.2022.1 (it includes a re-packaged Jersey 2.34) but not with Jersey 2.34 standalone, and (b) when the passed URI-typed path parameter contains `foo%20bar` (not `foo/bar`). Only in that particular combination the caller gets a 404 response unless the path parameter is annotated with `@Encoded`, and the JAX-RS resource method is not invoked at all. As soon as you run it on Jersey 2.34 standalone (without Payara) or not having `%20` in the path param value, the JAX-RS resource method is correctly invoked. I tried with exactly the same code in both cases. So apparently this seems to be a bug in the Payara repackaging and is not a native Jersey bug.
