### ISSUE TITLE
Dependency convergence in 3.0.5

### ISSUE THREAD

**Issue by agavrilov76** [eclipse-ee4j/jersey#5087]
The enforcer plugin fails with the following error on 3.0.5 due dependency convergence for `jakarta.inject:jakarta.inject-api`
```
Warning:  
Dependency convergence error for jakarta.inject:jakarta.inject-api:2.0.1 paths to dependency are:
+-com.telenordigital.tdbase:tdbase-client:1.0-SNAPSHOT
  +-org.glassfish.jersey.core:jersey-client:3.0.5
    +-org.glassfish.jersey.core:jersey-common:3.0.5
      +-jakarta.inject:jakarta.inject-api:2.0.1
and
+-com.telenordigital.tdbase:tdbase-client:1.0-SNAPSHOT
  +-org.glassfish.jersey.core:jersey-client:3.0.5
    +-jakarta.inject:jakarta.inject-api:2.0.1
and
+-com.telenordigital.tdbase:tdbase-client:1.0-SNAPSHOT
  +-org.glassfish.jersey.inject:jersey-hk2:3.0.5
    +-org.glassfish.hk2:hk2-locator:3.0.3
      +-jakarta.inject:jakarta.inject-api:2.0.0
and
+-com.telenordigital.tdbase:tdbase-client:1.0-SNAPSHOT
  +-org.glassfish.jersey.inject:jersey-hk2:3.0.5
    +-org.glassfish.hk2:hk2-locator:3.0.3
      +-org.glassfish.hk2:hk2-api:3.0.3
        +-jakarta.inject:jakarta.inject-api:2.0.0
and
+-com.telenordigital.tdbase:tdbase-client:1.0-SNAPSHOT
  +-org.glassfish.jersey.inject:jersey-hk2:3.0.5
    +-org.glassfish.hk2:hk2-locator:3.0.3
      +-org.glassfish.hk2:hk2-utils:3.0.3
        +-jakarta.inject:jakarta.inject-api:2.0.0

Warning:  Rule 1: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
```

**Comment by jansupol** [comment]
Congratulations! You are the first to file an issue with 3.0.5. That was fast!

Jersey does seem to be using the enforcer plugin itself. Sounds like it should.

**Comment by jansupol** [comment]
The workaround is of course to exclude the `jakarta.inject:jakarta.inject-api` dependency from `org.glassfish.jersey.inject:jersey-hk2` for the time being.

**Comment by zUniQueX** [comment]
> Jersey does seem to be using the enforcer plugin itself. Sounds like it should.

I'd appreciate having `DependencyConvergence` enabled. I've recently experienced an issue with that in the Grizzly connector too.

Currently Jersey uses the `maven-enforcer-plugin:3.0.0-M2` without the `DependencyConvergence` rule enabled. Please note, that the rule has some issues in the final 3.0.0 release (e.g. [MENFORCER-394](https://issues.apache.org/jira/browse/MENFORCER-394)). If you plan to upgrade the enforcer plugin, enabling `DependencyConvergence` may have to wait.

**Comment by mraible** [comment]
Is this fixed in https://github.com/eclipse-ee4j/jersey/pull/5092? If so, can this issue be closed and v3.0.6 released?

**Comment by senivam** [comment]
Hi @mraible, yes, the dependency convergence issue is fixed and merged. But in order to do a release, we have to collect more fixes/features. I think a release will happen soon but I cannot predict an exact date for now.

**Comment by bdemers** [comment]
I have a biased opinion, but getting a release out sooner would allow for Jersey support to be added back into Spring Boot v3 😁

**Comment by senivam** [comment]
@bdemers sure, but with all due efforts, it won't be possible till the next week.

**Comment by bdemers** [comment]
Awesome news! thanks @senivam!

**Comment by senivam** [comment]
@bdemers, @mraible - the 3.0.6 version is available in central sine today.
