### ISSUE TITLE
question about MultiPartWriter\MessageBodyWriter 

### ISSUE THREAD

**Issue by Nazaresh** [eclipse-ee4j/jersey#5088]
Standart MultiPartWriter is good for me but I can't understand how to set **Providers** for my MultiPart when I use MultiPartWriter. 
When I try to use it I facing with null point exception (because no one in my MultiPart) 
![image](https://user-images.githubusercontent.com/81460039/174534390-00b14e35-8a2c-4742-8a9c-42204ff5f2c6.png)

If I try to check my POST request with debug mode and I can see at MultiPartWriter class (org.glassfish.jersey.media.multipart.internal) needed providers:
![image](https://user-images.githubusercontent.com/81460039/174576025-78d26570-4dea-46ac-979c-b04f85ae1dad.png)

Can't understand how can I get\set it.

**Comment by jansupol** [comment]
`@Providers` are Jersey class, usually injected by `@Context Providers providers`. Can you please provide a reproducer that demonstrates the missing injections? Note that MultiPartWriter should not be instantiated by users

**Comment by Nazaresh** [comment]
Yes, as I understand, by debug - providers are set automatically. 
And yes, I try to use `new MultiPartWriter(*wanna providers*)` because I need to get my multipart body before sending. Like this: 
![image](https://user-images.githubusercontent.com/81460039/174736691-d4d84f05-a5b1-4ed5-a3ef-c7ba2d7c07f2.png)

As I understand correctly, I need to utilize my multipart by MultiPartWriter. How can I do it with injections? 
Or did I do something wrong?

**Comment by senivam** [comment]
Hi @Nazaresh , just a quick tip - you can try to inject providers just into a field, like:
```
 @Context
    protected Providers providers;
```
If this does not help, please provide some code you are working on, which can be used to reproduce the issue you are facing.

**Comment by Nazaresh** [comment]
Hi @senivam. 

https://github.com/Nazaresh/Test1/blob/master/src/main/java/Start.java

**Comment by senivam** [comment]
Hi @Nazaresh, according to the provided code example, you may want to take a look at Jersey's user guide, particularly a chapter about client implementation: https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest3x/client.html#d0e5148 It should help to properly implement and use client relevantly to your needs.

**Comment by Nazaresh** [comment]
Aha. Thank you! Let me try

**Comment by Nazaresh** [comment]
@senivam hi. I checked this chapter and I'm not sure about this method. As I understand correctly it can help only after request (because its implemented in **ClientConfig**), but I need my HTTP message from **MultiPart** before it. And if I can see, it's more for **headers** not for **entity**

**Comment by jansupol** [comment]
@Nazaresh Please understand that when @Context is used, in order for the DI container to inject, the instance needs to be created by the DI container. Your [Start](https://github.com/Nazaresh/Test1/blob/master/src/main/java/Start.java) is not instantiated at all (all is done in the static method), and the DI container (HK2) needs to instantiate the object with @Context.

The DI container started for each client when a request is invoked. You can possibly have a `ClientRequestFilter` registered in a `ClientConfig` and when the filter gets invoked, `@Context` fields would be injected and available for you.

Starting the DI container by yourself (and configuring it) is also possible, but very difficult.

**Comment by Nazaresh** [comment]
Aha. Thanks! I missed it.
