### ISSUE TITLE
repeating requests for authentication does not handover acceptedMediaTypes but the entity mediaType

### ISSUE THREAD

**Issue by dgeissl** [eclipse-ee4j/jersey#5119]
as of https://javaee.github.io/javaee-spec/javadocs/javax/ws/rs/client/WebTarget.html#request-javax.ws.rs.core.MediaType...- the `WebTarget#request` method will get the `acceptedResponseTypes` as parameter.

But when repeating non-preemptive requests the `HttpAuthenticationFilter` will use the `ClientRequestContext#getMediaType` method to get the acceptedMediaType:
https://github.com/eclipse-ee4j/jersey/blob/da45922dca0f151e2253b1124f5fc9f751904550/core-client/src/main/java/org/glassfish/jersey/client/authentication/HttpAuthenticationFilter.java#L289-L294

but according to https://javaee.github.io/javaee-spec/javadocs/javax/ws/rs/client/ClientRequestContext.html#getMediaType-- this method will return the media type of the requests entity and not what it expects to be returned.

I'd say one has to take the `ClientRequestContext#getAcceptableMediaTypes` to make it work correctly.

**Comment by jansupol** [comment]
Technically, you are correct. However, the `mediaType` does not matter. All headers are cleared at 
https://github.com/eclipse-ee4j/jersey/blob/da45922dca0f151e2253b1124f5fc9f751904550/core-client/src/main/java/org/glassfish/jersey/client/authentication/HttpAuthenticationFilter.java#L306

and new headers, including the correct `acceptableMediaType` is set there. 

Do you have any actual issue with the code?

**Comment by dgeissl** [comment]
Thank you for the quick response, I guess you are right and it should actually override the acceptedMediaType anyways.

I'll take a deeper look into our problem. 
We had some issues where the request has a different MediaType for the entity that what was accepted for the response. But the code is a custom JaxRs 2.0 backport of `repeatRequest` used in more scenarios than authentication. But as it was heavily inspired by this project we thought it would be a good idea to share our finding.
