### ISSUE TITLE
Issue with Jetty test framework provider in 3.0.6

### ISSUE THREAD

**Issue by zUniQueX** [eclipse-ee4j/jersey#5130]
After upgrading to Jersey 3.0.6, I experienced issues with the Jetty test framework provider. The test reports the following exception although running and compiling with JDK 11 and the `--release 11` option:
```
jakarta.ws.rs.ProcessingException: Jetty container is not supported on JDK version less than 11.
```
After looking into the `MANIFEST.MF` files of the JARs, I figured out that the JAR for 3.0.5 was created by the Maven bundle plugin and the JAR for 3.0.6 was created by the Maven JAR plugin. Is this an intentional change? If yes, do you have a suggestion on how to use the provider with version 3.0.6?

**Comment by jansupol** [comment]
Jakarta EE 9 compatible Jetty is compiled with java 11 target. Jetty won't run on JDK 8. That's the same in 3.0.5. The Jetty connector an Jetty container in Jersey should o ly fail on JDK 8, saying Jetty does not work there as you could have experienced.

**Comment by zUniQueX** [comment]
Thanks for the fast answer.

I just wondered, why there is a behaviour change. I chanced nothing on the executing platform, but the provider suddenly failed after upgrading to 3.0.6.

**Comment by jansupol** [comment]
I am a bit confused, this sounds like something stopped working from 3.0.5 to 3.0.6, but Jetty 11 always required Jdk 11. Can you please explain what is the behaviour Change?

**Comment by zUniQueX** [comment]
Sorry, I could have stated this a bit more detailed.

I'm using GitHub actions with the GitHub setup-java action and Temurin JDKs 11 and 17. All tests worked fine with Jersey 3.0.5 on both JDK 11 and 17. After upgrading Jersey from 3.0.5 to 3.0.6, the tests failed with the exception provided above on both builds.

When running the tests locally on a JDK 17, I can also reproduce the behaviour change when ugrading Jersey from 3.0.5 to 3.0.6.

This issue can be reproduced with the `release/4.0.x` branch from the [Dropwizard](https://github.com/dropwizard/dropwizard) project.

**Comment by jansupol** [comment]
Timurin seems to report `java.version` fine.

**Comment by zUniQueX** [comment]
That is what made me look into the manifests. Could the different JAR output be related to this problem?

**Comment by jansupol** [comment]
The MANIFEST.MF does not matter too much, it matters in the OSGi environment. But, in Jersey 3.0.5 the jar was a multirelease jar, in Jersey 3.0.6 the Java 11+ code is missing in the jar. That's a bug. The pom.xml contains the profiles to create the multirelease jar, but only JDK 8 classes are there. This seems to be issue with our release job.

**Comment by zUniQueX** [comment]
Thanks. I'll then go back to Jersey 3.0.5 until the next version is out.

If I may ask this here: The release for version 3.1.0 is estimated for may 2022. Do you have a new ETA for this?

**Comment by joschi** [comment]
Same issue as https://github.com/eclipse-ee4j/jersey/issues/5134.

Jersey 3.0.7 is still broken.

```
❯ jar -tf jersey-container-jetty-http-3.0.7.jar
META-INF/MANIFEST.MF
META-INF/
META-INF/LICENSE.md
META-INF/NOTICE.md
META-INF/maven/
META-INF/maven/org.glassfish.jersey.containers/
META-INF/maven/org.glassfish.jersey.containers/jersey-container-jetty-http/
META-INF/maven/org.glassfish.jersey.containers/jersey-container-jetty-http/pom.properties
META-INF/maven/org.glassfish.jersey.containers/jersey-container-jetty-http/pom.xml
META-INF/services/
META-INF/services/org.glassfish.jersey.server.spi.ContainerProvider
org/
org/glassfish/
org/glassfish/jersey/
org/glassfish/jersey/jetty/
org/glassfish/jersey/jetty/JettyHttpContainer.class
org/glassfish/jersey/jetty/JettyHttpContainerFactory.class
org/glassfish/jersey/jetty/JettyHttpContainerProvider.class
org/glassfish/jersey/jetty/internal/
org/glassfish/jersey/jetty/internal/LocalizationMessages$1.class
org/glassfish/jersey/jetty/internal/LocalizationMessages$BundleSupplier.class
org/glassfish/jersey/jetty/internal/LocalizationMessages.class
org/glassfish/jersey/jetty/internal/localization.properties
```

**Comment by jansupol** [comment]
Please try 3.0.8.

**Comment by zUniQueX** [comment]
3.0.8 fixed it. Thanks :+1:
