### ISSUE TITLE
Question: Dual-licensing really possible?

### ISSUE THREAD

**Issue by tgodau** [eclipse-ee4j/jersey#5157]
The "jersey-server" component is declared to be either under EPL-2.0 or under GPL-2.0-with-classpath-exception.

As far as I see, "jersey-server" contains an Apache-2.0 licensed part ("org.glassfish.jersey.server.internal.monitoring.core").

In the case , the "org.glassfish.jersey.server.internal.monitoring.core" part is mandatory for the "jersey-server" component, I would say it is not possible to offer a dual-licensing for the component. Only licensing under EPL-2.0 would be possible (GPL-2.0-with-classpath-exception is incompatible with Apache-2.0...).

Could someone clarify this (maybe I am at the wrong place for that, so I would appreciate to guide me to the correct place...) ?

Thank you in advance.

Regards, Thorsten

**Comment by jansupol** [comment]
The Eclipse Foundation provides legal service and reviewed the code see [Project license](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16109).

My understanding is that all Jersey is EPL-2.0/GPL-2.0wCPE, except for third-party content, denoted in [NOTICE.md](https://github.com/eclipse-ee4j/jersey/blob/master/NOTICE.md) which keeps the original license. (And except examples, that use BSD-2-Clause).

Though I might be wrong, my understanding is that while LGPL and GPL are not compatible with ASL 2.0, while the CPE allows for compatibility with ASL 2.0. The list of approved (compatible licenses is denoted [here](https://www.eclipse.org/legal/licenses.php#approved)).

If any doubts, please contact [Eclipse Legal](mailto:license@eclipse.org).

**Comment by tgodau** [comment]
Hi, 
thanks for the reply.
As far as I remember the incompatibility between GPL-2.0 and Apache-2.0 is because of the patents stuff in the Apache-2.0. 
Unfortunately the classpath exception has no influence on that.
LGPL is compatible. As of version 3.0 of the GPL, Apache-2.0 is compatible.

Thanks for the hint to Eclipse Legal. I will contact them...

Regards, Thorsten
