### ISSUE TITLE
SSE events get buffered with logging enabled

### ISSUE THREAD

**Issue by toff** [eclipse-ee4j/jersey#5171]
SSE events get buffered on client when logging is enabled with
`property("jersey.config.logging.logger.level", "INFO")`
Or the `LoggingFeature`

Code example:
```java
Client client = ClientBuilder.newClient()
		// !!!
		// This will enable logging and will block until the entity buffer is full in:
		// org.glassfish.jersey.logging.LoggingInterceptor.logInboundEntity
		.property("jersey.config.logging.logger.level", "INFO")
		;

WebTarget target = client.target("http://localhost:9000/events");

SseEventSource eventSource = SseEventSource.target(target).build();
eventSource.register((event) -> {
	System.out.println("ClientReceive: " + event); // !!! This should show just after the ServerSend message
});
```
Full sample :  [my-sse-test.zip](https://github.com/eclipse-ee4j/jersey/files/9668240/my-sse-test.zip)
Tested with jersey 3.0.8
In this sample you need to wait 8 events before they get processed.

Use case : you use the same client to do REST and SSE and you enable logs.

**Comment by jansupol** [comment]
I assume you do not use the filter for logging the SSE entities. but you have the entity logging is enabled. Please set
```
.property(LoggingFeature.LOGGING_FEATURE_VERBOSITY, LoggingFeature.Verbosity.HEADERS_ONLY)
```
to disable the entity buffering. Would it help?

**Comment by jansupol** [comment]
Using logging filter with the chunked stream such as SSE is not what the filter was designed for and can have its limits. I close the issue for no response from the issuer.
