### ISSUE TITLE
using jersey-container-servlet with Tomcat 10.1 leads to NoSuchMethodError: 'void jakarta.servlet.http.HttpServletResponse.setStatus(int, java.lang.String)'

### ISSUE THREAD

**Issue by vladak** [eclipse-ee4j/jersey#5181]
As reported on https://github.com/oracle/opengrok/discussions/4070, running the [OpenGrok webapp](https://github.com/oracle/opengrok/tree/master/opengrok-web) (that uses Jersey to implement RESTful APIs) with Tomcat 10.1 leads to:
```
org.glassfish.jersey.server.ContainerException: java.lang.NoSuchMethodError: 'void jakarta.servlet.http.HttpServletResponse.setStatus(int, java.lang.String)'

jakarta.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoSuchMethodError: 'void jakarta.servlet.http.HttpServletResponse.setStatus(int, java.lang.String)'
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
...
```
This seems to be caused by Tomcat 10.1 using https://github.com/jakartaee/servlet 6.0.0 that removed bunch of deprecated servlet APIs, notably the dual argument `setStatus()` of https://github.com/jakartaee/servlet/blob/master/api/src/main/java/jakarta/servlet/http/HttpServletResponse.java.

Looking into the code, this is the culprit: https://github.com/eclipse-ee4j/jersey/blob/ecfb15eba722210dd7e05127122ad6df9141e9ef/containers/jersey-servlet-core/src/main/java/org/glassfish/jersey/servlet/WebComponent.java#L404-L405

It seems that `jersey-container-servlet` currently depends on `jakarta.servlet-api` in version 4.0.4.

**Comment by vladak** [comment]
I [see](https://github.com/eclipse-ee4j/jersey/commit/4977fecc8704dd2178dacf0ba9590f2463f8accb); did not realize that the tip of the development happens outside the master branch is. Thanks. Will wait for 3.1.0.

**Comment by jansupol** [comment]
Right, currently, most of our customers still use Jersey 2.x, and the master branch. While the community is adopting the Jakarta EE, we are getting more customers for 3.x branch, and we will switch the master to be the latest development branch, and we create an additional 2.x branch from the master. Assumingly sometimes after 3.1.0 release.

**Comment by jansupol** [comment]
Jersey 3.1.0 is out. Please give it a try.

**Comment by vladak** [comment]
For the record, moving OpenGrok to Jersey 3.1.0 (and thus Jakarta Servlet API 6.0) went quite well (PR https://github.com/oracle/opengrok/pull/4109 is about to be merged in), except the usual Jersey/Jackson struggle (Jackson is used not only via Jersey but also directly and one has to keep an eye on the Jackson version used by Jersey artifacts vs the Jackson version used directly). Thanks !
