### ISSUE TITLE
Jersey 3.0 breaking change

### ISSUE THREAD

**Issue by rakshitcgupta** [eclipse-ee4j/jersey#5196]
As per the documentation -
https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest3x/migration.html#mig-3.0.0-breaking-changes
the following is stated
The most fundamental change in Jersey 3.1.0 and later is namespace change. Since Jakarta EE 9 the jakarta. namespace is introduced as a replacement for javax namespace from Java EE.
Do you mean this change is from jersey 3.0.0 or 3.1.0 as well as per what can be seen in poms?

**Comment by jansupol** [comment]
You are right, this paragraph is about migration to 3.0.0, so the statement should be 
> The most fundamental change in Jersey 3.0.0 and later is namespace change. Since Jakarta EE 9 the jakarta. namespace is introduced as a replacement for javax namespace from Java EE.

We'll fix that, thank you for pointing it out.

**Comment by jansupol** [comment]
Fixed by #5197
