### ISSUE TITLE
jersey-media-multipart depends on JUnit - regression

### ISSUE THREAD

**Issue by benken-parasoft** [eclipse-ee4j/jersey#5226]
After upgrading from Jersey 2.37 to 2.38, my project's main sources started building against JUnit Jupiter which is now getting pulled in as a transitive dependency of jersey-media-multipart.  The JUnit dependency in the pom for jersey-media-multipart is missing ```<scope>test</scope>```.

The pom for jersey-media-multipart 2.38 has this:
```xml
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>
```

The pom for jersey-media-multipart 2.37 is also missing test scope:
```xml
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
        </dependency>
```
Even though "test" scope is missing in 2.37, this problem was not visible in 2.37 because dependencyManagement for org.glassfish.jersey:project forced test scope:
```xml

            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>4.13.1</version>
                <scope>test</scope>
            </dependency>
```
In 2.38, dependencyManagement for org.glassfish.jersey:project now imports the JUnit BOM (which is good):
```xml
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${junit5.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

So, now that the JUnit BOM is imported, any projects missing "test" scope for junit-jupiter need to be corrected.  I noticed this for jersey-media-multipart but didn't check if any other Jersey modules also have the same issue.

As a workaround, I have to force an exclusion in my project's pom:
```xml
        <dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-multipart</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.jupiter</groupId>
                    <artifactId>junit-jupiter</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by cmuchinsky** [comment]
I attempted to work around the issue in gradle using a similar `org.junit.jupiter` group exclusion, but found that the `org.apiguardian:apiguardian-api` and `org.opentest4j:opentest4j` dependencies still came thru at compile time.

I added those as exclusions as well, but then realized that I would need to add the same exclusions to any of my modules that depend on jersey-media-multipart transitively, which is too many to account for.
