### ISSUE TITLE
3.1.0: java.lang.NoClassDefFoundError: jakarta/ws/rs/core/MultivaluedMap

### ISSUE THREAD

**Issue by pemko123** [eclipse-ee4j/jersey#5239]
I updated my project to Java 17/Wildfly 27/Keycloak 19 and I get the error:

java.lang.NoClassDefFoundError: jakarta/ws/rs/core/MultivaluedMap

The library Maven: jakarta.ws.rs-api is added in the library of the project via Maven: jakarta.ws.rs:jakarta.ws.rs-api:3.1.0

Does somebody know why this happens?

**Comment by senivam** [comment]
I think you've got the answer at [stackoverflow](https://stackoverflow.com/questions/75206317/java-lang-noclassdeffounderror-jakarta-ws-rs-core-multivaluedmap)

**Comment by pemko123** [comment]
I got an answer but sadly it's not working

**Comment by senivam** [comment]
If you cannot figure out what's happening, using the answer provided at StackOverflow, probably a better place to ask would be the RESTEasy dev community. Based on dependencies provided at StackOverflow, the RESTEasy framework is used as JAXRS implementation. The question does not relate to Jersey. 
```
<dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-client</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-jaxrs</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-jaxb-provider</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-jackson2-provider</artifactId>
            <scope>compile</scope>
        </dependency>
```
