### ISSUE TITLE
Client Logging not working at all

### ISSUE THREAD

**Issue by boyi01** [eclipse-ee4j/jersey#5274]
Hey,

i have problems with using the Client-Side Logging. Maybe i did something wrong, but i have no idea what.

The logging is not working at all.

`import jakarta.ws.rs.client.Client;
import jakarta.ws.rs.client.ClientBuilder;
import jakarta.ws.rs.client.Entity;
import jakarta.ws.rs.client.WebTarget;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.glassfish.jersey.client.ClientConfig;
import org.glassfish.jersey.logging.LoggingFeature;
import org.glassfish.jersey.logging.LoggingFeature.Verbosity;

public class Main {
  public static void main(String[] args){
    Logger logger = Logger.getLogger("test");
    logger.log(Level.INFO,"test");
    logger.setLevel(Level.ALL);
    LoggingFeature loggingFeature = new LoggingFeature(logger, Level.ALL, Verbosity.PAYLOAD_ANY,null);
    Client client = ClientBuilder.newClient();
    client.register(loggingFeature);
    WebTarget webTarget = client.target("http://google.com");
    Response response = webTarget.request().get();
    logger.log(Level.INFO,String.valueOf(response.getStatus()));
  }
}`

[TestJerseyClient.zip](https://github.com/eclipse-ee4j/jersey/files/10862222/TestJerseyClient.zip)

Expected Log would look like this as described in the docu,:
  1 May 09, 2020 2:55:33 PM org.glassfish.jersey.logging.LoggingInterceptor log
  2 INFO: 1 * Server has received a request on thread grizzly-http-server-0
  3 1 > GET http://localhost:9998/helloworld
  4 1 > accept: text/plain
  5 1 > accept-encoding: gzip,deflate
  6 1 > connection: Keep-Alive
  7 1 > host: localhost:9998
  8 1 > user-agent: Jersey/3.0.0 (Apache HttpClient 4.5.9)
  9 
 10 May 09, 2020 2:55:33 PM org.glassfish.jersey.logging.LoggingInterceptor log
 11 INFO: 1 * Server responded with a response on thread grizzly-http-server-0
 12 1 < 200
 13 1 < Content-Type: text/plain
 14 Hello World!

The resulted log can be seen in the posting of senivam

**Comment by senivam** [comment]
running attached reproducer actually logs something:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< org.example:TestJerseyClient >--------------------
[INFO] Building Archetype - TestJerseyClient 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:3.0.0:java (default-cli) @ TestJerseyClient ---
Mar 02, 2023 9:23:37 AM Main main
INFO: test
Mar 02, 2023 9:23:37 AM Main main
INFO: 200
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.728 s
[INFO] Finished at: 2023-03-02T09:23:37+01:00
[INFO] ------------------------------------------------------------------------
```

**Comment by senivam** [comment]
the example was run as: ``mvn exec:java -Dexec.mainClass=Main``
Environment:
```
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: apache-maven-3.8.6
Java version: 19.0.1, vendor: Oracle Corporation, runtime: 19.0.1-open
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-60-generic", arch: "amd64", family: "unix"
```

**Comment by senivam** [comment]
Regarding LoggingFeature - there are at least 2 possibilities for Logging Handler settings.
1. Set it programmatically like 
```
        Logger logger = Logger.getLogger("test");
        ConsoleHandler handler = new ConsoleHandler();
        handler.setLevel(Level.ALL);
        logger.addHandler(handler);
        logger.setLevel(Level.ALL);
```
2. Create `logging.properties` file with something like:
```
handlers=java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level=FINEST
java.util.logging.SimpleFormatter.format=%4$-7s [%3$s] %5$s%6$s%n

#All log level details
#.level=FINEST
test.level=FINEST
```
but in that case, you should not use Level.ALL in your app, only in the `logging.properties` file

**Comment by senivam** [comment]
@boyi01 , the logging output level is all about `java.util.logging.Logger` fine-tuning. When there is no logging Handler defined by user the Logging framework defines one itself with the default logging level which is INFO. So, when you supply the logging level to the `LoggingFeature`, it only tries to match the level supplied with a logger handler. And as soon as there is no logger configured for the `ALL` logging level, there is nothing logged out to the console.  However, if you supply logger handler which is configured for the log level `ALL` it will work (the 1st option from my answer). 
From the provided reproducer, if you try to execute `logger.getHandlers` without any other changes you will notice that there are no handlers. But for the `INFO` level it works because it is the default logging level. So, if you do not want to configure any particular logging handler for the LoggingFeature, the only option is to use `INFO` logging level.

**Comment by boyi01** [comment]
Ahh, oky thank you,

now I still have the problem: when I use this inside my wildfly server i don't get any logs...
Do you have an idea? The exact same code is running in my test project. The created logger is working too

**Comment by senivam** [comment]
Regarding application servers - regularly there are logging configurations related to a particular server. I do not know much about WildFly logging configuration, but I can advise to take a look at [their documentation](https://docs.jboss.org/author/display/WFLY10/Logging%20Configuration.html). Basically again it's about `logging.properties` file and its proper location.
