### ISSUE TITLE
JavaNetHttpConnector behavior conflicts with TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorContext)'s isEmpty() call

### ISSUE THREAD

**Issue by oramattkosem** [eclipse-ee4j/jersey#5307]
Environment:
Jersey 3.1
JDK17
JavaNetHttpConnector

Scenario:
Use JerseyClient to perform a call against an endpoint that returns no response (void on the server side, returning 204).

Expected result:
The client should successfully identify that the call has no input and should not fail with an error like this:
`org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=application/octet-stream, type=void, genericType=void.`

Actual result:
When TerminalReaderInterceptor makes its call to `org.glassfish.jersey.message.internal.EntityInputStream.isEmpty()`, the result is false.  This occurs because this call within EntityInputStream receives a reply of 1 from the underlying InputStream during this call:
```
                   if (in.available() > 0) {
                        return false;
                    } 
```

This occurs because the JDK code in `jdk.internal.net.http.ResponseSubscribers.HttpResponseInputStream.available()` returns a value of 1.
```
        @Override
        public int available() throws IOException {
            // best effort: returns the number of remaining bytes in
            // the current buffer if any, or 1 if the current buffer
            // is null or empty but the queue or current buffer list
            // are not empty. Returns 0 otherwise.
            if (closed) return 0;
            int available = 0;
            ByteBuffer current = currentBuffer;
            if (current == LAST_BUFFER) return 0;
            if (current != null) available = current.remaining();
            if (available != 0) return available;
            Iterator<?> iterator = currentListItr;
            if (iterator != null && iterator.hasNext()) return 1;
            if (buffers.isEmpty()) return 0;
            return 1;
        }
```

This happens, even though there truly is no response, because the buffers queue contains a single ByteBuffer with no capacity:
![inputstreamerror](https://user-images.githubusercontent.com/117667459/232095124-ad173120-c2f7-4a4f-9ea6-eba8fd03935d.png)

The Javadocs for the InputStream.available() method do suggest it to be an "estimate" so it is not clear if this behavior is necessarily a "bug" in the JDK, nevertheless Jersey is unable to obtain a message body provider and calls like this fail.

**Comment by jansupol** [comment]
We would need a reproducer. We have a [test case](https://github.com/eclipse-ee4j/jersey/blob/3.1/connectors/jnh-connector/src/test/java/org/glassfish/jersey/jnh/connector/NoEntityTest.java) that passes just fine.

**Comment by oramattkosem** [comment]
Can do.  The test case will pass if run on JDK11.  In JDK17 it fails as indicated above, even if just driving the client directly, because available() returns 1.

**Comment by oramattkosem** [comment]
@jansupol the existing test is sufficient for reproducing the scenario with the following additions.

The missing pieces in the current suite are:
1. An endpoint that returns success
2. A get() call requesting a result

```
diff --git a/connectors/jnh-connector/src/test/java/org/glassfish/jersey/jnh/connector/NoEntityTest.java b/connectors/jnh-connector/src/test/java/org/glassfish/jersey/jnh/connector/NoEntityTest.java
index 0954072..5db0e24 100644
--- a/connectors/jnh-connector/src/test/java/org/glassfish/jersey/jnh/connector/NoEntityTest.java
+++ b/connectors/jnh-connector/src/test/java/org/glassfish/jersey/jnh/connector/NoEntityTest.java
@@ -1,96 +1,112 @@
 /*
  * Copyright (c) 2022, 2023 Oracle and/or its affiliates. All rights reserved.
- *
  * This program and the accompanying materials are made available under the
  * terms of the Eclipse Public License v. 2.0, which is available at
  * http://www.eclipse.org/legal/epl-2.0.
- *
  * This Source Code may also be made available under the following Secondary
  * Licenses when the conditions for such availability set forth in the
  * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
  * version 2 with the GNU Classpath Exception, which is available at
  * https://www.gnu.org/software/classpath/license.html.
- *
  * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
  */
 
 package org.glassfish.jersey.jnh.connector;
 
+import java.util.logging.Logger;
+
 import org.glassfish.jersey.client.ClientConfig;
 import org.glassfish.jersey.logging.LoggingFeature;
 import org.glassfish.jersey.server.ResourceConfig;
 import org.glassfish.jersey.test.JerseyTest;
-
-import java.util.logging.Logger;
-
-import jakarta.ws.rs.GET;
-import jakarta.ws.rs.POST;
-import jakarta.ws.rs.Path;
-import jakarta.ws.rs.client.WebTarget;
-import jakarta.ws.rs.core.Application;
-import jakarta.ws.rs.core.Response;
 import org.junit.jupiter.api.Test;
 
-public class NoEntityTest extends JerseyTest {
-    private static final Logger LOGGER = Logger.getLogger(NoEntityTest.class.getName());
+import jakarta.ws.rs.*;
+import jakarta.ws.rs.client.WebTarget;
+import jakarta.ws.rs.core.*;
 
-    @Path("/test")
-    public static class HttpMethodResource {
-        @GET
-        public Response get() {
-            return Response.status(Response.Status.CONFLICT).build();
-        }
+public class NoEntityTest
+    extends JerseyTest {
+  private static final Logger LOGGER = Logger.getLogger(NoEntityTest.class.getName());
 
-        @POST
-        public void post(String entity) {
-        }
+  @Test
+  public void testGet() {
+    WebTarget r = target("test");
+
+    for (int i = 0; i < 5; i++ ) {
+      Response cr = r.request().get();
+      cr.close();
+    }
+  }
+
+  @Test
+  public void testGetGenericVoid() {
+    WebTarget r = target("test/success");
+    for (int i = 0; i < 5; i++ ) {
+      r.request().get(new GenericType<Void>() {});
+    }
+  }
+
+  @Test
+  public void testGetVoid() {
+    WebTarget r = target("test/success");
+    for (int i = 0; i < 5; i++ ) {
+      r.request().get(void.class);
+    }
+  }
+
+  @Test
+  public void testGetWithClose() {
+    WebTarget r = target("test");
+    for (int i = 0; i < 5; i++ ) {
+      Response cr = r.request().get();
+      cr.close();
+    }
+  }
+
+  @Test
+  public void testPost() {
+    WebTarget r = target("test");
+    for (int i = 0; i < 5; i++ ) {
+      Response cr = r.request().post(null);
+    }
+  }
+
+  @Test
+  public void testPostWithClose() {
+    WebTarget r = target("test");
+    for (int i = 0; i < 5; i++ ) {
+      Response cr = r.request().post(null);
+      cr.close();
+    }
+  }
+
+  @Override
+  protected Application configure() {
+    ResourceConfig config = new ResourceConfig(HttpMethodResource.class);
+    config.register(new LoggingFeature(LOGGER, LoggingFeature.Verbosity.PAYLOAD_ANY));
+    return config;
+  }
+
+  @Override
+  protected void configureClient(ClientConfig config) {
+    config.connectorProvider(new JavaNetHttpConnectorProvider());
+  }
+
+  @Path("/test")
+  public static class HttpMethodResource {
+    @GET
+    public Response get() {
+      return Response.status(Response.Status.CONFLICT).build();
     }
 
-    @Override
-    protected Application configure() {
-        ResourceConfig config = new ResourceConfig(HttpMethodResource.class);
-        config.register(new LoggingFeature(LOGGER, LoggingFeature.Verbosity.PAYLOAD_ANY));
-        return config;
+    @GET
+    @Path("/success")
+    public Response getSuccessfully() {
+      return Response.status(Response.Status.NO_CONTENT).build();
     }
 
-    @Override
-    protected void configureClient(ClientConfig config) {
-        config.connectorProvider(new JavaNetHttpConnectorProvider());
-    }
-
-    @Test
-    public void testGet() {
-        WebTarget r = target("test");
-
-        for (int i = 0; i < 5; i++) {
-            Response cr = r.request().get();
-            cr.close();
-        }
-    }
-
-    @Test
-    public void testGetWithClose() {
-        WebTarget r = target("test");
-        for (int i = 0; i < 5; i++) {
-            Response cr = r.request().get();
-            cr.close();
-        }
-    }
-
-    @Test
-    public void testPost() {
-        WebTarget r = target("test");
-        for (int i = 0; i < 5; i++) {
-            Response cr = r.request().post(null);
-        }
-    }
-
-    @Test
-    public void testPostWithClose() {
-        WebTarget r = target("test");
-        for (int i = 0; i < 5; i++) {
-            Response cr = r.request().post(null);
-            cr.close();
-        }
-    }
+    @POST
+    public void post(String entity) {}
+  }
 }
```

**Comment by jansupol** [comment]
This is a bit awkward scenario. The `Invocation.Builder#get(void.class)` expects a return type `Void`, but the only `Void` one can create is `null`. So you send a GET request requiring the response to be `null`? I can understand it for 204, but still, this construct won't even allow you to check the response status whether it went as expected.

Do I assume correctly this "Void" class is a result of some automatism that puts the argument into the `get` method so that you cannot use `get()` without an argument? If so, I'd suggest using `Response.class` instead of `Void.class`.

**Comment by oramattkosem** [comment]
It's a common pattern. Jersey's provided org.glassfish.jersey.client.proxy.WebResourceFactory and org.glassfish.jersey.microprofile.restclient.RestClientBuilderImpl impls of "type safe APIs" both do this.

In cases like this, you can determine if the response is as expected by noting the lack of exceptions. When using this pattern, successful replies return WebApplicationException, which can be used to obtain the actual response.

**Comment by jansupol** [comment]
Sorry, no. You can get 404, but that would not cause `WebApplicationException` to be thrown.

You argue with `WebResourceFactory` and `RestClientBuilder` but both are proxies, they do not have `get(void.class)` methods. I do not see any relevance to this.

**Comment by oramattkosem** [comment]
That's not accurate.  If you follow this path, a javax.ws.rs.NotFoundException (a subclass of javax.ws.rs.WebApplicationException) is thrown.

Both of those classes create proxies of whatever API you provide.  If the API has methods returning void or Void, a call to get(void.class)/get(Void.class) is made.

**Comment by oramattkosem** [comment]
For what it's worth, this misbehavior isn't specific to just the void/Void use case.  Any other object type tied to a 204 response produces this behavior as well, this exception ends up getting thrown where any 204/null scenario is found.
