### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by dtbaum** [eclipse-ee4j/jersey#5358]
When the first GET request is in progress, all parallel requests from other Jersey clients, in other threads, fail with **SSLHandshakeException: PKIX path building failed**. 
Once the first GET request is completed,  all subsequent requests work without error.
Here is the code which demonstrates this issue:
https://github.com/dtbaum/jersey-bug-report

The fix in HttpUrlConnector.java solved the issue, see pull request https://github.com/eclipse-ee4j/jersey/pull/5359.
Affected versions: at least 3.1.2 & OpenJDK17 and 2.37 & OpenJDK 8

**Comment by fwippe** [comment]
@senivam @jansupol @dtbaum Please note that this change has been having a drastic impact on performance, in particular when using Jersey client for multiple services: Only one connection can be created at a time, across all routes. If the intention had been to just synchronize `HttpsURLConnection.getDefaultSSLSocketFactory(),` as an alternative you could have introduced a lazy one-off supplier initializing the socket factory. What do you think?

See https://github.com/eclipse-ee4j/jersey/issues/5738 for performance impact in practice.
