### ISSUE TITLE
Micrometer Observation support

### ISSUE THREAD

**Issue by marcingrzejszczak** [eclipse-ee4j/jersey#5371]
I'm a co-maintainer of [Spring Cloud Sleuth](https://github.com/spring-cloud/spring-cloud-sleuth/) and [Micrometer](https://micrometer.io/) projects (together with @shakuzen and @jonatan-ivanov).

[Micrometer Observation](https://micrometer.io/docs/observation) is part of the Micrometer 1.10 release and [Micrometer Tracing](https://micrometer.io/docs/tracing) is a new project. The idea of Micrometer Observation is that you instrument code once but you get multiple benefits out of it - e.g. you can get tracing, metrics, logging or whatever you see fit).

Since this project already records metrics I was curious if there's interest in adding Micrometer Observation support so that except for metrics, spans could be created and tracing context propagation could happen too. Via Micrometer Tracing one can use OpenTelemetry or OpenZipkin Brave Tracer, but with the handler mechanism the possibilities are endless :)

If there's such interest we could provide a PR to add support for that.

**Comment by marcingrzejszczak** [comment]
It's worth mentioning that we already have such instrumentation in [Micrometer](https://github.com/micrometer-metrics/micrometer/tree/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jersey/server) and we would be happy to donate it to this project and help maintain it in the future

**Comment by jansupol** [comment]
Hi @marcingrzejszczak,
This sounds great! We would be happy to see a contribution of Micrometer integration. 

As you can see, we have some [MicroProfile extensions](https://github.com/eclipse-ee4j/jersey/tree/2.x/ext/microprofile), I can imagine having Micrometer extensions in the `ext/micrometer` the similar way.

How can we help you with the PR? Are there any details you would like to discuss?

**Comment by marcingrzejszczak** [comment]
Sorry for the delay - I was on PTO.

https://github.com/eclipse-ee4j/jersey/pull/5391 this is a PR that basically has the port of what we currently have in Micrometer. It has tests for metrics and observability listeners. This is an example of how the trace looks like from the point of view of the server 
![image](https://github.com/eclipse-ee4j/jersey/assets/3297437/0b8018fb-e95f-49e5-a284-d2d5b9aa0cf1)
