### ISSUE TITLE
Where is the source code for Jersey 1.19.4 stored?

### ISSUE THREAD

**Issue by Lastoneee** [eclipse-ee4j/jersey#5397]

**Comment by jansupol** [comment]
[It is](https://github.com/javaee/jersey-1.x) in the old javaee GitHub org.

**Comment by Lastoneee** [comment]
In the old warehouse, only 1.19.3 was seen, not 1.19.4

**Comment by jansupol** [comment]
You are certainly right. Given that no other repository of Jersey 1.x is available, I'd expect the 1.19.4 to be built from the master.

**Comment by Lastoneee** [comment]
Could you please tell me the specific commit id of jersey 1.19.4?

**Comment by jansupol** [comment]
What makes you think it is not the Change-Id: Iba664fb1a46889bac3c37c9c3c52d1f19a97d0e3, named `Pre-release copyright update`, made the exact date the 1.19.4 was put to maven central?

**Comment by Lastoneee** [comment]
Only Jersey 1.19.4 artifacts are found in the Maven repository, but related tags are not found in the Git source code repository.

**Comment by Lastoneee** [comment]
[And the same people asking the same questions](https://github.com/javaee/jersey-1.x/commit/864a01d7be490ab93d2424da3e446ad8eb84b1e8#comments)

**Comment by jansupol** [comment]
It looks like the tag was not created in 2017, and the javaee repository is locked now, sorry.
