### ISSUE TITLE
Getting HTTP status 500 with Jersey libraries and JDK 11

### ISSUE THREAD

**Issue by shidrogo** [eclipse-ee4j/jersey#5400]
Hello,

We are migrating from Java 1.8 to JDK 11 and getting the following exceptionwith the Jersey libraries, it was working before without any issues:

Type Exception Report

Message Servlet.init() for servlet [NRBREST] threw exception

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

javax.servlet.ServletException: Servlet.init() for servlet [NRBREST] threw exception
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.base/java.lang.Thread.run(Thread.java:834)
Root Cause

java.lang.IllegalArgumentException
	jersey.repackaged.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
	jersey.repackaged.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
	jersey.repackaged.objectweb.asm.ClassReader.<init>(ClassReader.java:424)
	org.glassfish.jersey.server.internal.scanning.AnnotationAcceptingListener.process(AnnotationAcceptingListener.java:170)
	org.glassfish.jersey.server.ResourceConfig.scanClasses(ResourceConfig.java:883)
	org.glassfish.jersey.server.ResourceConfig._getClasses(ResourceConfig.java:840)
	org.glassfish.jersey.server.ResourceConfig.getClasses(ResourceConfig.java:755)
	org.glassfish.jersey.server.ResourceConfig$RuntimeConfig.<init>(ResourceConfig.java:1171)
	org.glassfish.jersey.server.ResourceConfig$RuntimeConfig.<init>(ResourceConfig.java:1144)
	org.glassfish.jersey.server.ResourceConfig.createRuntimeConfig(ResourceConfig.java:1140)
	org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:317)
	org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:284)
	org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311)
	org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:168)
	org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:358)
	javax.servlet.GenericServlet.init(GenericServlet.java:158)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.base/java.lang.Thread.run(Thread.java:834)
Note The full stack trace of the root cause is available in the server logs.

Apache Tomcat/8.5.28

![image](https://github.com/eclipse-ee4j/jersey/assets/143644587/f0b3fd0e-3bcc-4cb7-8999-7592d3ee39b5)

Any help will be greatly appreciated!

Regards,
Sandra

**Comment by jansupol** [comment]
I can see you use Jersey 2.6, but JDK 11 has been supported since Jersey 2.29.

**Comment by shidrogo** [comment]
Hello jansupol, 

I have copied the Jersey libraries 2.29, but getting other error:

Type Exception Report

Message Servlet.init() for servlet [NRBREST] threw exception

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

javax.servlet.ServletException: Servlet.init() for servlet [NRBREST] threw exception
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.base/java.lang.Thread.run(Thread.java:834)
Root Cause

java.lang.NoClassDefFoundError: Could not initialize class org.glassfish.jersey.internal.inject.Providers
	org.glassfish.jersey.model.internal.ComponentBag.modelFor(ComponentBag.java:495)
	org.glassfish.jersey.model.internal.ComponentBag.lambda$registerModel$10(ComponentBag.java:454)
	org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	org.glassfish.jersey.model.internal.ComponentBag.registerModel(ComponentBag.java:446)
	org.glassfish.jersey.model.internal.ComponentBag.register(ComponentBag.java:357)
	org.glassfish.jersey.model.internal.CommonConfig.register(CommonConfig.java:480)
	org.glassfish.jersey.server.ResourceConfig.register(ResourceConfig.java:428)
	org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:306)
	org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
	org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:346)
	javax.servlet.GenericServlet.init(GenericServlet.java:158)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.base/java.lang.Thread.run(Thread.java:834)
Note The full stack trace of the root cause is available in the server logs.

Apache Tomcat/8.5.28

web.xml:
<servlet>
		<servlet-name>NRBREST</servlet-name>
		
		<servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class>

		<init-param>
			<param-name>jersey.config.server.provider.packages</param-name>
			<param-value>com.hp.vzw.spc.nrb.rest</param-value>
		</init-param>

		<init-param>
			<param-name>jersey.config.server.provider.classnames</param-name>
			<param-value>org.glassfish.jersey.media.multipart.MultiPartFeature</param-value>
		</init-param>

		<load-on-startup>1</load-on-startup>
	</servlet>

**Comment by jansupol** [comment]
> java.lang.NoClassDefFoundError: Could not initialize class org.glassfish.jersey.internal.inject.Providers

It looks like there is dependency conflict, and there is NoClassDefFound. The difference in Jersey 2.29 is that there is an extra module that needs to be added: `org.glassfish.jersey.inject:jersey-hk2`. Do you have that one in your classpath/pom?

**Comment by jansupol** [comment]
BTW I would recommend using the latest Jersey when you migrate, which is currently 2.40.
Jersey 2.26+ is also JAX-RS 2.1 implementation, so you would likely need a new API jar (2.1.6) + some newer HK2 implementation.

**Comment by shidrogo** [comment]
Hello jansupol, thanks for all your help!

I’ve been trying with both versions the 2.29 and 2.40, but I feel like I’m missing things because no one is working for me.

The version 2.29,  it does contain all the Jersey libraries found on this website:

 
![image](https://github.com/eclipse-ee4j/jersey/assets/143644587/b410bfbd-1b84-4e04-8fce-4bb56112e5c7)


On the web.xml,  I have added the entry for “org.glassfish.jersey.inject.jersey-hk2”, just in case it needs initialization, but not sure if I’m on the correct path to make it work good.

		<servlet-name>NRBREST</servlet-name>
		<servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class>

		<init-param>
			<param-name>jersey.config.server.provider.packages</param-name>
			<param-value>com.hp.vzw.spc.nrb.rest</param-value>
		</init-param>

		<init-param>
			<param-name>jersey.config.server.provider.classnames</param-name>
			<param-value>org.glassfish.jersey.media.multipart.MultiPartFeature</param-value>
		</init-param>
		
		<init-param>
			<param-name>org.glassfish.jersey.inject.jersey-hk2</param-name>
			<param-value>com.hp.vzw.spc.nrb.rest</param-value>
		</init-param>

		<load-on-startup>1</load-on-startup>
	</servlet>
    <servlet-mapping>
         <servlet-name>NRBREST</servlet-name>
         <url-pattern>/rest/*</url-pattern>
    </servlet-mapping>	

But still getting the same HTTP Status 500 result:

 
![image](https://github.com/eclipse-ee4j/jersey/assets/143644587/a2aa304b-a9b0-4846-9fae-33f0735604a9)


Regarding the 2.40 version, I’m trying with a helloworld-webapp example for this website, but no luck, it is displaying an error:

Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	HttpServer cannot be resolved to a type
	GrizzlyWebContainerFactory cannot be resolved

	at org.glassfish.jersey.examples.helloworld.webapp.App.main(App.java:32)

![image](https://github.com/eclipse-ee4j/jersey/assets/143644587/9478081f-3952-4687-a813-6efe60a9c6a9)

 

All the 2.40 libraries were added to the classpath:

 
![image](https://github.com/eclipse-ee4j/jersey/assets/143644587/647616f1-85ce-4cc8-bdaa-21c5121dd31f)


Do you know of any suggestion for this issue?, any help will be greatly appreciated it, thank you!

**Comment by jansupol** [comment]
The helloworld-webapp example contains three parts:

1. The App class with `main` method. This executes Grizzly Server and starts Jersey within it. Grizzly Server is an NIO server that understands a minimum bit of Servlet to be able to support Jersey. It is a competitor to Tomcat. The Grizzly container requires `org.glassfish.jersey.containers:jersey-container-grizzly2-servlet`, `org.glassfish.jersey.containers:jersey-container-servlet`, `org.glassfish.jersey.containers:jersey-container-grizzly2-http` and the grizzly itself, i.e. `org.glassfish.grizzly:grizzly-http-servlet`, `org.glassfish.grizzly:grizzly-http-server`, `org.glassfish.grizzly:grizzly-http` and `org.glassfish.grizzly:grizzly-framework.jar`. 

I would strongly recommend you use maven when trying the examples. You can run `mvn dependency:tree` to see all jar dependencies required to run the example.

2. The web.xml and glassfish.xml. The example builds a war archive that can be deployed to any servlet container, such as Tomcat. The war contains the Grizzly dependencies, but they are not required in Tomcat.

3. The HelloWorldTest. The test starts Jersey in the default (Grizzly) container and sends a request to the JAX-RS endpoint. Neither the first nor the third case work with web.xml.

----

Really use maven to compile the example. Maven automatically brings in all dependencies required to prevent the reported NoClassDefFoundError.

**Comment by shidrogo** [comment]
Hello jansupol, thank you for the suggestions and help!

We do have downloaded the 2.40 libraries from a Maveen project, created a new project with the libraries, but for some reason is still not working.

Here is the JerseyTest.jar file with all the 2.40 libraries version:
[ium@BBTPNJ33W06vSPC-C-HP-TLS-01 webapps]$ jar tvf JerseyTest.war
    39 Fri Sep 08 11:04:34 GMT 2023 META-INF/MANIFEST.MF
     0 Fri Sep 08 11:03:06 GMT 2023 META-INF/
     0 Fri Sep 08 11:22:06 GMT 2023 WEB-INF/
     0 Fri Sep 08 11:03:52 GMT 2023 WEB-INF/classes/
     0 Fri Sep 08 11:04:02 GMT 2023 WEB-INF/classes/Test/
   864 Fri Sep 08 11:18:46 GMT 2023 WEB-INF/classes/Test/Hello.java
   890 Fri Sep 08 15:47:42 GMT 2023 WEB-INF/classes/Test/Hello.class
     0 Fri Sep 08 15:43:16 GMT 2023 WEB-INF/lib/
 27006 Thu Sep 07 18:50:14 GMT 2023 WEB-INF/lib/aopalliance-repackaged-2.6.1.jar
 45024 Thu Sep 07 18:50:16 GMT 2023 WEB-INF/lib/hamcrest-core-1.3.jar
200223 Thu Sep 07 18:50:18 GMT 2023 WEB-INF/lib/hk2-api-2.6.1.jar
203358 Thu Sep 07 18:50:22 GMT 2023 WEB-INF/lib/hk2-locator-2.6.1.jar
131590 Thu Sep 07 18:50:24 GMT 2023 WEB-INF/lib/hk2-utils-2.6.1.jar
 25058 Thu Sep 07 18:50:26 GMT 2023 WEB-INF/lib/jakarta.annotation-api-1.3.5.jar
 18140 Thu Sep 07 18:50:28 GMT 2023 WEB-INF/lib/jakarta.inject-2.6.1.jar
 91930 Thu Sep 07 18:50:32 GMT 2023 WEB-INF/lib/jakarta.validation-api-2.0.2.jar
140376 Thu Sep 07 18:50:34 GMT 2023 WEB-INF/lib/jakarta.ws.rs-api-2.1.6.jar
794137 Thu Sep 07 18:50:36 GMT 2023 WEB-INF/lib/javassist-3.29.2-GA.jar
301876 Thu Sep 07 18:50:38 GMT 2023 WEB-INF/lib/jersey-client-2.40.jar
1230119 Thu Sep 07 18:50:42 GMT 2023 WEB-INF/lib/jersey-common-2.40.jar
 78477 Thu Sep 07 18:50:44 GMT 2023 WEB-INF/lib/jersey-hk2-2.40.jar
950564 Thu Sep 07 18:50:48 GMT 2023 WEB-INF/lib/jersey-server-2.40.jar
245039 Thu Sep 07 18:50:50 GMT 2023 WEB-INF/lib/junit-4.11.jar
 19479 Thu Sep 07 18:50:52 GMT 2023 WEB-INF/lib/osgi-resource-locator-1.0.3.jar
   547 Fri Sep 08 14:50:32 GMT 2023 WEB-INF/web.xml

The web.xml:
![image](https://github.com/eclipse-ee4j/jersey/assets/143644587/aeb82a19-f672-4108-b242-51fdf49075bb)


The Hello.java with the methods:

package Test;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

  @Path("/hello")
  public class Hello {

    // This method is called if TEXT_PLAIN is request
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String sayPlainTextHello() {
      return "Hello Jersey";
    }

    // This method is called if XML is request
    @GET
    @Produces(MediaType.TEXT_XML)
    public String sayXMLHello() {
      return "<?xml version=\"1.0\"?>" + "<hello> Hello Jersey" + "</hello>";
    }

    // This method is called if HTML is request
    @GET
    @Produces(MediaType.TEXT_HTML)
    public String sayHtmlHello() {
      return "<html> " + "<title>" + "Hello Jersey" + "</title>"
          + "<body><h1>" + "Hello Jersey" + "</body></h1>" + "</html> ";
    }
  
}

We are getting HTTP 404 status as response:

![image](https://github.com/eclipse-ee4j/jersey/assets/143644587/8d419038-fc7d-41a0-84f7-bc3b88349716)


Do you know of anything that may be failing or something missing?

All your help is really aprreciate it!

**Comment by jansupol** [comment]
It is simple: do just `mvn clean package` or `mvn clean compile` as suggested in the `README.MD`; the maven will build you the war. It should contain additional jars such as `jersey-container-servlet-core.jar` and `jersey-container-servlet.jar`.

**Comment by shidrogo** [comment]
Hi jansupol! thanks so much for you support!

I do have added those libraries but unfortunately it is still not working...

We want to expose web service with a simple Hello.java class as testing:

package Test;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

  @Path("/hello")
  public class Hello {

    // This method is called if TEXT_PLAIN is request
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String sayPlainTextHello() {
      return "Hello Jersey";
    }

    // This method is called if XML is request
    @GET
    @Produces(MediaType.TEXT_XML)
    public String sayXMLHello() {
      return "<?xml version=\"1.0\"?>" + "<hello> Hello Jersey" + "</hello>";
    }

    // This method is called if HTML is request
    @GET
    @Produces(MediaType.TEXT_HTML)
    public String sayHtmlHello() {
      return "<html> " + "<title>" + "Hello Jersey" + "</title>"
          + "<body><h1>" + "Hello Jersey" + "</body></h1>" + "</html> ";
    }
  
}


- What Jersey 2.40 dependencies do we need to have defined in maven's pon.xml file?
- What do we need to have in web.xml file?
- We want to use jerse 2.40 library, running Tomcat XX and OpenJDK Java 11

Thanks a lot for all your responses.

**Comment by shidrogo** [comment]
Nevermind jansupol, it is working now!, I had a wrong line on the web.xml, thanks again for all your support provided! thank you! :)
