### ISSUE TITLE
jersey-container-jetty support for jetty 12

### ISSUE THREAD

**Issue by gluser1357** [eclipse-ee4j/jersey#5401]
Hi, are there plans to support Jetty 12.x in Jersey (jersey-container-jetty-http and jersey-container-jetty-servlet)?
As far as I see the latest version (3.1.3) of these libs depend on Jetty 11.0.15.

**Comment by jansupol** [comment]
Hi, yes, we plan the next 3.1 release will support Jetty 12.x.
