### ISSUE TITLE
FILTER_FORWARD_ON_404 not working with custom ExceptionMapper

### ISSUE THREAD

**Issue by gluser1357** [eclipse-ee4j/jersey#5402]
I'd like to use Jersey (3.1.3) to filter http requests at endpoint /x as follows:

    if /x exists: serve the request,
    if /x does not exist: continue with the next servlet filter in the chain that may handle /x

The whole works when setting property(ServletProperties.FILTER_FORWARD_ON_404, true). But, as soon as I add an jakarta.ws.rs.ext.ExceptionMapper as resource, the request gets aborted and upcoming servlet filters are not executed.

Is there any solution or alternative to get this combination working?

(Looking at the Jersey sources, I'm looking for a way to handle the NotFoundException thrown in org.glassfish.jersey.server.ServerRuntime in case that no endpoint has been found - before calling the ExceptionMapper which effectively aborts the request. I tried also ServerProperties.RESPONSE_SET_STATUS_OVER_SEND_ERROR but this doesn't seem to be relevant here.)

**Comment by jansupol** [comment]
No, I believe there is no such mechanism at the moment. As soon as the ExceptionMapper is applied, the response is returned, and the request is never passed to the underlying container. 

What is your use-case? If you want to pass the request processing outside of Jersey in the ExceptionMapper, should you not do it in the servlet filter?

**Comment by gluser1357** [comment]
Hi, thanks for the quick reply!

Use case 1:
- apply existing jersey filter (encapsulating further filters), e. g. for user authentication and other request processing
- set some properties on the request via containerRequestContext.getHeaders.add(...), httpRequest.setAttribute(...)
- go on with Apache Wicket application that can read and evaluate these properties
- this use case is related to the issue https://github.com/eclipse-ee4j/jersey/issues/4867

Use case 2:
- serve endpoints that the jersey filter knows and can handle, e. g. paths /a, /b and c/ that have been defined via @Path (this works)
- in case of an error while serving one of these endpoints: delegate to custom ExceptionMapper (a non-matching path should NOT be seen as error) (this works too after registering an ExceptionMapper)
- in case that other paths are requested, go on with upcoming filters in the queue that may serve these paths (this works only if no ExceptionMapper has been added)

I think that if ServletProperties.FILTER_FORWARD_ON_404 is set to true, the filter should always continue when none of the @Paths are matching. Regardless of the existence of an ExceptionMapper. At least I would expect that. Maybe a second flag could be added into a next release, something new similar to RESPONSE_SET_STATUS_OVER_SEND_ERROR that can be evaluated before looking and calling the ExceptionMapper? That would be great :-)

**Comment by gluser1357** [comment]
Hi, I added a minimal runnable demo at https://github.com/gluser1357/jerseyissues/tree/issue-5402-forward-on-404-with-exception-mapper, please see readme.txt of this project.

I think the issue could be resolved in `org.glassfish.jersey.server.ServerRuntime.process(ContainerRequest)`:

- Currently : `if (endpoint == null) {throw new NotFoundException();}` // always jumping into custom ExceptionMapper
- Suggested "fix": `if (endpoint == null) {if (runningAsServletFilter && forwardOn404) <... call chain.doFilter() and return.>}` // similar to `ServletContainer.doFilter(...)`

In my opinion, this fix would lead to more consistent behaviour that users commonly know as "servlet filter chain". Especially the naming "FILTER_FORWARD_ON_404" implies to continue if the requested path cannot be served.

Another, possibly even clearer approach would be to introduce a new flag FILTER_FORWARD_ON_NO_MATCHING_PATH: With help of such a flag it would be possible to distinguish between "No path matched" and "response 404" (possibly created by a matching Jersey endpoint). This new flag should default to true and must be checked in the code above and in all places where FILTER_FORWARD_ON_404 is currently checked.

What do you think?

**Comment by jansupol** [comment]
To me, there is some inconsistency in this requirement. Current behaviour: 
1) `if (endpoint == null) {throw new NotFoundException();}`
2) `catch (Exception e) { ExceptionMapper em = findMapper(e);}`
3) `if (em != null) try { return em.toResponse(e); } catch (Exception e2) { return Response.error().build();}`
4) `else if (em == null && FILTER_FORWARD_ON_404) { proceedWithChain(); }` 
5) `else {return Response.error().build();}`

This **requirement A**:
`if /x exists: serve the request,`
`if /x does not exist: continue with the next servlet filter in the chain that may handle /x`
But that works, as you say:
> The whole works when setting property(ServletProperties.FILTER_FORWARD_ON_404, true). 

This **requirement B**:
> Suggested "fix": if (endpoint == null) {if (runningAsServletFilter && forwardOn404) <... call chain.doFilter() and return.>} // similar to ServletContainer.doFilter(...)

That's basically the requirement A, in different words, but this works as you say.

This **requirement C**:
> as soon as I add an jakarta.ws.rs.ext.ExceptionMapper as resource, the request gets aborted and upcoming servlet filters are not executed.

Correct, this does not work, but there is no mention of requirement C in requirement B, which is confusing. So what exactly is it you would like to have? 

FILTER_FORWARD_ON_404 should take place only after the ExceptionMapper is invoked as a last regard unless people start complaining that `ExceptionMapper` ceased to work.

**Comment by gluser1357** [comment]
The relevant point is that, from a users perspective, when using Jersey as Filter (not Servlet), a request to a path that cannot be served by Jersey should not result in an Exception. Especially not when turning on a Flag named "FILTER_FORWARD_ON_404". As soon as an exception (NotFoundException) is created there is currently no way to get out of the custom ExceptionMapper and go on with further filters.

Requirement B says that if no endpoint can be found, and runningAsServletFilter and forwardOn404 are both true, then the next filter shall be called. The observation (you called it Requirement C) is just the current (non-ideal) state, regardless on forwardOn404.

I'm not sure how to solve the problem in code exactly since I don't have the big picture of the sources. I just think it could be solved by taking care of FILTER_FORWARD_ON_404 (or the suggested FILTER_FORWARD_ON_NO_MATCHING_PATH) especially in the if (endpoint == null) line. Sorry if I'm unclear with that, maybe my suggested idea how to "fix" the problem was too confusing.

**Comment by gluser1357** [comment]
Ok, I was wrong. There is a simple way to get out of a custom ExceptionMapper: Assuming that the NotFoundException is only thrown on non-matching paths (and ideally nowhere else) we could simply use the following line in the ExceptionMapper to solve the issue:

`if (e instanceof jakarta.ws.rs.NotFoundException) return Response.status(404).build();`

With this, the next filter in the chain will be called on all paths that Jersey cannot match.

So, nothing to do here. Thank you for you time :-)
