### ISSUE TITLE
Jersey client 3.1.3 is not JDK8 compatible

### ISSUE THREAD

**Issue by pnavato** [eclipse-ee4j/jersey#5406]
[Official documentation](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest3x/modules-and-dependencies.html#d0e560) says that Jersey targets Java 8 BUT v3.1.3 depends on jakarta.ws.rs-api 3.1.0. This new version of jakarta.ws.rs-api targets Jakarta EE 10 instead of Jakarta EE 9 and also **Java 11 instead of Java 8** (see [this page](https://jakarta.ee/specifications/restful-ws/3.1/)).

See also https://stackoverflow.com/questions/77045310/is-jersey-client-3-1-3-jdk8-compatible

**Comment by jansupol** [comment]
Yes, Jersey 3.1.x is Jakarta EE 10 implementation. The minimum JDK version for the entire Jakarta EE 10 is JDK 11. 

If you want Jakarta EE 9 compatible Jersey (and JDK 8 compatible - except for Jetty support), please use Jersey 3.0. (Currently 3.0.11). Jersey 3.0.x depends on jakarta.ws.rs-api 3.0.0.

Jersey 2.x (EE8), 3.0.x (EE9) and 3.1.x (EE10) are being developed concurrently, to satisfy customer needs for different Jakarta EE versions.

We will update the paragraph in the 3.x documentation, thank you for pointing to it.

**Comment by jansupol** [comment]
Jersey discusses the matter in the [Migration Guide ](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest31x/migration.html#mig-3.1.0)

**Comment by senivam** [comment]
fixed by #5407

**Comment by borgogelli** [comment]
Thank you @jansupol
