### ISSUE TITLE
Broken link in javadocs

### ISSUE THREAD

**Issue by NicolaIsotta** [eclipse-ee4j/jersey#5408]
Go to https://javadoc.io/static/org.glassfish.jersey.media/jersey-media-multipart/3.1.3/org/glassfish/jersey/media/multipart/ContentDisposition.html#%3Cinit%3E(org.glassfish.jersey.message.internal.HttpHeaderReader,boolean)
Click on `HttpHeaderReader`
The link does not point to valid javadoc (https://projects.eclipse.org/projects/ee4j.jersey/jersey-common/apidocs/org/glassfish/jersey/message/internal/HttpHeaderReader.html?is-external=true)

**Comment by senivam** [comment]
The mentioned source from the javadoc.io is not ours. 

The main project page is: https://eclipse-ee4j.github.io/jersey/

The original documentation is located here:https://eclipse-ee4j.github.io/jersey.github.io/apidocs/latest31x/jersey/org/glassfish/jersey/media/multipart/ContentDisposition.html

and reference actually works: https://eclipse-ee4j.github.io/jersey.github.io/apidocs/latest31x/jersey/org/glassfish/jersey/message/internal/HttpHeaderReader.html

**Comment by NicolaIsotta** [comment]
I just downloaded the javadoc jar from maven, this is the link in ContentDisposition.html:
```html
<pre>public&nbsp;ContentDisposition&#8203;(<a href="https://projects.eclipse.org/projects/ee4j.jersey/jersey-common/apidocs/org/glassfish/jersey/message/internal/HttpHeaderReader.html?is-external=true" title="class or interface in org.glassfish.jersey.message.internal" class="externalLink">HttpHeaderReader</a>&nbsp;reader,
```
Are the javadocs hosted on github different from the generated jars?

**Comment by senivam** [comment]
hm, shall be the same. Actually, the first step is to publish jar with JavaDoc to maven and then take it and publish its content to the project's site. I will check what's going on.
