### ISSUE TITLE
Injecting `Providers` into `ClientRequestFilter`

### ISSUE THREAD

**Issue by namedgraph** [eclipse-ee4j/jersey#5419]
Hi,

I need to obtain the serialized request entity in a `ClientRequestFilter` using 3.1.0.
My plan was to inject `@Context Providers` which would allow me to obtain an insance of `MessageBodyWriter` and serialize the entity. But the `Providers` is not injected, the value is `null`.

Is that a know limitation? This StackOverflow post suggests the [`Providers` injection should work](https://stackoverflow.com/a/53595552/1003113), but I cannot replicate that. This issue [suggests `@Context HttpHeaders` should work](https://github.com/eclipse/microprofile-rest-client/issues/164), but I'm getting `null` value as well.

More context on my use case: https://stackoverflow.com/questions/77153267/getting-request-entity-in-jerseys-clientrequestfilter

**Comment by namedgraph** [comment]
In the meanwhile I'll try this alternative approach using `WriterInterceptor`: https://stackoverflow.com/a/33519702/1003113

**Comment by jansupol** [comment]
Can you show an example? Providers must work, that is the JAX-RS requirement. HttpHeaders are not required to be injected by the Spec. Indeed, it did not work a few versions back; It should work now, too.

I assume you do not create ClientRequestFilter instance, and you registrate the class instead, right?

**Comment by jansupol** [comment]
I cannot reproduce the issue. Feel free to reopen when you have a reproducer for us.
