### ISSUE TITLE
Content-Disposition header with filename* returns not just the filename

### ISSUE THREAD

**Issue by m1h43l** [eclipse-ee4j/jersey#5429]
I am trying to upload a file. The receiving server (Helidon 2.x) is using jersey-media-multipart. I am getting the filename via the `FormDataContentDisposition` object but the filename is the whole string value from the `filename*` attribute from the `Content-Disposition` header. I would have expected just the real filename.

I have tried this with jersey-media-multipart 2.40.

I am sending this
```
Content-Disposition: form-data; name="avatar"; filename="Ueberflieger.jpg"; filename*=UTF-8'de'%C3%9Cberflieger.jpg
```
and would have expected to get just `Überflieger.jpg` from the `ContentDisposition::getFileName` method but I got `UTF-8'de'%C3%9Cberflieger.jpg`. 

Is this the correct behaviour? If it is then how do I get the expected result of `Überflieger.jpg` from the filename value I get from the ContentDisposition class?

**Comment by jansupol** [comment]
This is encoding as per [RFC 5987](https://datatracker.ietf.org/doc/html/rfc5987) for `Ü`.

**Comment by m1h43l** [comment]
Yes, the encoded value is ok. 

But what I am noting is that `ContentDisposition::getFileName` just returns the encoded value. It doesn't do any decoding. Is this the expected behaviour? Just returning the encoded value and the caller will have to do the decoding by himself?

**Comment by jansupol** [comment]
Shouldn't `ContentDisposition::getFileName` return the filename, i.e. `Ueberflieger.jpg` and `ContentDisposition::getExtendedFilename` return `Überflieger.jpg` ?

**Comment by m1h43l** [comment]
There is no `getExtendedFilename` in jersey-media-multipart 2.40.

**Comment by NicolaIsotta** [comment]
Noticed that behavior too. I have to substring the result, it's quite annoying.
