### ISSUE TITLE
Question related to next jersey release

### ISSUE THREAD

**Issue by gluser1357** [eclipse-ee4j/jersey#5433]
Hi, I'd like to better understand how dates and contents of jersey releases are coordinated. I tried to find something at the mailing list (https://www.eclipse.org/lists/jersey-dev), the wiki roadmap (https://github.com/eclipse-ee4j/jersey/wiki/Road-Map) and the milestone list (https://github.com/eclipse-ee4j/jersey/milestones) but could not find more details on this. A short explaination would be great :)

In particular, we are eagerly waiting for a release containing
- https://github.com/eclipse-ee4j/jersey/issues/4876
- https://github.com/eclipse-ee4j/jersey/pull/5372
- https://github.com/eclipse-ee4j/jersey/pull/5405

Is it correct that release 3.2 (announced for this month) will contain these changes?

Thank you very much for your feedback!

**Comment by jansupol** [comment]
The first release is 2.41, then 3.0.12, then 3.1.4.
3.1.4 will contain 
- https://github.com/eclipse-ee4j/jersey/pull/5372
- https://github.com/eclipse-ee4j/jersey/pull/5405

but not JPMS, which ought to be part of 3.2, hopefully after 3.1.4.

**Comment by gluser1357** [comment]
Ok, thank you, that's great. Could you please add a few words on how you plan contents and dates of upcoming jersey releases (see my first question)? It would help us to sync our own release planning.

**Comment by jansupol** [comment]
ASAP :) We have some open PRs we want to review for the release, hopefully we will be able to finish 2.41 next week. The other releases should come shortly after. As for 3.2, there could be some more work, however.

**Comment by gluser1357** [comment]
Ok, thanks for the info. Looking forward for 3.1.4 and 3.2 :)
