### ISSUE TITLE
Jersey 3 and Spring AOP 6

### ISSUE THREAD

**Issue by PavelTurk** [eclipse-ee4j/jersey#5458]
I am trying to make work Jersey 3.1.1 with Spring AOP 6.0.13 for Spring security. With `jersey-spring6` module Jersey works with Spring context - all dependencies are injected in JAX-RS resources as expected. 

However, when I want to add authorization for my JAX-RS resource using `authorize()` method then `authorize()` is ignored (not called). However, `authorize()` can be set to be called for any Spring controller and then everything works without any problems.

This my code.
```
@Configuration
@EnableWebSecurity(debug = true)
@EnableMethodSecurity
public class SecurityConfig {

    @Bean
    @Role(BeanDefinition.ROLE_INFRASTRUCTURE)
    public Advisor authorize() {
        JdkRegexpMethodPointcut pattern = new JdkRegexpMethodPointcut();
        pattern.setPattern("com.example.FooResource.*");// IT DOESN'T WORK
        //pattern.setPattern("com.example.MyMvcController.*");// IT WORKS

        AuthorizationManager<MethodInvocation> rule = (AuthorizationManager) authorizationManager;
        AuthorizationManagerBeforeMethodInterceptor interceptor =
                new AuthorizationManagerBeforeMethodInterceptor(pattern, rule);
        interceptor.setOrder(AuthorizationInterceptorsOrder.PRE_AUTHORIZE.getOrder() - 1);
        return interceptor;
    }
   ....
}

@Path("/foo")
@Service
public class FooResource {

    @Autowired
    private Bar bar;

    @GET
    @Produces(MediaType.TEXT_HTML)
    @Path("/temp")
    public String temp(@Context HttpServletRequest req) {
        System.out.println(this.bar.returnString());
        return "<body>Hello! This is temp rest</body>";
    }

}
```
Is this a bug or expected behavior?

**Comment by jansupol** [comment]
@PavelTurk Have you found the solution or did you close it because we lack the expertise in spring?

**Comment by PavelTurk** [comment]
@jansupol I studied the problem and came to a conclusion that the problem was in Spring, but not in Jersey. So, I opened this issue - https://github.com/spring-projects/spring-framework/issues/31565 . Spring developers seem to have solved it. Unfortunately I haven't had time to check yet.

**Comment by jansupol** [comment]
@PavelTurk Thank you for adding the reference for others who might hit similar issues.
