### ISSUE TITLE
Is JDK17 supported?

### ISSUE THREAD

**Issue by Lastoneee** [eclipse-ee4j/jersey#5459]
Does Jersey 2.36 and Later Versions Support JDK17?

**Comment by jansupol** [comment]
Yes, see [Wiki](https://github.com/eclipse-ee4j/jersey/wiki/Road-Map#released-2x) for supported JDKs in the releases.
As always, I would recommend using the latest.

**Comment by Lastoneee** [comment]
Okay, thank you.
