### ISSUE TITLE
org.glassfish.jersey.message.internal.MessagingBinders$EnabledProvidersBinder.bindToBinder A class javax.activation.DataSource for a default provider MessageBodyWriter<javax.activation.DataSource> was not found. The provider is not available.

### ISSUE THREAD

**Issue by minfrin** [eclipse-ee4j/jersey#5480]
When jersey v2.41 is started up, the following is logged:

```
28-Nov-2023 15:23:29.662 WARNING [main] org.glassfish.jersey.message.internal.MessagingBinders$EnabledProvidersBinder.bindToBinder A class javax.activation.DataSource for a default provider MessageBodyWriter<javax.activation.DataSource> was not found. The provider is not available.
```

The javax.activation.DataSource appears to be part of obsolete javax.activation API, but this dependency does not come through transitively.

**Comment by jansupol** [comment]
That is a warning for the customers.

The warning says that in case you are using `javax.activation.DataSource`  and you did not put javax.activation or jakarta.activation (1.x) on classpath on JDK 11+, it won't work for you. 

The warning can be turned off by [PROVIDER_DEFAULT_DISABLE](https://eclipse-ee4j.github.io/jersey.github.io/apidocs/latest/jersey/org/glassfish/jersey/CommonProperties.html#PROVIDER_DEFAULT_DISABLE) property.
