### ISSUE TITLE
Did Jersey 3.1.4 remove support for JDK 11?

### ISSUE THREAD

**Issue by dangmai** [eclipse-ee4j/jersey#5483]
Hello,

Based on what I'm reading, it looks like `Jersey 3.1.4` is supposed to be used alongside `Jetty 12`. However, as far as I know `Jetty 12` only supports `JDK >= 17`, while `Jersey 3.1.3` does support `JDK 11`. I didn't expect a patch version upgrade to remove support for a major JDK version, but maybe that's just my own ignorance here. Could you clarify that please? Thank you!

I'm currently using embedded `Jetty 11` with `Jersey 3.1.3` in my project for context. I'd like to update to `3.1.4` purely for the Jackson upgrade that fixes a security vulnerability, but it looks like that's not an option if I want to keep supporting JDK 11 for my users.

**Comment by senivam** [comment]
Hello @dangmai, 
the JDK 11 support is not removed, to keep Jetty 11 connector available, there is new module `jersey-jetty11-connector` which allows to continue usage of the Jetty connector with JDK 11. However if you use Jetty 11 embedded container, I would recommend to wait until the 3.1.5 is released, there will be `jersey-container-jetty11-http` module as well (in the 3.1.4 it is temporary disabled)

**Comment by dangmai** [comment]
I see, thank you for the explanation!

**Comment by senivam** [comment]
the 3.1.5 release is out, so you can use both modules ``jersey-jetty11-connector`` and/or ``jersey-container-jetty11-http``
