### ISSUE TITLE
Shall we start a 4.0 branch?

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jersey#5492]
It might be a good moment to start a 4.0 branch, and for a first PR there update the dependencies to those from the Jakarta EE 11 M1 release. Even though REST isn't available yet, it would be good to start experimenting with especially the dependencies that had a major update.

If the other committers agree, I can do this myself.

**Comment by jansupol** [comment]
We are not there, yet. 

The 4.0 branch is planned to come from 3.2 branch (currently the JPMS branch) we are working on.

Is there any rush for the 4.0 branch? We do not have the Jakarta REST API, yet

**Comment by arjantijms** [comment]
> Is there any rush for the 4.0 branch?

Yes, without very extensive patching we can't build GlassFish. Jersey depends on Jakarta Annotations 2.1 among others, while for the Jakarta EE 11 M1 release Jakarta Annotations 3.0 is used. Since this is a major version update, OSGi (Felix) kills the server when encountering this.

Also, final review for Jakarta EE 11 is at 30 January 2024, so at least starting with a 4.0 branch to show progress would be good.

**Comment by arjantijms** [comment]
Specifically  `org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider` is problematic, as it uses `ManagedBean` which has been removed from the Annotations API, so the code will crash no matter what (even without OSGi).

We can always up-sync a 4.0 branch whenever 3.1-JMPS is done? I can branch 4.0 from 3.1-JMPS, update the dependencies, remove the `ManagedBean` references, and stage a 4.0-alpha1 or maybe even 4.0-gf-alpha1 if that is less intrusive.

Or maybe, to be even less intrusive, a 4.0-gf branch?

**Comment by arjantijms** [comment]
> We do not have the Jakarta REST API, yet

We actually do have it. See https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/ws/rs/jakarta.ws.rs-api/4.0.0-M1/

**Comment by jansupol** [comment]
Having the Jakarta REST 4.0.0 M1 is actually even a bigger issue. As you well know, the API comes with big changes, the `@Context` is no longer there and every entity method requires a new `@Body` annotation for the entity.  

Glassfish contains some REST API methods, for instance, in the console, all of them would be required to be changed. So the question is what is the plan for Glassfish? Will it create M1 release with old Jakarta REST API and all newer, with Jersey that understands those new APIs, or will Glassfish also include the new REST API that would require a bigger change in Jersey injection, too?

**Comment by arjantijms** [comment]
> So the question is what is the plan for Glassfish?

For 8-M1 I'm trying to incorporate as many components with the bar just set to "it compiles" and "it starts". This somewhat aligns with the goals for the Jakarta EE 11 M1 release.

Even without Jakarta REST 4.0.0 M1, Jersey can try to set the compilation target to JDK 17, or even JDK 21 already and try to pass all tests. You can also already incorporate all, or a selection, of the M1 versions of the other APIs. Especially Jakarta Annotations is a relatively simple target (you basically need to remove `@ManagedBean`).

Incidentally, I saw RestEASY has already started their branch as well, and are doing things like the above in that branch.

**Comment by jansupol** [comment]
Jersey already builds on JDK 17 & 21. 

Will start working on 4.x later this week. We need to finish the Christmas release first and split from there.

**Comment by jansupol** [comment]
4.0 branch created.
