### ISSUE TITLE
Unbounded memory use of LRUMap due to removed access synchronization in ProviderBase

### ISSUE THREAD

**Issue by e-hubert-opti** [eclipse-ee4j/jersey#5502]
Jersey 2.41 introduced a regression by porting a change from Jackson removing synchronization while accessing com.fasterxml.jackson.jaxrs.util.LRUMap from com.fasterxml.jackson.jaxrs.base.ProviderBase.

The underlying implementation is non-threadsafe, it simply extends a LinkedHashMap. Concurrently executed put result in _maxEntries of 120 to be useless and depending on the number of endpoint configurations this can grow substantially.

The related commit was:
https://github.com/eclipse-ee4j/jersey/commit/e79aa535afe6f2c9fb7b0a39e4d0cc02d198c99a#diff-2ef29e24080600307e208ebcf3399be243501ea767e94224d4923f1f95828eaeL716

The "upstrream" Jackson change seems to be this. I also added a comment there:
https://github.com/FasterXML/jackson-jaxrs-providers/issues/166

Likely, the best change would be to use a different (thread-safe) LRUMap/Cache implementation, to avoid too much synchronisation overhead while still limiting the memory consumption.

**Comment by jansupol** [comment]
@e-hubert-opti Can you describe the process leading to the ineffective value of _maxEntries? How do the multiple threads skip the check?

**Comment by e-hubert-opti** [comment]
Maybe sharing simple unit tests helps more than long descriptions?

    @Test
    void test_sequential_usage_of_lru_map() {
        Map<Integer, Integer> lruMap = new LRUMap<>(16, 120);

        for (int i = 0; i < 100000; i++) {
            lruMap.put(i, i);
        }

        assertThat(lruMap.size()).isLessThanOrEqualTo(120);
    }

    @Test
    void test_concurrent_usage_of_lru_map() {
        Map<Integer, Integer> lruMap = new LRUMap<>(16, 120);
        ExecutorService executorService = Executors.newFixedThreadPool(10);

        for (int i = 0; i < 100000; i++) {
            int tmp = i;
            executorService.submit(() -> lruMap.put(tmp, tmp));
        }

        assertThat(lruMap.size()).isLessThanOrEqualTo(120);
    }
    
While the first one obviously passes, the second one gives something like this:
java.lang.AssertionError: 
Expecting actual:
  33670
to be less than or equal to:
  120
  
Replacing the LRUMap with a thread-safe implementation or synchronizing it (e,g. lruMap = Collections.synchronizedMap(new LRUMap<>(16, 120)) ) will of course also turn the second test green again.

**Comment by e-hubert-opti** [comment]
As the Jackson maintainers were very responsive and immediately replaced the usage of com.fasterxml.jackson.jaxrs.util.LRUMap by com.fasterxml.jackson.databind.util.LRUMap (see https://github.com/FasterXML/jackson-jaxrs-providers/commit/60e69413eaefeb49add7972e394c04915446cb4f) I adjusted the import in the test above and it looks likes this implementation also fails. Will try to have a closer look.

**Comment by e-hubert-opti** [comment]
All good with the change to com.fasterxml.jackson.databind.util.LRUMap. I had a look in the implementation of PrivateMaxEntriesMap and noticed the async draining, so it is just the test which needs to be adjusted for this.

**Comment by jansupol** [comment]
@e-hubert-opti Thank you, we'll use Jackson 2.16.1 with the fix when available.

**Comment by jansupol** [comment]
2.16.1 is released.
