### ISSUE TITLE
Can I add custom formatting settings to Gson in jersey-media-json-gson?

### ISSUE THREAD

**Issue by Stapxs** [eclipse-ee4j/jersey#5503]
PS: I'm not good at English.

I'm using jersey-media-json-gson to format the return to JSON, but I want to format the date as a string. This can be done by adding some settings to gson, but I don't know what to do.

After reading the document and the existing issue, there seems to be no relevant discussion, or I may have missed it.

sorry for bothering.

**Comment by jansupol** [comment]
You can use `ContextResolver<Gson>` to configure GSON.
Something like:
```
    public static class GsonContextResolver implements ContextResolver<Gson> {
        @Override
        public Gson getContext(Class<?> type) {
            GsonBuilder builder = new GsonBuilder();
            builder.set...
            return builder.create();
        }
    }
```
Then do not forget to register the `GsonContextResolver` to the `ResourceConfig`/`Application`.

**Comment by Stapxs** [comment]
oh okay, thank you very much
