### ISSUE TITLE
InjectionManagerFactory not found in OSGi http service with Declarative service

### ISSUE THREAD

**Issue by AmolFasate** [eclipse-ee4j/jersey#5521]
We are migrating our jetty, jersey library to non vulnerable version for our OSGi project which is based on Declarative service (Apache SCR) and for all the rest API/resource we are getting 404

Here is the OSGi and jar version

org.osgi.core version 6.0.0
org.apache.felix.http.jetty version 4.2.22
glassfish-jersey version 2.41
org.osgi.compendium version 5.0.0
org.glassfish.hk2.hk2-util version 2.6.1
org.glassfish.hk2.hk2-api version 2.6.1
org.glassfish.hk2.hk2-locatorl version 2.6.1
org.glassfish.hk2.external.jakarta.inject version 2.6.1
org.glassfish.hk2.osgi-resource-locator version 1.0.3
org.apache.felix.scr version 2.1.26
org.glassfish.jersey.core.jersey-server version 2.41
org.glassfish.jersey.core.jersey-client version 2.41
org.glassfish.jersey.core.jersey-common version 2.41
org.glassfish.jersey.containers.jersey-container-servlet-core version 2.41
org.glassfish.jersey.media.jersey-media-json-jackson version 2.41
org.glassfish.jersey.ext.jersey-entity-filtering version 2.41

also using 
com.google.inject.guice version 4.0 for additional Binding

After upgrading version we were able to compile the code with JDK 11.
Deploying the generated bundles into Apache Felix but at deployment we are getting InjectionManagerFactory not found error, so we have added org.glassfish.jersey.inject.jersey-hk2 version 2.41 in pom but no use also tried to add in bnd.bnd file also in META-INF/MANIFEST.MF file  but still getting same issue. 
Before adding jersey-hk2 in pom my unit test case were also failing with same error InjectionManagerFactory not found but now my test cases are running successfully but still at,

org.glassfish.jersey.internal.inject.Injections.lookupService(Class<T> clazz) of jersey-common

getting InjectionMangerFactory not found. Please guide us to resolve the issue

**Comment by jansupol** [comment]
Yes, jersey-hk2 is required.

I would expect the Felix environment to print errors in the missing dependencies, without it, I cannot say. Perhaps org.javassist:javassist is missing?

**Comment by AmolFasate** [comment]
![image](https://github.com/eclipse-ee4j/jersey/assets/144648534/5103bd3f-3ff9-4c2c-97ae-d8b612794852)


All my bundles are active also have org.javassist:javassist in place and there is not error at all only at 

httpService.registerServlet(alias.get(), container, null, httpContext); 

which will again lookup InjectionManagerFactory service having optional.empty

![image](https://github.com/eclipse-ee4j/jersey/assets/144648534/590228e3-49dc-4883-8090-e9e8c06293b8)

**Comment by AmolFasate** [comment]
We have resolved with bundle waiter Thanks for support
