### ISSUE TITLE
Headers modified by MultiPartWriter are not sent

### ISSUE THREAD

**Issue by chkpnt** [eclipse-ee4j/jersey#5528]
If the headers don't already include a header `MIME-Version` and a header `Content-Type` with a boundary, they are added by the `MultiPartWriter`:

https://github.com/eclipse-ee4j/jersey/blob/b0c503d04e1712837e7985fccca76cbc1b78e932/media/multipart/src/main/java/org/glassfish/jersey/media/multipart/internal/MultiPartWriter.java#L122-L136

So far so good, but the modified headers won't be sent, instead a warning is logged by `HeaderUtils#checkHeaderChanges(...)`:

https://github.com/eclipse-ee4j/jersey/blob/604cf2e940549fd6f5524c1a5fe37bcaea95dfad/core-common/src/main/java/org/glassfish/jersey/message/internal/HeaderUtils.java#L293-L318

Is this the expected behaviour? Since the headers are modified internally by the library, I'd expect the code to work out of the box.

```
Feb. 08, 2024 2:52:26 PM org.glassfish.jersey.logging.LoggingInterceptor log
INFORMATION: 1 * Sending client request on thread Test worker
1 > POST https://example.com/api/document
1 > Accept: application/json
1 > Content-Type: multipart/form-data
1 > User-Agent: jersey-client/3.1.5 (java)
--Boundary_1_905404580_1707400346199
Content-Type: application/octet-stream
Content-Disposition: form-data; filename="file-1065460366320764802.tmp"; size=7110; name="contents"

%PDF-1.3
%���������
...

--Boundary_1_905404580_1707400346199
Content-Type: application/json
Content-Disposition: form-data; name="metadaten"

{"name":"Passport.pdf","type":"Passport"}
--Boundary_1_905404580_1707400346199--


Feb. 08, 2024 2:52:28 PM org.glassfish.jersey.message.internal.HeaderUtils checkHeaderChanges
WARNUNG: There are some request headers that have not been sent by connector [org.glassfish.jersey.apache.connector.ApacheConnector]. Probably you added those headers in WriterInterceptor or MessageBodyWriter. That feature is not supported by the connector. Please, do not modify headers in WriterInterceptor or MessageBodyWriter or use default HttpUrlConnector instead.
Unsent header changes: [MIME-Version, Content-Type]
```

**Comment by jansupol** [comment]
Unfortunately, you are correct. 

The problem is with mixing the Multipart and Apache connector. The Apache writes down the headers and only then it writes the entity. Since multipart modifies the headers during the entity processing, the changes in HttpHeaders are not reflected by the Apache Http Client.

The Multipart is supported only by the Default Http Connector, by the JDK connector, and only recently by Netty Connector, and for synchronous requests by Jetty Connector.

The documentation has a [big warning](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest31x/client.html#d0e4950) regarding the modification of HTTP headers with the connectors.

**Comment by chkpnt** [comment]
Thanks for the hint regarding the big warning. Yes, after switching to `HttpUrlConnector` or `JettyConnector`, the modified headers have been sent. But it took me a while to verify this: The `LoggingInterceptor` prints for both the `HttpUrlConnector` and the `JettyConnector` the unmodified header, so the output is the same as above. It seems the header is logged to early. I had to setup mitmproxy to verify the actual send request:

![grafik](https://github.com/eclipse-ee4j/jersey/assets/1956979/f07deda3-d824-4e5c-9272-2a612bb0980e)

For the logging issue, I'm filing a separate issue.
