### ISSUE TITLE
Inquiry about Jersey Project Licensing and Third-Party Content Usage

### ISSUE THREAD

**Issue by gumingyu6689** [eclipse-ee4j/jersey#5547]
Dear Jersey Project Maintainers,
I am an engineer at BATW Company, and we are currently evaluating the use of the Jersey framework (version 2.38) in one of our projects. We have encountered some uncertainties regarding licensing and third-party content as outlined in the pom.xml and NOTICE.md files, and we would greatly appreciate your guidance to ensure our compliance with the necessary legal requirements.
Licensing Inconsistency in pom.xml: We have noticed that the project's main license is declared as dual-licensed under EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0, as seen at [pom.xml#L16](https://github.com/eclipse-ee4j/jersey/blob/2.x/pom.xml#L16) https://github.com/eclipse-ee4j/jersey/blob/2.x/pom.xml#L16 . However, further down in the pom.xml, there are references to other licenses, such as BSD 2-Clause, Apache License 2.0, etc. ([pom.xml#L169](https://github.com/eclipse-ee4j/jersey/blob/2.x/pom.xml#L169)) [https:/ /github.com/eclipse-ee4j/jersey/blob/2.x/pom.xml#L169](https://github.com/eclipse-ee4j/jersey/blob/2.x/pom.xml#L169) . Could you please clarify the relationship between the main project license and the licenses of these additional components?
Third-Party Content in NOTICE.md: In the NOTICE.md file https://github.com/eclipse-ee4j/jersey/blob/2.x/NOTICE.md, third-party content is mentioned, but it is not entirely clear to us whether this refers to software that is included within the Jersey source code itself or if it is dynamically linked. Additionally, we would like to understand which third-party software is specifically relevant to the jersey-core-client, jersey-core-common, and jersey-inject-hk2 modules, as these are of particular interest to us.
 
Your insights on these matters are crucial for us to proceed with our project, and we would be grateful for any information or clarification you can provide. We aim to fully respect and adhere to the licensing terms of the software we use.
Thank you in advance for your assistance.

**Comment by jansupol** [comment]
Jersey comes in the form of multiple artifacts. While most artifacts are distributed without third-party dependencies, some bundles (https://mvnrepository.com/artifact/org.glassfish.jersey.bundles) are distributed with them, under the provided licenses. The NOTICE.md (and the pom information) is a summary of all possible licenses used within all kinds of distributable Jersey jars.

Jersey code itself is distributed under the dual license of EPL 2.0/GPL 2.0 with CPE (same as most Jakarta projects), except for some repackaged code.
The artifacts with the repackaged code (such as jersey-core-server, media-json-jackson, jersey-core-common) contain `NOTICE.markdown` files that describe the repacked classes and the license under which those classes exist in their original projects. For instance, Jersey repackages a part of Guava, and the ASM project. 

If you want to double-check, each source class contains the Copyright header and licensing information, except for the repackaged code.

For completeness, the Jersey examples are distributed under a different license (EDL 1.0).

**Comment by jansupol** [comment]
HK2 is also an Eclipse project that shares the license with Jersey.

**Comment by gumingyu6689** [comment]
Thanks for your detail answer，but to make issues more clear I want to double confirm with you：
So that mean for the three libs we concerned：
1. jersey-core-common license  should be ：EPL 2.0/GPL 2.0 with CPE and Apache License, 2.0 and Creative Commons 1.0 (CC0)；
2. jersey-core-client：EPL 2.0/GPL 2.0 with CPE ；
3. jersey-inject-hk2：EPL 2.0/GPL 2.0 with CPE ；
AM I right？

by the way another question if there are any Patent in jersey？

**Comment by jansupol** [comment]
No, there are not any patents in Jersey.

Regarding the license in jersey-core-common, my understanding is that the repackaged ASL 2.0 code and CC0 code are basically the same as having the dependencies themselves on the classpath, so the license of Jersey is EPL 2.0/GPL 2.0 wCPE, while there are implicit dependencies of the given 3rd party code on a classpath. However, I am not a licensing expert. For these types of questions, the Eclipse Foundation provides an email contact [license@eclipse.org](mailto:license@eclipse.org). (See also https://www.eclipse.org/legal/licenses.php).

**Comment by gumingyu6689** [comment]
Thanks for your reply

**Comment by jansupol** [comment]
Another opinion (non-expert) I hear is that Apache and CC licenses are permissive enough to allow Jersey to be distributed under a different license than the Apache and CC licenses (unlike for instance the GPL).

**Comment by jansupol** [comment]
Closing as there likely will be no more comments.

**Comment by jansupol** [comment]
After getting some more information, my (non-legal, non-lawyer) understanding is that

- CC0 is a permissive license,
- Apache license is a weak copyleft license
- 3-Clause BSD (ASM license) is a weak copyleft license

These licenses allow for distribution under the EPL 2.0 / GPL 2.0 with CPE as long as we publicly enlist the attribution to the particles under those licenses included in Jersey.
