### ISSUE TITLE
Carrier Thread pinning on stack CommittingOutputStream.flushBuffer()

### ISSUE THREAD

**Issue by vasanth-bhat** [eclipse-ee4j/jersey#5623]
We are running tests for sample application with Helidon 4.x based on Loom virtual threads  with JDK 21  in the Kubernetes containers.   When running load test with concurrent users we see that application hangs and JVM becomes unresponsive 
we do not see any resource  issues for CPU, Memory, Heap etc.. The usage are  much below the configured capacity. 

In JFR, we do seeing large number of carrier thread pinning on the  below stack.   The pinning is happening when the. org.glassfish.jersey.message.internal.CommittingOutputStream.flushBuffer() is invoking ByteArrayOutputStream.writeTo().

stack snippet below from tracePinnedThreads output:

io.helidon.webserver.observe.tracing.TracingObserver$TracingStreamOutputDelegate.write(TracingObserver.java:525)
**java.base/java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:163) <== monitors:1** 
**org.glassfish.jersey.message.internal.CommittingOutputStream.flushBuffer(CommittingOutputStream.java:278)**    org.glassfish.jersey.message.internal.CommittingOutputStream.commit(CommittingOutputStream.java:232)   org.glassfish.jersey.message.internal.CommittingOutputStream.close(CommittingOutputStream.java:247)   org.glassfish.jersey.message.internal.OutboundMessageContext.close(OutboundMessageContext.java:865)   org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:403)

 The recommendation from teh JDK team was to  modify the implementation of "org.glassfish.jersey.message.internal.CommittingOutputStream.flushBuffer()" to  avoid calling the synchronised  method. ByteArrayOutputStream.writeTo()

Based on the suggestion, the below code change was tried out, in the implementation of CommittingOutputStream.flushBuffer()

private void flushBuffer(boolean endOfStream) throws IOException {
             .........
             ............ 
            if (buffer != null && adaptedOutput != null) {
                //buffer.writeTo(adaptedOutput);
                adaptedOutput.write(buffer.toByteArray());
            }
        }
    }

With this change, we no longer see the carrier thread pinning on this stack.
The ask is to see if this code change can be implemented in Jersey.

**Comment by jansupol** [comment]
At first glance, `adaptedOutput.write(buffer.toByteArray());` seems worse performance-wise as it is synchronized too and it creates a copy of the data buffer for each call. We should measure the performance and have the change for JDK 21+ only, if worse on JDK [8,20)

**Comment by vasanth-bhat** [comment]
Below is the Full stack for the Pinned events. 

`Thread[#50,ForkJoinPool-1-worker-2,5,CarrierThreads]
    java.base/java.lang.VirtualThread$VThreadContinuation.onPinned(VirtualThread.java:183)
    java.base/jdk.internal.vm.Continuation.onPinned0(Continuation.java:393)
    java.base/java.lang.VirtualThread.park(VirtualThread.java:582)
    java.base/java.lang.System$2.parkVirtualThread(System.java:2643)
    java.base/jdk.internal.misc.VirtualThreads.park(VirtualThreads.java:54)
    java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:219)
    java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:754)
    java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:990)
    java.base/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
    java.base/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
    java.base/java.util.concurrent.ArrayBlockingQueue.offer(ArrayBlockingQueue.java:344)
    org.apache.logging.log4j.core.appender.AsyncAppender.transfer(AsyncAppender.java:179)
    org.apache.logging.log4j.core.appender.AsyncAppender.append(AsyncAppender.java:158)
    org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
    org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
    org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
    org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
    org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:683)
    org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:641)
    org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:624)
    org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:560)
    org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
    org.apache.logging.log4j.core.Logger.log(Logger.java:163)
    org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2069)
    org.apache.logging.log4j.internal.DefaultLogBuilder.logMessage(DefaultLogBuilder.java:250)
    org.apache.logging.log4j.internal.DefaultLogBuilder.log(DefaultLogBuilder.java:144)
    org.apache.logging.slf4j.Log4jEventBuilder.log(Log4jEventBuilder.java:116)
    org.apache.logging.slf4j.Log4jEventBuilder.log(Log4jEventBuilder.java:127)
    org.slf4j.jdk.platform.logging.SLF4JPlatformLogger.performLog(SLF4JPlatformLogger.java:152)
    org.slf4j.jdk.platform.logging.SLF4JPlatformLogger.log(SLF4JPlatformLogger.java:130)
    org.slf4j.jdk.platform.logging.SLF4JPlatformLogger.log(SLF4JPlatformLogger.java:105)
    java.base/java.lang.System$Logger.log(System.java:1387)
    io.helidon.common.socket.SocketContext.log(SocketContext.java:73)
    io.helidon.webserver.http1.Http1LoggingConnectionListener.headers(Http1LoggingConnectionListener.java:70)
    io.helidon.webserver.http1.Http1ServerResponse$BlockingOutputStream.write(Http1ServerResponse.java:585)
    io.helidon.webserver.http1.Http1ServerResponse$BlockingOutputStream.write(Http1ServerResponse.java:470)
    java.base/[java.io](http://java.io/).BufferedOutputStream.implWrite(BufferedOutputStream.java:217)
    java.base/[java.io](http://java.io/).BufferedOutputStream.write(BufferedOutputStream.java:200)
    io.helidon.webserver.http1.Http1ServerResponse$ClosingBufferedOutputStream.write(Http1ServerResponse.java:749)
    io.helidon.webserver.observe.tracing.TracingObserver$TracingStreamOutputDelegate.write(TracingObserver.java:525)
    java.base/[java.io](http://java.io/).ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:163) <== monitors:1
    org.glassfish.jersey.message.internal.CommittingOutputStream.flushBuffer(CommittingOutputStream.java:278)
    org.glassfish.jersey.message.internal.CommittingOutputStream.commit(CommittingOutputStream.java:232)
    org.glassfish.jersey.message.internal.CommittingOutputStream.close(CommittingOutputStream.java:247)
    org.glassfish.jersey.message.internal.OutboundMessageContext.close(OutboundMessageContext.java:865)
    org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:403)
    org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:749)
    org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:385)
    org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:375)
    org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:264)
    org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
    org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
    org.glassfish.jersey.internal.Errors.process(Errors.java:292)
    org.glassfish.jersey.internal.Errors.process(Errors.java:274)
    org.glassfish.jersey.internal.Errors.process(Errors.java:244)
    org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
    org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240)
    org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697)
    io.helidon.microprofile.server.JaxRsService.doHandle(JaxRsService.java:228)
    io.helidon.microprofile.server.JaxRsService.lambda$handle$2(JaxRsService.java:185)
    io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
    io.helidon.microprofile.server.JaxRsService.handle(JaxRsService.java:185)
    io.helidon.webserver.http.HttpRoutingImpl$RoutingExecutor.doRoute(HttpRoutingImpl.java:165)
    io.helidon.webserver.http.HttpRoutingImpl$RoutingExecutor.call(HttpRoutingImpl.java:124)
    io.helidon.webserver.http.HttpRoutingImpl$RoutingExecutor.call(HttpRoutingImpl.java:102)
    io.helidon.webserver.http.ErrorHandlers.runWithErrorHandling(ErrorHandlers.java:75)
    io.helidon.webserver.http.Filters$FilterChainImpl.proceed(Filters.java:121)
    io.helidon.webserver.observe.metrics.MetricsFeature.lambda$configureVendorMetrics$2(MetricsFeature.java:90)
    io.helidon.webserver.http.Filters$FilterChainImpl.proceed(Filters.java:119)
    io.helidon.webserver.security.SecurityContextFilter.filter(SecurityContextFilter.java:88)
    io.helidon.webserver.http.Filters$FilterChainImpl.proceed(Filters.java:119)
    io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
    io.helidon.webserver.observe.tracing.TracingObserver$TracingFilter.filter(TracingObserver.java:247)
    io.helidon.webserver.http.Filters$FilterChainImpl.proceed(Filters.java:119)
    io.helidon.webserver.accesslog.AccessLogHttpFeature.filter(AccessLogHttpFeature.java:86)
    io.helidon.webserver.http.Filters$FilterChainImpl.proceed(Filters.java:119)
    io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
    io.helidon.webserver.context.ContextRoutingFeature.filter(ContextRoutingFeature.java:50)
    io.helidon.webserver.http.Filters$FilterChainImpl.proceed(Filters.java:119)
    io.helidon.webserver.http.Filters.executeFilters(Filters.java:87)
    io.helidon.webserver.http.Filters.lambda$filter$0(Filters.java:83)
    io.helidon.webserver.http.ErrorHandlers.runWithErrorHandling(ErrorHandlers.java:75)
    io.helidon.webserver.http.Filters.filter(Filters.java:83)
    io.helidon.webserver.http.HttpRoutingImpl.route(HttpRoutingImpl.java:73)
    io.helidon.webserver.http1.Http1Connection.route(Http1Connection.java:357)
    io.helidon.webserver.http1.Http1Connection.handle(Http1Connection.java:194)
    io.helidon.webserver.ConnectionHandler.run(ConnectionHandler.java:165)
    io.helidon.common.task.InterruptableTask.call(InterruptableTask.java:47)
    io.helidon.webserver.ThreadPerTaskExecutor$ThreadBoundFuture.run(ThreadPerTaskExecutor.java:239)
    java.base/java.lang.VirtualThread.run(VirtualThread.java:309)`

**Comment by vasanth-bhat** [comment]
>> At first glance, adaptedOutput.write(buffer.toByteArray()); seems worse performance-wise as it is synchronized too 

Yes,  BufferedOutputStream.toByteArray()  is synchronised , but it does not lead to the specific issue of carrier thread pinning, as there is no  IO happening from with this  sync block.   

https://github.com/openjdk/jdk/blob/jdk-21%2B35/src/java.base/share/classes/java/io/ByteArrayOutputStream.java

 public synchronized byte[] toByteArray() {
        return Arrays.copyOf(buf, count);
    }

yes,  It does make  Array copy  .

Looking  further at the. stack snippet. in this scenario,  the concrete type of  "adaptedOutput"   is  of. type. "TracingObserver$TracingStreamOutputDelegate" .   

https://github.com/helidon-io/helidon/blob/e93ee0c0c9b8762212a7f07cb473fec6bc52d827/webserver/observe/tracing/src/main/java/io/helidon/webserver/observe/tracing/TracingObserver.java#L490

Further, The BufferedOutputStream.write() is synchronized only  when it is subclassed and not used directly. 
https://github.com/openjdk/jdk/blob/890adb6410dab4606a4f26a942aed02fb2f55387/src/java.base/share/classes/java/io/BufferedOutputStream.java#L87


Stack Snippet

`io.helidon.webserver.http1.Http1ServerResponse$BlockingOutputStream.write(Http1ServerResponse.java:585) io.helidon.webserver.http1.Http1ServerResponse$BlockingOutputStream.write(Http1ServerResponse.java:470) java.base/[java.io](http://java.io/).BufferedOutputStream.implWrite(BufferedOutputStream.java:217) java.base/[java.io](http://java.io/).BufferedOutputStream.write(BufferedOutputStream.java:200) io.helidon.webserver.http1.Http1ServerResponse$ClosingBufferedOutputStream.write(Http1ServerResponse.java:749) io.helidon.webserver.observe.tracing.TracingObserver$TracingStreamOutputDelegate.write(TracingObserver.java:525) java.base/[java.io](http://java.io/).ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:163) <== monitors:1 org.glassfish.jersey.message.internal.CommittingOutputStream.flushBuffer(CommittingOutputStream.java:278) org.glassfish.jersey.message.internal.CommittingOutputStream.commit(CommittingOutputStream.java:232) `

**Comment by jansupol** [comment]
Interesting test results, for buffer=ByteArrayOutputStream, adaptedOutput=FileOutputStream, 32MB written:
```
|    JDK     |     Actual  Method    |      Proposed Method      |
| -------------------------------------------------------------- |  
|     8      |        90ms           |              98ms         |
|     11     |        35ms           |              40ms         | 
|     17     |        45ms           |              50ms         |
|     21     |        43ms           |              48ms         | 
```
It looks like the proposed method is about 10% slowlier, no virtual threads. So we should have this just for virtual threads.

**Comment by jansupol** [comment]
Perhaps a better solution is to have a ByteArrayOutputStream without synchronized blocks, with reentrant locks instead to avoid data copying.

**Comment by jansupol** [comment]
I have copied the ByteArrayOutputStream into a new file and replaced the synchronized with the ReentrantLock. The synchronized blocks are 10x faster.

**Comment by jansupol** [comment]
#5629 Is for 2.x and 3.0, we should check for Thread#isVirtual in 3.1 and forward.

**Comment by jansupol** [comment]
Keep open for 3.1

**Comment by vasanth-bhat** [comment]
#5632 fixes the  issue in 2.4.3. 

Helidon 4.x. uses  jersey 3.1.5 
https://github.com/helidon-io/helidon/blob/main/dependencies/pom.xml
 <version.lib.jersey>3.1.5</version.lib.jersey>

Which version of 3.1  would have this fix for Helidon to uptake?

**Comment by jansupol** [comment]
The next one, 3.1.7

**Comment by vasanth-bhat** [comment]
Has this change has been delivered into in 3.1.7?

**Comment by jansupol** [comment]
Yes

**Comment by vasanth-bhat** [comment]
Thank you @jansupol

**Comment by vasanth-bhat** [comment]
We have verified this fix, we no longer see pinning on this stack , post  fix

**Comment by jansupol** [comment]
@vasanth-bhat 
Great news, thanks!
