### ISSUE TITLE
Jersey 3.1.7 release

### ISSUE THREAD

**Issue by wendigo** [eclipse-ee4j/jersey#5626]
Hi,

I'd like to ask what's the schedule for 3.1.7 release. 

We've recently hit the issue that was already fixed on the 3.1 branch: https://github.com/eclipse-ee4j/jersey/commit/59b7d65a85db0e548bebdb25d78d61aee98aec9b. 

Are there any snapshot releases published to some staging repository?

**Comment by senivam** [comment]
Hi, SNAPSHOTS are not published, regarding release dates of the 3.1.7, presumably, it could be in May, but closer to the end of the month. Any exact date is not determined.

**Comment by mkarg** [comment]
If there is a wishlist, I would be very glad if we could include https://github.com/eclipse-ee4j/jersey/pull/5341.

**Comment by wendigo** [comment]
@mkarg yes please 🕺🏼

**Comment by jansupol** [comment]
Yes, we plan to review 5341 as part of the 3.1 release preparation

**Comment by senivam** [comment]
@wendigo 3.1.7 is in mvn central.
