### ISSUE TITLE
What is the difference between jersey2.x, jersey 3.x and jersey4.x and which one is recommended?

### ISSUE THREAD

**Issue by Lastoneee** [eclipse-ee4j/jersey#5655]
What is the difference between jersey2.x, jersey 3.x and jersey4.x and which one is recommended?

**Comment by jansupol** [comment]
Jersey 2.x is Java EE / Jakarta EE 8 / JAX-RS 2.1 / Jakarta REST 2.1 compatible.
Jersey 3.0.x is Jakarta EE 9 / Jakarta REST 3.0 compatible.
Jersey 3.1.x is Jakarta EE 10 / Jakarta REST 3.1 compatible.
Jersey 4.0.x is Jakarta EE 11 / Jakarta REST 4.0 compatible.

While we would recommend using the latest, it is more on the environment that is to be used.
That depends on the JDK version as well as the container Jersey runs in.

If JDK 8 is to be used (still often a requirement), Jersey 2.x and 3.0 can be used, only. No Jersey 3.1 or 4.0
If JDK 11 is to be used, Jersey 4.0 cannot be used, as it requires JDK 17.

Then if for instance Tomcat is to be used, then 
Tomcat 9 is for Jersey 2.x
Tomcat 10.0.x is for Jersey 3.0
Tomcat 10.1.x is for Jersey 3.1
Tomcat 11.x is for Jersey 4.0

Jersey is often bundled in products, such as in Payara, Glassfish, WebLogic, Helidon, or Jersey can be a part of Spring Boot.
Depending on the version of these products, the compatible version of Jersey is used there.

Jersey 2.x - Payara 5, Glassfish 5, WebLogic 12c (Jersey 2.22.4) , WebLogic 14, Helidon 2
Jersey 3.0 - Glassfish 6, Helidon 3
Jersey 3.1 - Payara 6, Glassfish 7, Helidon 4
Jersey 4.0 - Payara 7, Glassfish 8

**Comment by Lastoneee** [comment]
Thank you

**Comment by Lastoneee** [comment]
One more question please, how long will jersey 2.x be maintained in the future?

**Comment by pizzi80** [comment]
@jansupol :rocket: 

put it on github homepage!!!

If I may suggest the 3.0 line could be put in EOL 
because there should be no single reason to use it instead of 3.1

also Tomcat 10.0 is in EOL since [2022-10-31](https://tomcat.apache.org/tomcat-10.0-eol.html)

**Comment by jansupol** [comment]
We plan to continue to maintain all versions of Jersey (except the obsolete Jersey 1, of course), yet.

There are products with planned releases with the latest Jersey 2.x, 3.0, and 3.1 versions. I personally guess that 2.x and 3.0 EOLs are bound with JDK 8 EOL (2030) but that decision has not been made, yet.

**Comment by Lastoneee** [comment]
Okay, thanks.

**Comment by jansupol** [comment]
Can we close this?

**Comment by Lastoneee** [comment]
Okay, thanks.
