### ISSUE TITLE
"MessageBodyWriter not found for media type=application/xml" error preventing upgrade from 2.32 to 2.33

### ISSUE THREAD

**Issue by jluehe** [eclipse-ee4j/jersey#5670]
We are currently running with Jersey `2.32` and trying to upgrade to latest version. However, trying to upgrade to `2.33` already gives an error:

`org.glassfish.jersey.message.internal.WriterInterceptorExecutor[] [...] MessageBodyWriter not found for media type=application/xml, type=class test.framework.common.pojos.TestResults, genericType=class test.framework.common.pojos.TestResults.`

I have looked at the delta between versions `2.32` and `2.33` (https://github.com/eclipse-ee4j/jersey/compare/2.32...2.33), but don't see anything obvious that could be causing this error. 

There are no other changes.

Any ideas?

**Comment by senivam** [comment]
Do you have 
```
             <groupId>org.glassfish.jersey.media</groupId>
             <artifactId>jersey-media-jaxb</artifactId>
```
dependency in your classpath?  If you use JDK 11+ there should be also 
```
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
```
,
```
           <groupId>com.sun.xml.bind</groupId>
           <artifactId>jaxb-osgi</artifactId>
```
dependencies.

**Comment by jluehe** [comment]
Thank you, @senivam, for your reply!

Yes, I do have the following (we are using JDK 17):

- j`avax.xml.bind:jaxb-api:2.3.0`
- `org.glassfish.jersey.media:jersey-media-jaxb:2.32`

I do not have `com.sun.xml.bind:jaxb-osgi` though. Is it required? As I said, everything works fine with `2.32`, it is only when I upgrade to `2.33` that I get the error ...

**Comment by senivam** [comment]
I hope, in reality, you have 
``
org.glassfish.jersey.media:jersey-media-jaxb:2.33
``
not ``2.32`` as is the previous version you are migrating from. 

could you please supply the output of the ``mvn dependency:tree`` for the module you are having error with?

**Comment by jluehe** [comment]
I am upgrading all Jersey artifacts at the same time, so yes, as part of the upgrade, I am bumping `org.glassfish.jersey.media:jersey-media-jaxb` to `2.33` as well.

Will supply the dependency tree shortly ...

**Comment by jansupol** [comment]
@jluehe I assume this is solved and can be closed?

**Comment by jluehe** [comment]
Thanks for getting back to me, @jansupol! So far I have not been able to resolve the issue, but have not had time to look into it further ...

**Comment by jluehe** [comment]
@jansupol, actually, this is fixed now. Turns out `org.glassfish.jersey.media:jersey-media-jaxb` was missing from the class path. Thanks for your help!
