### ISSUE TITLE
ChunkedInput.close is not sufficient to release client connections

### ISSUE THREAD

**Issue by eddsteel** [eclipse-ee4j/jersey#5679]
Hi folks,

We observed a connection leak in our dropwizard service, using `jersey-client 2.41` to call an endpoint with chunked encoding. The code receives a `ChunkedInput`, processes it, then closes it. We expected this would be sufficient to close the underlying input stream and release the connection, but open connections just increase until the pool is exhausted.

I reproduced the issue [here](https://github.com/eddsteel/zipped-chunked) and raised a dropwizard [issue](https://github.com/dropwizard/dropwizard/issues/8884). Steffen's [reply](https://github.com/dropwizard/dropwizard/issues/8884#issuecomment-2169989863) clearly laid out the reasons for the behaviour (I won't add noise here). This situation seems to be by design in Jersey, specifically `jersey-common` 2.41.

We can release the resources by returning both a `ChunkedInput` and a `Response` object, and closing both. But this seems inconsistent with other parts of the API and the spec where closing an underlying input will have the same effect. I'm not necessarily asking you to change anything, but would be interested in your thoughts on what Steffen said.

Thanks!

**Comment by jansupol** [comment]
Thanks @eddsteel. It looks like the bug has been there for at least 6 years by now.

**Comment by eddsteel** [comment]
Thanks for having a look @jansupol !
