### ISSUE TITLE
Json Jackon Maven test failing for version 3.1.3

### ISSUE THREAD

**Issue by vimalchandts** [eclipse-ee4j/jersey#5681]
Trying to run the unit test for json jackson i.e (org.glassfish.jersey.media:jersey-media-json-jackson) for 3.1.3 version 

```
[ERROR]   The project org.glassfish.jersey.tests:version-agnostic:1.0.8 (/root/json-jack/jersey-3.1.3/tests/version-agnostic/pom.xml) has 3 errors
[ERROR]     Non-resolvable import POM: The following artifacts could not be resolved: org.glassfish.jersey:jersey-bom:pom:3.1.99-SNAPSHOT (absent): Could not transfer artifact org.glassfish.jersey:jersey-bom:pom:3.1.99-SNAPSHOT 
[ERROR]     'dependencies.dependency.version' for org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-bundle:pom is missing. @ line 120, column 29
[ERROR]     'dependencies.dependency.version' for org.glassfish.jersey.connectors:jersey-jetty-connector:jar is missing. @ line 126, column 29
```

However the build for the json jackon are work's fine.

Below are the environment used for the maven test/build
Maven - 3.9.4
Java - 17.0.8

**Comment by jansupol** [comment]
Good point - `org.glassfish.jersey.tests:version-agnostic` test should not refer to a SNAPSHOT. we will fix that.

In case it troubles you, you may just comment out the test module from the `tests/pom.xml'
