### ISSUE TITLE
Issue when injecting @QueryParam values when the URL query string has percentage encoded &

### ISSUE THREAD

**Issue by The-East-Wind** [eclipse-ee4j/jersey#5691]
# Issue

I have a resource like:

```java
@GET 
@Path("/foobar")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public Response get(@QueryParam("x") String x, @QueryParam("y") String y, @QueryParam("z") String z) {
}
```

If I call this resource with `/foobar?x=a%26y=b%26z=c` then `x` get assigned with the value `a%26y=b%26z=c` and `y` and `z` are set to `null`. 

Servlet container: Tomcat 9
Jersey Version: 2.19
Java Version: 1.8

**Comment by jansupol** [comment]
I have tried in later Jersey.
`x` is `a&y=b&z=c`
`y` and `z` is null.

The encoded ampersand is used as an ampersand character inside the query string which is what the encoding is for.

The difference can be in what is actually sent to the server, if `/foobar?x=a%26y=b%26z=c` or some double encoded form (depending on the client). You can check by 
```
@Context UriInfo info;
System.out.println(info.getRequestUri());
```
I get `http://localhost:9998/foobar?x=a%26y=b%26z=c`.

**Comment by jansupol** [comment]
Currently, I'd say Jersey is working properly.
