### ISSUE TITLE
`JerseySseEventSource` ignores `onError` callback supplied to `register()` method, making it impossible to surface HTTP/network errors

### ISSUE THREAD

**Issue by adriansuarez** [eclipse-ee4j/jersey#5693]
It is possible for an SSE endpoint to generate an error.
It can respond with 403 Forbidden or 401 Unauthorized if the user is not authorized or authenticated, or 404 Not Found if the client is communicating with an older version of the server that does not support the SSE endpoint.
Or there can be 5xx or some network error if there are other issues.

In all of these cases, it is useful to surface the actual error so that the user can understand what the problem is.
But the `JerseySseEventSource` seems to ignore the `onError` callback completely.

I have code that looks like this:

```java
try (SseEventSource sseSource = SseEventSource.target(target).build()) {
    // create SSE client and register consumer
    SettableFuture<InboundSseEvent> firstMessage = SettableFuture.create();
    sseSource.register(Functions.asConsumer(sseEvent -> {
        firstMessage.set(sseEvent);
        // do other stuff...
    }), e -> {
        firstMessage.setException(e);
    }, () -> {
        firstMessage.cancel(true);
    });
    // start SSE client and wait for initial message
    sseSource.open();
    firstMessage.get();
    // do other stuff...
} catch (ExecutionException e) {
    e.getCause().printStackTrace();
}
```

I'm expecting the `firstMessage.get()` invocation to generate an `ExecutionException` that carries the underlying cause of the SSE client failing if the endpoint cannot be used to establish an SSE connection, e.g. an exception containing HTTP status and response data. Instead only the `onClose` get invoked, without any useful information being surfaced.

Is this intentional, or is there something that I'm missing?

**Comment by jansupol** [comment]
Your expectations make sense. I assume the error handling was omitted when SSE was transformed from JAX-RS 2.0 compatible JERSEY to 2.1. In the elder Jersey EventSource, it is not possible to register a consumer for throwable there.
