### ISSUE TITLE
Jetty connector is not supported on JDK version less than 17

### ISSUE THREAD

**Issue by sdyavanapelli** [eclipse-ee4j/jersey#5694]
I am getting below error  after upgrading <b>jersey-client</b> <b>3.1.7</b> from <b>3.1.5</b> and also <b>jersey-jetty-client</b> <b>3.1.7</b>.

I have read the documentation  and I am using <b>java 21</b> and <b>maven 3.9.6</b> version.

```bash

jakarta.ws.rs.ProcessingException: Jetty connector is not supported on JDK version less than 17.
        at org.glassfish.jersey.jetty.connector.JettyConnectorProvider.getConnector(JettyConnectorProvider.java:83)
        at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:471)
        at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:321)
        at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:834)

```

pom.xml

```text

 <dependency>
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-client</artifactId>
            <version>3.1.7</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.connectors</groupId>
            <artifactId>jersey-jetty-connector</artifactId>
            <version>3.1.7</version>
        </dependency>
````

I have tested my changes with  <b>jersey-jetty-connector</b> with version <b>3.1.6</b> and <b>4.0.0.M1</b> , both of them are working fine but the issue is only with the <b>jersey-jetty-connector</b> : <b>3.1.7</b>

**Comment by sdyavanapelli** [comment]
Note : we are loading the <b>org.glassfish.jersey.jetty.connector.JettyConnectorProvider</b> as spi.

**Comment by jansupol** [comment]
This is weird,  jersey-jetty-connector 3.1.7 is almost identical to 3.1.6. Check 
- [3.1.6](https://repo1.maven.org/maven2/org/glassfish/jersey/connectors/jersey-jetty-connector/3.1.6/jersey-jetty-connector-3.1.6.jar)
- [3.1.7](https://repo1.maven.org/maven2/org/glassfish/jersey/connectors/jersey-jetty-connector/3.1.7/jersey-jetty-connector-3.1.7.jar)

**Comment by sdyavanapelli** [comment]
yes. The error is only coming from 3.1.7 but not in 3.1.6 and 4.0.0-M1 version, but we have to use 3.1.7 version, can you please look into this.

**Comment by sdyavanapelli** [comment]
<img width="1233" alt="Screenshot 2024-07-09 at 8 18 26 PM" src="https://github.com/eclipse-ee4j/jersey/assets/70435073/c59757a9-9f08-47e1-9858-d8bca2852a82">

<b>It seems that the jersey-jetty-connector-3.1.7 jar is not generating correct profile for jdk 21 </b>, please check.

**Comment by jansupol** [comment]
That's just confusing. You'd get the same result from 3.1.6. It is a multi-release jar, and the proper classes are in  META-INF/versions/17. The class you show is just to warn about using the improper JDK version.

**Comment by sdyavanapelli** [comment]
I suspect this Line is missing in 3.1.7 version in MANIFEST.MF "META-INF
 .versions.17.org.glassfish.jersey.jetty.connector;version="3.1.7". can you check the dependency provided in maven repo :
https://mvnrepository.com/artifact/org.glassfish.jersey.connectors/jersey-jetty-connector/3.1.7

**Comment by sdyavanapelli** [comment]
any update  @jansupol .

**Comment by jansupol** [comment]
I can see the `Export-Package`: contains `META-INF.versions.17.org.glassfish.jersey.jetty.connector;version="3.1.7"`. But that line should not be relevant outside of OSGi.

**Comment by jansupol** [comment]
@sdyavanapelli You can try 3.1.8 if that helps.

**Comment by jansupol** [comment]
I am closing this as not an issue in Jersey.

**Comment by jarinek** [comment]
@sdyavanapelli: Hi, have you found a solution for your issue or understand it?
