### ISSUE TITLE
Memory leak in NonInjectionManager?

### ISSUE THREAD

**Issue by andresluuk** [eclipse-ee4j/jersey#5710]
I was looking at the code of: NonInjectionManager.TypedInstances
https://github.com/eclipse-ee4j/jersey/blob/4.0/core-client/src/main/java/org/glassfish/jersey/client/innate/inject/NonInjectionManager.java
It has multiple fields and a dispose() method:
In dispose() singletonInstances and threadPredestroyables are cleared, but threadInstances is left as-is.
So I had a test case where NonInjectionManager instances was made multiple times and they piled up under the threadlocal.
So my question would be that maybe threadInstances should be set to null on dispose or I think it will not be gcd maybe because the thread that called it is still alive?

**Comment by jansupol** [comment]
First, the NonInjectionManager is merely a backup when the HK2 is not available on a classpath. Please make sure you use this InjectionManager on purpose and not by a wrongly set classpath.

You might be right, the Thread has `ThreadLocalMap`. However, the map seems to keep entries of `WeakReference<ThreadLocal<?>>` which should not prevent the garbage collection. But yes, we can set `threadInstances` to null.

**Comment by jansupol** [comment]
Do you have any reason to believe in the leak? I would rather not remove the `final` keyword for the `threadInstances`.

**Comment by andresluuk** [comment]
I did not get the issue myself, but a client found it and provided an example to reproduce it:

import jakarta.ws.rs.client.Client;
import jakarta.ws.rs.client.ClientBuilder;
import jakarta.ws.rs.client.Invocation.Builder;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;

import org.glassfish.jersey.client.ClientConfig;

public class App {

    public static void main(String[] args) throws Exception {
        System.out.println("Start");
        for (int i = 0; i < 10000; i++) {
            System.out.print(i);
            doCall();
        }
        //a breakpoint here, and you can examine the memory of java application
        System.out.println("Done");
        Thread.sleep(1000000);
        System.out.println("Done really");
    }

    private static void doCall() {
        var config = new ClientConfig();
        Client client = ClientBuilder.newBuilder().withConfig(config).build();
        //take any target url, functional or not,
        //memory leak can be seen even when call fails
        Builder request = client.target("http://www.someplace.com/test")
                .path("dummyCall")
                .request(MediaType.APPLICATION_JSON);
        Response res;
        try {
            res = request.get();
            System.out.println(" status:" + res.getStatus());
        } catch (Exception e) {
            //expected
            System.out.println(" error: " + e.getMessage());
        }
        client.close();
    }
}
With maven dep:
<groupId>org.glassfish.jersey.core</groupId>
<artifactId>jersey-client</artifactId>
<version>3.1.7</version>
For me it does not much matter how Jersey should be used :P for me the issue is that it can be used that way.
Anyway If you run the application and make a memory dump in the end (I used MAT) I could see the leaked instanced and the gc did not clean them up. From the dumps I did not see any WeakReference there, or some part of MultivaluedHashMap should be weak. The stack from MAT:
Class Name                                                                                                      | Shallow Heap | Retained Heap
-----------------------------------------------------------------------------------------------------------------------------------------------
org.glassfish.jersey.client.innate.inject.NonInjectionManager @ 0x6044d4958                                     |           64 |        28 384
'- injectionManager org.glassfish.jersey.client.ClientMessageBodyFactory @ 0x6044d4e98                          |           64 |         4 456
   '- workers org.glassfish.jersey.client.ClientRequest @ 0x6044c68b0                                           |           96 |         1 488
      '- reference org.glassfish.jersey.internal.util.collection.Refs$DefaultRefImpl @ 0x6044c68a0              |           16 |         1 504
         '- instance org.glassfish.jersey.client.innate.inject.NonInjectionManager$InstanceContext @ 0x6044c6888|           24 |            24
            '- item java.util.LinkedList$Node @ 0x6044c6870                                                     |           24 |            48
               '- last, first java.util.LinkedList @ 0x6044c6850                                                |           32 |            80
                  '- value java.util.HashMap$Node @ 0x6044c6830                                                 |           32 |           112
                     '- [2] java.util.HashMap$Node[16] @ 0x6044c67e0                                            |           80 |           192
                        '- table java.util.HashMap @ 0x6044c67b0                                                |           48 |           240
                           '- store jakarta.ws.rs.core.MultivaluedHashMap @ 0x6044c67a0                         |           16 |           256
                              '- value java.lang.ThreadLocal$ThreadLocalMap$Entry @ 0x6044c6770                 |           32 |           288
                                 '- [32861] java.lang.ThreadLocal$ThreadLocalMap$Entry[65536] @ 0x6171ef090     |      262 160 |     3 782 496
                                    '- table java.lang.ThreadLocal$ThreadLocalMap @ 0x60440cb50                 |           24 |     3 782 520
                                       '- threadLocals java.lang.Thread @ 0x604405f40  main Thread              |          112 |     3 782 752
-----------------------------------------------------------------------------------------------------------------------------------------------

**Comment by jansupol** [comment]
@andresluuk Thank you for reporting this! I can confirm the issue. Setting `threadInstances` to null indeed fixes the problem.

**Comment by jansupol** [comment]
@andresluuk Fixed in 3.1.8
