### ISSUE TITLE
Equivalent of com.sun.jersey.api.client.ClientHandler in Jersey 2?

### ISSUE THREAD

**Issue by jluehe** [eclipse-ee4j/jersey#5717]
When migrating from Jersey 1.x to Jersey 2.x, what is the replacement of `com.sun.jersey.api.client.TerminatingClientHandler` or the more generic `com.sun.jersey.api.client.ClientHandler`? Is there a similar concept in Jersey 2, and if not, what are our options/alternatives? Thank you!

**Comment by jansupol** [comment]
There is no single replacement, there are more classes that cover the functionality.

`ClientRequestFilter`, `ClientResponseFilter`, `ReaderInterceptor`, `WriterInterceptor` are just a few examples. It depends what exactly is needed.

**Comment by jluehe** [comment]
Thank you, @jansupol!

We have a custom `TerminatingClientHandler`, which replaces the default `com.sun.jersey.client.urlconnection.URLConnectionClientHandler` and uses some custom logic to produce a `com.sun.jersey.api.client.ClientResponse` from the `com.sun.jersey.api.client.ClientRequest` argument passed to its `handle` method:

```
@Override
public ClientResponse handle(ClientRequest clientRequest) throws ClientHandlerException {
    // Custom logic to process the given clientRequest and produce a clientResponse
}
```
Can you tell me how to migrate this use case to Jersey 2?

**Comment by jansupol** [comment]
Do you mean something like 
```
client
                    .register(new ClientRequestFilter() {
                        @Override
                        public void filter(ClientRequestContext requestContext) throws IOException {
                            requestContext.abortWith(Response.ok().build());
                        }
                    })
```
?

**Comment by jluehe** [comment]
Nice, @jansupol - I think this should work!
