### ISSUE TITLE
Public class removed in bugfix release?

### ISSUE THREAD

**Issue by gus-asf** [eclipse-ee4j/jersey#5720]
https://github.com/eclipse-ee4j/jersey/commit/21668db5a4023634b9568514ebfe80fdd6c2650b#diff-77ffb7eeac2f33be75d8debb4d32cd5fee7f815ab48603081e7a2a35d3d1fdbd

NullOutputStream was **_removed_** which means when gradle tries to substitute the highest version among several dependencies one can get java.lang.ClassNotFoundException errors for this... super irritating, and forcing me to backtrack to 3.1.6 instead of 3.1.7.

Removing public classes is not a typical thing for bugfix releases, and doesn't seem to fit the "3.1 compatible release" phrase.

**Comment by jansupol** [comment]
I agree that we did not need to remove that class.

On the other hand, that is an **internal** package which may be a subject of a change between versions.

I do not see a reason why not to put it back for 3.x

**Comment by gus-asf** [comment]
It's not like I'm using it in my code. Something else is probably invoking it via an older jersey package, but commons got upgraded by something else. The upshot is dropping in your new bugfix version can blow up a project, and reverting resolves the issue. If that's ok then...  I guess it's ok. I'll just fiddle with my dependencies and force it not use your new version.

**Comment by gus-asf** [comment]
Ah I see I failed at parsing the double negative above. Thanks for fixing this.

**Comment by joakime** [comment]
Seeing as Jersey 3.1.x is on JDK11, note that there is a JDK built-in replacement for NullOutputStream.

* https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/OutputStream.html#nullOutputStream()

**Comment by jansupol** [comment]
> Seeing as Jersey 3.1.x is on JDK11, note that there is a JDK built-in replacement for NullOutputStream.

Yes, that's why it has been removed. But the customers are used to utilize Jersey NullOutputStream which is for some reason public.
