### ISSUE TITLE
Despite URI spec when parsing URI query (QueryParam) becomes part of path (PathParam)

### ISSUE THREAD

**Issue by smolnij** [eclipse-ee4j/jersey#5737]
When I use both jakarta.ws.rs @PathParam and @QueryParam, both params are being parsed as part of first PathParam.

Request:

> /user/id11302908?asOf=2024-05-21

In jersey method mapping described like this:

  ```
  @GET
    @Path("/user/{id}")
    public Response getUser(@PathParam("id") final String id, @QueryParam("asOf") final String asOf) {
    System.out.println("id: " + id);
    System.out.println("asOf: " + asOf);
    return null; }

```
Output:

> id: id11302908?asOf=2024-05-21
> asOf: null
> 

i.e. everything is being parsed as first PathParam (id). Isn't it supposed to stop at the question mark and interpret stuff after it as a QueryParam? 
Javadoc here: https://javadoc.io/doc/jakarta.ws.rs/jakarta.ws.rs-api/3.1.0/jakarta.ws.rs/jakarta/ws/rs/Path.html says that it takes as a path everything like this "[^/]+". 
Which looks strange for me, since the spec https://www.rfc-editor.org/rfc/rfc3986.txt says that a path CANNOT include the "?" character (see esp. section 3.3 and the BNF in Appendix 1). (rfc3986 is also referenced from the latest HTTP spec, https://www.rfc-editor.org/rfc/rfc9110.txt).

So path parameter parsing should stop by “?” as well, not only by “/”''

I've tried to write first to jersey+help@javaee.groups.io but nobody responds here.

Thanks!

**Comment by jansupol** [comment]
@smolnij What client do you use?

**Comment by smolnij** [comment]
If I got your question right, I've tried firefox and google chrome to make requests to the API url ( http://<hostname>/user/id11302908?asOf=2024-05-21)

**Comment by smolnij** [comment]
Sorry, found that it was only reproducable with testing with JserseyTest, and not in the prod code. Probably has to do with test config issues. Closing this.

**Comment by jansupol** [comment]
This usually happens when using `target("http://user/id11302908?asOf=2024-05-21")` where the symbol "?" is encoded to be used as a path.
