### ISSUE TITLE
InjecteeSkippingAnalyzer not always installed when needed

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jersey#5745]
`org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider.bindHk2ClassAnalyzer()` contains code to conditionally install `InjecteeSkippingAnalyzer`:

```java
int skippedElements = methodsToSkip.size() + fieldsToSkip.size();

ClassAnalyzer customizedClassAnalyzer = skippedElements > 0
            ? new InjecteeSkippingAnalyzer(defaultClassAnalyzer, methodsToSkip, fieldsToSkip, beanManager)
            : defaultClassAnalyzer;
```

If there are no skipped elements, `InjecteeSkippingAnalyzer` is not used. This assumes only skippedElements that are detected during startup are being used in this analyzer. This is however not true. Runtime ellements are added as per the following code in `org.glassfish.jersey.ext.cdi1x.internal.InjecteeSkippingAnalyzer.addCdiInjectedFieldsToSkip(Set<Field>, Set<Field>)`:

```java
private void addCdiInjectedFieldsToSkip(Set<Field> skippedFields, Set<Field> originalFields) {
        for (Field field : originalFields) {
            if (field.getAnnotation(Inject.class) != null && !cdiComponentProvider.isHk2ProvidedType(field.getType())) {
                skippedFields.add(field);
            }
        }
    }
```

Should the optimising check be totally removed and `InjecteeSkippingAnalyzer` simply always added here?

**Comment by jansupol** [comment]
@arjantijms Thanks. We will use the skipping analyzer.
Fixed by #5750.
