### ISSUE TITLE
NonInjectionManager  produce out of memory error

### ISSUE THREAD

**Issue by skafenko** [eclipse-ee4j/jersey#5805]
Jersey client version = 2.45

Case: When invoke first request or by asynch way or by CompletableFuture jersey create instances of ClientRequest in NonInjectionManager$TypedInstances.threadPredestroyables and they never cleaned until clinet not closed, but i need to reuse client instance.

CODE:
` Client client = ClientBuilder.newClient();

        Response response = client.target("https://google.com").request().get();
        int status = response.getStatus();
        response.close();
        System.out.println(status);
        //Create instance in NonInjectionManager$TypedInstances.threadPredestroyables

        for (int i = 0; i <= 10; i++) {
             client.target("https://google.com").request()
                    .async()
                    .post(Entity.text("text"));
        }
        //Create 10 instance in NonInjectionManager$TypedInstances.threadPredestroyables

        for (int i = 0; i <= 10; i++) {
            CompletableFuture.supplyAsync(() -> {
                Response test = client.target("https://google.com").request()
                        .post(Entity.text("text"));
                int string = test.getStatus();
                test.close();
                System.out.println(string);

                return null;
            }).join();
        }
        //Create 10 instance in NonInjectionManager$TypedInstances.threadPredestroyables

        response = client.target("https://sm-dev.smiddle.lab/MessengerGateway/ping").request().get();
        status = response.getStatus();
        response.close();`

![image](https://github.com/user-attachments/assets/75be15c9-b964-4c14-98f5-5caab4cbcc10)

**Comment by jansupol** [comment]
@skafenko Thank you for testing our NonInjectionManager for the Jersey Client. Its primary purpose at the moment is a fallback when HK2 is not on a classpath. It is not capable of injections the way the JAX-RS Spec mandates, and HK2 is the preferred injection framework backing up the Jersey Client. The intention is to use this NonInjectionManager for the client in Jersey 5, where HK2 will be replaced to better comply with Jakarta REST's next Specification.

We have added a proper cleanup of the `@RequestScoped` objects in #5813.
