### ISSUE TITLE
Jersey update from 3.1.8 to 3.1.9 performance regression when using the JVM `http.proxyHost` mechanism

### ISSUE THREAD

**Issue by ripdajacker** [eclipse-ee4j/jersey#5814]
This PR introduced the regression: https://github.com/eclipse-ee4j/jersey/pull/5749 

The referenced fix introduces a map from `java.util.URL` to a `Lock`. That has the side effect of calling `getInetAddress(url.host)`, which significantly impacts the performance if you are running the JVM with a proxy with `-Dhttp.proxyHost` and `-Dhttp.proxyPort`.

Before the call to `hashCode` the JVM handled the proxy connection transparently.

**Comment by ripdajacker** [comment]
Fixed in: https://github.com/eclipse-ee4j/jersey/pull/5815

**Comment by jansupol** [comment]
Fixed by #5794
